레스토랑 상세 페이지 구현하기
CodeSoom/week6-assignment-1 pull request #101
Opened 2022-09-14 11:55 UTC by ChoJinmok

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 레스토랑 상세 페이지 구현하기
<br />

## :: 구현 사항 설명
- 1차 제출
  - 6주차 강의내용만 반영돼있습니다!
<br />

## :: 기타 질문 및 특이 사항
-

2022-09-14 13:47 UTC, daadaadaah reviewed
강의내용해서라도 PR 날리신거 잘하셨어요!👍 나머지도 완성시켜봅시당👊
다음 PR 기다리고 있을게요!😊

2022-09-15 12:47 UTC, daadaadaah reviewed
fixture 한번 활용해보시면서 계속 진행해주세요!🏃‍♂️ 매일매일 PR 날려주시는 모습 너무 좋습니당👍

2022-09-16 12:27 UTC, daadaadaah requested changes
테스트가 점점 복잡해질수록 test 문 -> descaribe - (context)-it 패턴을 사용하신 점, 좀더 상세히 테스트 코드 작성해보려고 노력하신 점 너무 잘하셨어요!ㅎㅎ다음 PR 또 기다리고 있을게요!🚀

2022-09-16 12:27 UTC, daadaadaah commented on src/HomePage.test.jsx
> +test('HomePage', async () => {
async가 왜 필요한건가용?ㅎㅎ

2022-09-16 12:27 UTC, daadaadaah commented on src/actions.js
> +export function setRestaurantDetailData(restaurantDetail) {
`Data`를 빼도 의도를 전달하는데 문제가 없을 것 같아요!ㅎㅎ

2022-09-16 12:27 UTC, daadaadaah commented on src/reducer.test.js
> +      expect(state.selectedRegion).toEqual(REGIONS.find(equal('id', targetId)));
find를 사용하는 것보다 데이터 자체를 넣어주는건 어떠신가요?

2022-09-16 12:55 UTC, ChoJinmok commented on src/HomePage.test.jsx
> +test('HomePage', async () => {
🫢 이게 왜 들어가있을까요?? 😭

2022-09-16 12:58 UTC, ChoJinmok commented on src/reducer.test.js
> +      expect(state.selectedRegion).toEqual(REGIONS.find(equal('id', targetId)));
```suggestion
      expect(state.selectedRegion).toEqual(REGIONS[0]);
```

이런식으로 직접 넣어주는게 좋을까요??🤔

2022-09-16 18:42 UTC, ChoJinmok reviewed
상세페이지에서 새로고침할 때 main.js를 이상한 경로에서 불러와서 index.html에서 기본 base를 설정해줬는데 이렇게 해결하는게 맞을까요?

2022-09-17 15:45 UTC, daadaadaah requested changes
진목님 보면, github 기능들(예: 리뷰 요청, suggested change)을 잘 활용하시는 것 같아서 너무 좋습니당!ㅎㅎ다음 PR 기다리고 있을게요!ㅎㅎ

> 상세페이지에서 새로고침할 때 main.js를 이상한 경로에서 불러와서 index.html에서 기본 base를 설정해줬는데 이렇게 해결하는게 맞을까요?

처음에 `/main.js`로 하셔도 되고, base 로 문제를 해결하셔도 됩니당! 잘하셨어요👏

2022-09-17 15:45 UTC, daadaadaah commented on src/RestaurantDetail.test.jsx
> +  it('rendes name, adress, menu items of restaurant', () => {
테스트도 유지보수성을 고려해서 작성하는게 좋아요! 이렇게 하나하나 기재할 경우, 만약에 restaurant의 다른 정보(예 : 별점)가 추가되는 요구사항이 들어온다면, 이 it문은 대응하지 못할 것 같아요!ㅎㅎ어떻게 하면 레스토랑의 다른 정보가 추가되는 요구사항이 발생하더라도 it문장을 수정하지 않게할 수 있을까요?

2022-09-17 15:45 UTC, daadaadaah commented on src/RestaurantDetailContainer.test.jsx
> +  it('renders restaurant detail', () => {
여기서 detail이 레스토랑의 정보들을 말하는 걸까용?

2022-09-17 15:45 UTC, daadaadaah commented on src/RestaurantDetail.test.jsx
> +    expect(getByText(/메뉴/)).not.toBeNull();
1. 통일감 있게 `toHaveTextContent`를 사용해보는 건 어떠신가요? 이 코드를 처음 봤다고 했을 때 왜 다르게 표현했지라는 생각이 들 것 같아요!ㅎㅎ
2. 추가로, 화면에 보이는지 여부를 테스트할 때
- `expect(container).toHaveTextContent('주소:');`로 할지(방식1), `expect(getByText(/메뉴/)).not.toBeNull();`로 할지(방식2) 자신만의 규칙을 정해보시는건 어떠신가요? 어디서는 방식1로 하고, 어디서는 방식2로 해서 어떤 의도인지 의문이 들 것 같아요!

2022-09-17 15:45 UTC, daadaadaah commented on src/RestaurantDetailContainer.jsx
> +  );
restaurantDetail이 없을 때, loading이 보이는 걸로 바꿔보시는건 어떠신가요? 보통 예외처리를 위에 써주는 편이라서요!

2022-09-17 15:45 UTC, daadaadaah commented on src/RestaurantDetailContainer.test.jsx
> +  context('before loading restaurant detail', () => {
context는 with/when으로 통일감 있게 표현하는게 좋아요!
지금 상황에서 `without/with restaurantDetail`로 표현해보시는건 어떠신가요?

2022-09-17 15:45 UTC, daadaadaah commented on src/reducer.test.js
> +      expect(selectedRegion).toEqual(REGIONS[0]);
작성해주시대로 하셔도 되고, 아래처럼 작성하셔도 될 것 같아요!
```js
const SEOUL = REGIONS[0];

expect(selectedRegion).toEqual(SEOUL);
```

2022-09-18 03:58 UTC, ChoJinmok commented on src/RestaurantDetail.test.jsx
> +  it('rendes name, adress, menu items of restaurant', () => {
일일이 여러가지를 기재하는 것 보다 여러가지를 포괄할 수 있게 it문장을 수정하는게 좋을 거 같네요!~ 좋은 리뷰 감사합니당~ㅎㅎ

2022-09-18 05:26 UTC, ChoJinmok commented on src/RestaurantDetail.test.jsx
> +    expect(getByText(/메뉴/)).not.toBeNull();
딱 똑같은 고민을 하고 어떻게 할지 갈팡지팡하고 있었는데 코드로도 드러나나 보네요🥲 저만의 규칙을 한번 정해봐야겠습니다!!

2022-09-18 06:28 UTC, ChoJinmok commented on src/RestaurantDetailContainer.test.jsx
> +  it('renders restaurant detail', () => {
네!~ 다희님 리뷰보고 details로 고쳐봤습니다!

2022-09-18 06:30 UTC, ChoJinmok commented on src/RestaurantDetailContainer.test.jsx
> +  context('before loading restaurant detail', () => {
context에 통일감 주는 게 훨씬 눈에 잘들어오네요! 좋은 리뷰 감사합니다!

2022-09-18 06:34 UTC, ChoJinmok commented on src/RestaurantDetailContainer.jsx
> +  );
보통 예외처리는 위에 작성해주는군요!? 좋은리뷰 감사합니다!ㅎㅎ

2022-09-18 06:38 UTC, ChoJinmok commented on src/reducer.test.js
> +      expect(selectedRegion).toEqual(REGIONS[0]);
그냥 작성하는 것보다 다희님 처럼 변수명으로 명명해놓는게 더 가독성이 좋은 거 같네요! 좋은 리뷰 감사합니다! ㅎㅎ

2022-09-18 11:48 UTC, daadaadaah approved these changes
이번주도 수고 많으셨어요!👏 회고를 통해 이번주에 무엇을 배웠지 한번 되돌아보는 시간을 가져봅시당😊

2022-09-18 13:04 UTC, ChoJinmok reviewed
Restuarant Detail Container 테스트에서 '데이터를 load하기전', '데이터를 load할 때'로 context를 작성해주고 싶은데 context에서는 when/with 외에 before/after을 사용하는 경우는 많이 없나요??

2022-09-19 11:35 UTC, merged