상세 페이지 구현 (react-router-dom 활용)
CodeSoom/week6-assignment-1 pull request #102
Opened 2022-09-15 12:07 UTC by 0-Chan

안녕하세요~~ 명절 잘 보내셨나요?

기본 강의 내용을 작성한 상태이구요,
 useParams() 로 상세페이지에 id를 부여 하던 중 PR 요청 드립니다!

현재 커밋 부분을 작성하고 나서 **클릭 가능한 식당 이름**이 나올 것을 기대했는데... 
안되는 것으로 보아 뭔가 놓친 부분이 있는 것 같습니다 ㅜ

일단 지금 코드와 머릿 속이 뒤죽박죽이라 공식 문서를 더 봐보겠습니다.

2022-09-15 13:44 UTC, daadaadaah reviewed
영찬님도 명절 잘 보내셨나요? 푹 쉬었으니 다시 달려봅시당!🏃‍♂️ 이번주도 같이 힘내봐요👊

> 현재 커밋 부분을 작성하고 나서 클릭 가능한 식당 이름이 나올 것을 기대했는데...
> 안되는 것으로 보아 뭔가 놓친 부분이 있는 것 같습니다 ㅜ
> 일단 지금 코드와 머릿 속이 뒤죽박죽이라 공식 문서를 더 봐보겠습니다.

정리하자면, 지역이랑 카테고리를 클릭했을 때, 식당 목록이 안나오는 상황이신가요? 공식문서 보기보다 어디서 문제가 발생하고, 왜 발생하는지, 에러메시지가 있다면 어떤 에러메시지 등을 먼저 파악해보는 걸 추천드려요! 도움이 필요하면 말씀해주세요!😎

2022-09-15 13:44 UTC, daadaadaah commented on src/pages/NotFoundPage.test.jsx
> +});
expect문이 빠져있어요!ㅎㅎ(다른 페이지 테스트들도 마찬가지예요!)

2022-09-15 13:44 UTC, daadaadaah commented on src/pages/RestaurantsPage.jsx
> +    dispatch(loadInitialData());
`data`보다 좀더 의도를 드러낼 수 있는 용어는 없을까요?ㅎㅎ

2022-09-16 09:27 UTC, 0-Chan commented
> > 일단 지금 코드와 머릿 속이 뒤죽박죽이라 공식 문서를 더 봐보겠습니다.
> 
> 정리하자면, 지역이랑 카테고리를 클릭했을 때, 식당 목록이 안나오는 상황이신가요? 공식문서 보기보다 어디서 문제가 발생하고, 왜 발생하는지, 에러메시지가 있다면 어떤 에러메시지 등을 먼저 파악해보는 걸 추천드려요! 도움이 필요하면 말씀해주세요!sunglasses

말씀 주신대로 딴 길로 새지 않고 곧장 error 메시지를 확인 해봤습니다.

1. net::ERR_ABORTED 404 문제
검색을 통해 경로 문제임을 파악하고 절대 경로를 넣어줌으로써 해결 했습니다.

2. Loading... 처리를 안했던 문제
자꾸만 undefined를 처리할 수 없다는 error가 절 괴롭혔었는데요.
생각해보니 이런 서버 api를 활용하는 과정은 모두 비동기 라는 것을 깨달았습니다.
그래서 값이 없을 경우에 예외 처리하여 해결 했습니다.

 - - -
 - 질문
 Loading 문제를 해결하다 훅에 대한 궁금증이 생겼는데요.
 이전 과제에서 초기 데이터를 불러오기 위해 `useEffect()`를 사용한다고 봤었는데
 여기서 side effect 라는게  컴포넌트 내부에서 변경될 수 없는 값들을 뜻하는 걸까요?..
 (정리하면 언제 `useEffect()`를 쓸지 `useState()`를 쓸지가 궁금합니다!)

2022-09-16 09:39 UTC, 0-Chan commented on src/pages/NotFoundPage.test.jsx
> +});
앗.. 정신이 없었네요ㅜ Page 관련 테스트에 expect 추가 했습니다!

2022-09-16 09:59 UTC, 0-Chan commented on src/pages/RestaurantsPage.jsx
> +    dispatch(loadInitialData());
확실히 `data`는 가능하면 피해야할 작명 인 것 같습니다.. (비슷하게는 num, str, a, b ...)

암튼 용어를 `loadInitialList()` 로 바꾸어 보았습니다!

2022-09-16 13:38 UTC, daadaadaah requested changes
> Loading 문제를 해결하다 훅에 대한 궁금증이 생겼는데요.
이전 과제에서 초기 데이터를 불러오기 위해 useEffect()를 사용한다고 봤었는데
여기서 side effect 라는게 컴포넌트 내부에서 변경될 수 없는 값들을 뜻하는 걸까요?..
(정리하면 언제 useEffect()를 쓸지 useState()를 쓸지가 궁금합니다!)

1. Side Effect란 함수 실행시 함수 외부의 상태를 변경하는 연산을 말해요! 예를 들어, API 호출, 이벤트 처리 등록하고 해제 하는 등이 있어요! 
2. useState는 컴포넌트에 상태를 추가할 때 쓰는 hook이고, useEffect는 어떻게 보면 그렇게 추가된 상태를 Side Effect를 활용해서 변경하고 싶을 때 사용할 수 있는 hook이라고 보시면 될 거예요!

2022-09-16 13:38 UTC, daadaadaah commented on src/pages/RestaurantInfoPage.test.jsx
> +  it('renders RestaurantInfoPage', () => {
describe-it을 한문장으로 연결했을 때, 문장이 어색하지 않아야해요!(다른 페이지 테스트 코드도 마찬가지예요!)
지금 작성해주신대로 문장을 만들면, `RenderantInfoPage가 RestaurantInfoPage 를 renders 한다` 라고 문장이 만들어져서 어색합니당! 어떻게 고치는게 좋을까요?ㅎㅎ

2022-09-17 11:49 UTC, 0-Chan commented on src/pages/RestaurantInfoPage.test.jsx
> +  it('renders RestaurantInfoPage', () => {
친절한 설명 감사합니다! 내용은 수정 했습니다.

2022-09-17 15:48 UTC, daadaadaah commented on src/pages/RestaurantInfoPage.test.jsx
> +  it('renders RestaurantInfoPage', () => {
다른 페이지 테스트 코드도 같이 수정해주세요!ㅎㅎ

2022-09-18 12:12 UTC, 0-Chan commented on src/pages/RestaurantInfoPage.test.jsx
> +  it('renders RestaurantInfoPage', () => {
앗 넵넵.. 너무 지정 해주신 곳만 봤었네요.. :sweat_smile:

2022-09-18 12:26 UTC, daadaadaah approved these changes
이번주도 수고 많으셨습니다!👏 회고를 통해 이번주에 무엇을 배웠는지 한번 되돌아보는 시간을 가져봅시당👊
it문 피드백은 다음과제 하실 때 한번 생각해보시고 진행해주세요😊

2022-09-18 12:26 UTC, daadaadaah commented on src/pages/AboutPage.test.jsx
> +  it('shows AboutPage description', () => {
`AboutPage가 AboutPage description를 show한다` 라는 문장이랑 `AboutPage가 AboutPage description를 render한다` 이랑 문장이랑 비교해봤을 때, 어느 것이 더 자연스러운지 한번 생각해봅시당!ㅎㅎ

2022-09-19 11:35 UTC, merged