6주차 - 레스토랑 상세 페이지 구현하기
CodeSoom/week6-assignment-1 pull request #104
Opened 2022-11-14 18:44 UTC by yxxnhx

# 목표
레스토랑 상세 페이지 구현하기

### 진행사항
현재 Home, About, Restaurants 페이지를 각각 라우팅해놓은 상태입니다.
레스토랑의 상세 페이지를 보여줄 수 있도록 어떻게 할지 고민하고 있습니다.
차근차근히 해보도록 하겠습니다👊

2022-11-15 12:02 UTC, daadaadaah requested changes
항상 PR 일찍 남겨주시는 것 같은데, 좋은 프로세스인 것 같아요!👍
계속 진행해주세요🚀

2022-11-17 10:53 UTC, yxxnhx commented
# 진행사항
현재 RestaurantsInfoPage를 생성하여 데이터를 관리하고 각각의 데이터를 RestaurantsInfoContainer에서 보여줄 수 있도록 하였습니다

actions
```jsx
export function setRestaurantInfo(restaurantInfo) {
  return {
    type: 'setRestaurantInfo',
    payload: { restaurantInfo },
  };
}

/* 생략 */

export function loadRestaurantsInfo(restaurantId) {
  return async (dispatch) => {
    const restaurantInfo = await fetchRestaurantInfo(restaurantId);

    dispatch(setRestaurantInfo(restaurantInfo));
  };
}
```
reducer
```jsx
  setRestaurantInfo(state, { payload: { restaurantInfo } }) {
    return {
      ...state,
      restaurantInfo,
    };
  },
```

RestaurantsInfoPage
```jsx
  const { id } = useParams();

  useEffect(() => {
    dispatch(loadRestaurantsInfo(id));
  }, []);

  const restaurantInfo = useSelector((state) => ({
    restaurantInfo: state.restaurantInfo,
  }));
```

<img width="860" alt="image" src="https://user-images.githubusercontent.com/50559373/202427614-fb49a201-6530-412a-a44e-6165900efd34.png">

그런데 지금 restaurantInfo를 처음에는 null을 받다가 뒤늦게서야 데이터를 받아와 지금처럼 콘솔에 세 개가 찍힙니다ㅠㅠ
왜 그런 것일까요?

2022-11-18 10:16 UTC, daadaadaah requested changes
1. 테스트 코드를 먼저 작성해보는 걸 의도적으로 훈련해보시는 걸 추천드립니다! 지금 질문 주신 내용이 테스트 코드를 먼저 작성했으면 해결될 수도 있는 이슈 같거든용!😊

## 질문에 대한 답변
RestaurantsInfoPage에서 `restaurantInfo`를 디스트러처링해서 뽑아오시고, 
```js
const { restaurantInfo } = useSelector((state) => ({
    restaurantInfo: state.restaurantInfo,
  }));
```
RestaurantsInfoContainer에서 restaurantInfo 가 없을 때에 대한 로직을 추가해주시면 될거예요!
```
  if (!restaurantInfo) {
    // ~~~
  }
```

2022-11-18 15:10 UTC, yxxnhx commented
# 진행사항
구조분해할당을 하여 restaurantInfo를 가져오고 restaurantInfo가 없을 경우의 조건을 추가하여 목록 조회까지 완료시켰습니다!
테스트 코드를 먼저 작성하면 방지할 수 있다니.. 틀을 간단히 잡고 테스트 코드를 짜야지 하다가 보니 이렇게 되었었네요ㅠㅠ
꼭 다음 과제 때는 의도적으로라도 테스트 코드를 먼저 작성하면서 잡을 수 있는 오류들은 잡아나가보겠습니다!

### 질문사항
![image](https://user-images.githubusercontent.com/50559373/202736772-3dcb2666-aec1-45c0-b1fd-79752b05bb75.png)

지금 현재 테스트 커버리지는 모두 통과를 하였고 레스토랑과 레스토랑 정보도 정상적으로 잘 출력이 되는데 E2E 테스트가 위와 같이 restaurantDetail이 나오지 않는다고 에러가 뜹니다ㅠㅠ
왜 그런 것일까요?
어떤 부분을 수정해야 이 부분이 해결이 될까요?

2022-11-19 08:31 UTC, daadaadaah requested changes
1. presentational component 를 만들지 않고 구현하신 이유가 궁금합니다!
2. 질문 주신거 해결되셨나요?

2022-11-19 08:31 UTC, daadaadaah commented on src/reducer.test.js
> +      };
`restaurantInfo` 객체로 관리하는데, 이부분도 수정해줘야 하지 않을까여?ㅎㅎ

2022-11-19 14:40 UTC, yxxnhx commented on src/reducer.test.js
> +      };
앗 그렇군요! null로 수정하겠습니다~

2022-11-19 15:36 UTC, yxxnhx commented
# 진행사항
restaurantInfo 초기값 null로 모두 통일하여 수정하였습니다.
그리고 presentational component를 만들 생각을 하지 못하였었어요..🥹
일단 구현하는데 급급해서 컨테이너 안에 그냥 다 넣어서 진행했었습니다
그래서 RestaurantsInfoPage에서는 id만,  RestaurantsInfoContainer에서는 리덕스를 이용하여 액션을 꺼내오기만,  RestaurantDetail에서는 레스토랑 정보 출력만,  RestaurantMenuItem에서는 메뉴 아이템 출력만 할 수 있도록 관심사를 분리하여 컴포넌트 분리하는 것으로 수정하였습니다.

그리고 어제 질문하였던 부분은 구글링을 하여서 상대경로 때문에 `/`가 없을 경우에는 에러가 나서 일어났던 깨짐으로 이해하였는데 혹시 맞을까요? 사실 완벽하게 이해는 하지 못하였습니다 
제가 참고할 수 있는 사이트나 검색어를 알려주신다면 정말 감사하겠습니다!

2022-11-20 06:42 UTC, daadaadaah requested changes
## 질문에 대한 답변
- 네, `절대경로`와 `상대경로`의 차이에 대해 공부해보시면되요!
- 추가로, `main.js`에 대한 문제는 `index.html`의 `head`에
`<base href="/">`를 추가해서 해결할 수도 있습니다.
- 참고 : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

2022-11-20 06:42 UTC, daadaadaah commented on src/RestaurantsInfoPage.jsx
> +  const { id } = useParams();
`RestaurantsInfoPage`에서 id가 필요하지 않으므로, 필요한 곳에서만 useParams로 뽑아 사용할 수 있을거예요!

2022-11-20 07:39 UTC, yxxnhx commented
# 진행사항
절대경로 상대 경로의 문제였다니! 감사합니다
덕분에 이해가 되었습니다. 처음에는 뭔가 설정이 잘못된 줄 알고 webpack 문서도 찾아보고 그랬었어요😅
그리고 `RestaurantsInfoContaienr에서 직접 사용할 수 있도록 `RestaurantsInfoPage`에서 빼왔습니다.

```jsx
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/about" element={<AboutPage />} />
          <Route path="/restaurants" element={<RestaurantsPage />} />
          <Route path="/restaurants/:id" element={<RestaurantsInfoContaienr />} />
          <Route path="*" element={<NotFoundPage />} />
        </Routes>
```
그렇게 되면 페이지에서는 그저 컨테이너를 넘기는 일만 하게 되는데 페이지를 삭제하고 컨테이너에서 바로 보일 수 있도록 App의 라우트 설정을 변경해도 괜찮을까요?
그게 아니라면 페이지를 그대로 살려두는 것이 맞나요? 뭔가 라우트를 페이지로 하는 것이 맞는거 같은데 그렇다고 아무 일도 하지 않고 컨테이너로만 넘기는 일을 하는 컴포넌트를 살려두는 것이 맞는지 잘 모르겠습니다ㅠㅠ

2022-11-20 07:39 UTC, yxxnhx commented on src/RestaurantsInfoPage.jsx
> +  const { id } = useParams();
아하 넵! 수정하겠습니다~!

2022-11-20 14:13 UTC, daadaadaah commented
> # 진행사항
> 절대경로 상대 경로의 문제였다니! 감사합니다 덕분에 이해가 되었습니다. 처음에는 뭔가 설정이 잘못된 줄 알고 webpack 문서도 찾아보고 그랬었어요😅 그리고 `RestaurantsInfoContaienr`에서 직접 사용할 수 있도록 `RestaurantsInfoPage`에서 빼왔습니다.
> 
> ```js
>   <Routes>
>     <Route path="/" element={<HomePage />} />
>     <Route path="/about" element={<AboutPage />} />
>     <Route path="/restaurants" element={<RestaurantsPage />} />
>     <Route path="/restaurants/:id" element={<RestaurantsInfoContaienr />} />
>     <Route path="*" element={<NotFoundPage />} />
>   </Routes>
> ```
> 
> 그렇게 되면 페이지에서는 그저 컨테이너를 넘기는 일만 하게 되는데 페이지를 삭제하고 컨테이너에서 바로 보일 수 있도록 위처럼 App의 라우트 설정을 변경해도 괜찮을까요? 그게 아니라면 페이지를 그대로 살려두는 것이 맞나요? 뭔가 라우트를 페이지로 하는 것이 맞는거 같은데 그렇다고 아무 일도 하지 않고 컨테이너로만 넘기는 일을 하는 컴포넌트를 살려두는 것이 맞는지 잘 모르겠습니다ㅠㅠ

- 추상화 수준을 일치시키기 위해 Page 컴포넌트로 라우트를 해주는 게 더 좋을 것 같아요!
- 저라면, page 컴포넌트에서 load 해옴으로써 Page 컴포넌트의 역할을 부여해줄 것 같아요! 다른 page 컴포넌트에서도 초기 데이터 불러와주니까!

2022-11-20 14:13 UTC, daadaadaah approved these changes

2022-11-21 08:04 UTC, merged