6주차 과제 - 레스토랑 상세 페이지 구현하기
CodeSoom/week6-assignment-1 pull request #105
Opened 2022-11-15 12:04 UTC by sejineeee

## 내용
react-router-dom을 사용하기 위해 설치하였습니다.
아직 테스트 파일이 작성되지 않은 상태여서 route에 연결한 컴포넌트들은 푸시하지 않았습니다!
마저 작업하는대로 바로바로 올리고 질문이 있을 경우 같이 올려놓도록 하겠습니다!
이번주도 잘 부탁드립니다!!

2022-11-15 13:22 UTC, daadaadaah requested changes
좋습니당!! 빠른 PR 보내기 잘하셨어요👏👏👏
다음 PR 기다리고 있을게여ㅎㅎ

2022-11-16 12:13 UTC, sejineeee commented
## 내용
안녕하세요!!
일단 디테일 페이지를 라우트 연결하는 것까지는 완료했습니다.
그러고 디테일 페이지 데이터 api 호출 함수까지 구현하였습니다!
하지만 생각처럼 되지 않아서 ...ㅎㅎㅎ

처음에 state is not a function 이라는 에러가 뜨길래, state를 콘솔에 확인해봐야겠다 싶어서
useSelector 안에서 확인해봤는데... 😭 state는 확인이 되긴 하지만
현재 restaurantDetail에는 초기값([])만 들어있고, 데이터가 들어오질 않습니다ㅠㅠ
일단 PR을 남긴 후, 해결하기 위해 더 노력해보도록 하겠습니다...
<img width="742" alt="스크린샷 2022-11-16 오후 9 08 01" src="https://user-images.githubusercontent.com/86041335/202177415-789e3cda-09fc-472f-ae18-773ab7f43220.png">

2022-11-17 03:30 UTC, daadaadaah requested changes
계속 진행해주세요! 남겨주신 질문은 해결 되신건가여?ㅎㅎ

2022-11-17 03:30 UTC, daadaadaah commented on src/RestaurantDetail.jsx
> +  const id = useParams();
디스트러처링을 활용해보시는건 어떠신가여? 14번째줄이 그럼 깔끔해질 거 같은데
```js
  const { id } = useParams();
```

2022-11-17 03:30 UTC, daadaadaah commented on src/RestaurantDetail.jsx
> +  if (restaurantDetail === []) {
length를 활용해봅시당!

2022-11-17 03:30 UTC, daadaadaah commented on src/RestaurantDetail.test.jsx
> +import RESTAURANTDETAIL from '../fixtures/restaurantDetail';
두 단어가 합쳐진 경우, `RESTAURANT_DETAIL` 이렇게 구분자로 구별해주면 좋아요!

2022-11-17 07:55 UTC, sejineeee commented on src/RestaurantDetail.jsx
> +          restaurantDetail.menuItems?.map((item) => (<li key={item.id}>{item.name}</li>))
이 부분에 undefined로 인해서 옵셔널 체이닝을 이용해서 일단 문제를 해결하였습니다!
옵셔널 체이닝밖에 떠오르지 않아서 사용하였는데, 최선의 방법일지 잘 모르겠습니다ㅠㅠ

2022-11-17 10:54 UTC, sejineeee commented
## 내용
리뷰를 토대로 수정하였습니다!!!
reducer에 action에 테스트 잘못 들어온 부분은 제가 액션을 잘못 줬기 때문에 생긴 문제로 수정하였습니다!
아직 RestaurantDetail 부분에는 왜 아무것도 렌더링되지 않는 것일까요...?
그리고 제가 질문을 같이 올렸었는데... 제가 아직 깃허브 사용이 익숙하지 않다 보니, 질문이 Pending 상태였더라고요! ㅎㅎㅎ
그래서 늦게나마, 다시 질문 올렸습니다(옵셔널 체이닝 질문입니다!)
감사합니다!!

2022-11-18 10:29 UTC, daadaadaah requested changes
잘하셨습니다!ㅎㅎ테스트 코드 작성하시는 것도 이제 제법 익숙해주신 것 같아 좋네영!👍

## 질문에 대한 답변
1. 현재 `restaurantDetail`를 배열로 관리하시는데, 컴포넌트에서는 객체로 취급하고 있어요!ㅎㅎ또한, fixture 데이터에서 값이랑 테스트코드에서 확인하고자 하는 값이랑 일치하는지 확인해보셔야 할 것 같아요!ㅎㅎ

2022-11-18 10:55 UTC, sejineeee commented
## 내용
안녕하세요! 컴포넌트에서는 객체로 취급하고, fixture 데이터에서는 배열로 만들어서 구조가 달라서 그랬던 거였다니...!
어제 하루종일 봤는데 이런 간단한 문제였다니...충격이에요! ㅎㅎㅎㅎ
restaurantDetail에 배열에 객체가 담긴 구조라고 저는 생각했는데, 콘솔로 확인해보니 객체만 담긴 것을 확인했습니다!

그러면 reducer 파일에 초기 state 설정 값에 제가 빈배열을 할당했는데, 이렇게 `null`을 할당하는 편이 더 나을까요?
```javascript
// reducer.js

const initialState = {
  restaurantDetail : null
}
```
그리고 제가 `RestaurantDetail.jsx` 파일에서

```javascript
 if (restaurantDetail.length === 0) {
    return null;
  }
```
이렇게 코드를 구현했었는데, 이 부분도 이렇게 작성해도 괜찮은 것일까요..?
뭔가 배열 안에 객체가 담긴 구조가 아닌데 (처음에는 배열 안에 객체가 담긴 구조라고 생각해서 이렇게 처리를 했었습니다!)
이렇게 작성해도 괜찮은지 궁금합니다!

만약, 초기값을 null로 할당한다면 이렇게 바꿔야 되는 것일까요?
```javascript
if (restaurantDetail === null) {
   return null;
}
```

2022-11-19 08:47 UTC, daadaadaah requested changes
> e2e 테스트에서 이렇게 나오는데 다른 조건에 대한 테스트가 더 필요한 걸까요? useParams에 대한 조건도 테스트를 해줘야 되는 건가요?
- `http://localhost:8080/restaurants/1` 링크로 입력했을 떄에도 화면이 보여야 하는데, 안보여서 실패하는 것 같아요! 하루 시간 더 있으니, 혼자 스스로 해결해보시는 걸 추천드려요! 다른 분들도 동일한 문제를 겪었는데, 어떻게 해결하셨는지 살펴봐도 좋구요!ㅎㅎ

2022-11-19 08:47 UTC, daadaadaah commented on src/RestaurantDetail.jsx
> +  }
이제 배열이 아니니, 질문주신대로 아래처럼 표현하거나
```js
if (restaurantDetail === null) {
   return null;
}
```
- 아래처럼 해주셔도 괜찮을 것 같아요! 추가로, 없을 때, null 보다는 사용자에게 좀더 친화적인 UI를 넣어주시는 것도 좋을 것 같아요!
```js
if (!restaurantDetail) {
   return <p>loaing...</p>;
}
```

2022-11-19 11:56 UTC, sejineeee commented
## 내용
안녕하세요!! 에러 메시지를 구글링 해보니, `index.html`의 스크립트 경로를 `main.js`에서 `/main.js`로 바꾸면 되는 것을 찾을 수 있었습니다!!! (저는 처음에 url에 저주가 걸린 줄 알았어요ㅎㅎㅎ 어떤 것을 해도 /1만 붙으면 에러가 뜨길래 푸하하)
일단 구글링을 통해서 해결은 하였으나, 왜 경로 설정으로 인해서 문제가 해결이 된 건지 이해가 잘 되지 않습니다!
혹시 이러한 이유에 대해서 알고 싶다면 어떤 키워드를 검색하면 제가 이해하기에 도움이 될까요...?
알려주신다면 이러한 이유에 대해서 공부해보도록 하겠습니다!! 🤓

2022-11-20 06:44 UTC, daadaadaah approved these changes
sejineeee이라면 혼자 해결하실 수 있을 것 같았어요!👍 잘하셨어요~

- `절대경로`와 `상대경로`의 차이에 대해 공부해보시면 될거예요!
- 추가로, `main.js`에 대한 문제는 `index.html`의 `head`에
`<base href="/">`를 추가해서 해결할 수도 있습니다.
- 참고 : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

2022-11-21 08:04 UTC, merged