레스토랑 상세 페이지 구현하기
CodeSoom/week6-assignment-1 pull request #13
Opened 2020-07-09 08:18 UTC by iamhwang

습득이 느려서 ,, 이제야 조금 알 거 같습니다. 

작업을 하고 한 번에 commit add 했는데 ,, 작업 순서와 같은 히스토리가 안남네요 

다음부터는 작업 중간중간 commit을 올리도록 하겠습니다. 

오늘 한 부분 먼저 올리겠습니다. 부족한 부분 피드백 요청드립니다. 

감사합니다.

2020-07-09 12:31 UTC, hannut91 requested changes
잘 진행하고 계세요 ㅎㅎ 계속 진행해주세요

2020-07-09 12:31 UTC, hannut91 commented on src/App.jsx
> +        <HeaderPage />
정확히는 페이지는 아니니까 그냥 `Header`는 어떨까요?

2020-07-09 12:31 UTC, hannut91 commented on src/App.test.jsx
> +      ));
반복되어 사용되는 것은 함수로 추출하는게 좋을 것 같아요

```js
function renderApp(path) {
  return render(
    <MemoryRouter initialEntries={path}>
      <App />
    </MemoryRouter>
  );
}
```

2020-07-09 12:31 UTC, hannut91 commented on src/HomePage.test.jsx
> +});
간단하게 render되는지만 테스트를 작성해주셨네요. 어떤 링크들이 있는지 테스트를 작성해서 `HomePage`는 이런 링크들을 가지고 있다고 의도를 드러내는건 어떨까요?

2020-07-09 12:31 UTC, hannut91 commented on src/RestaurantsPage.jsx
> +export default function App() {
이름이 App이네요. RestaurantPage로 변경하는게 좋을 것 같아요

2020-07-10 08:45 UTC, iamhwang commented on src/App.jsx
> +        <HeaderPage />
Header에 이것저것 넣기 시작한다면, 그 때는 HeaderPage 이름이 어울릴까요?

2020-07-10 08:45 UTC, iamhwang commented on src/RestaurantsPage.jsx
> +export default function App() {
복붙하느라 놓쳤던 부분이네요. 섬세하게 봐주셔서 정말 감사합니다!

2020-07-10 09:44 UTC, iamhwang commented on src/App.test.jsx
> +      ));
추출했습니다! function renderComponent(address) 객체로 안받고 하나의 파라미터로 받았는데
어떤 상황에서 객체로 받고, 어떤 상황에서는 그냥 파라미터로 받나요?

2020-07-10 09:44 UTC, iamhwang commented on src/HomePage.test.jsx
> +});
수정했습니다. 이 정도면 충분히 의도를 드러냈을까요?

2020-07-10 11:40 UTC, hannut91 commented on src/App.test.jsx
> +      ));
제가 그냥 받는걸로 예제를 드렸는데요. 객체로 받는 이유는 named parameter로 사용할 있는 거에요. 받을 때 

`function renderApp({path})`로 받게 되면 보낼 때도 `renderApp({path: '/path'})`이렇게 보내기 때문에 어떤 파라미터에 대해서 이름을 지어서 보낼 수 있게 돼요. 다른 언어같은 경우에는 예를들어 코틀린 같은 경우에는 `renderApp(path = '/path')` 이렇게 할 수 있는데 자바스크립트에서는 그렇게 지원이 안되고, 또 타입이 없다보니까 객체로 그냥 넘기는게 아주 많이 사용됩니다.

객체로 보낼 경우 그냥 넘기는 것보다 좋은 점이 하나 더 있는데 Optional하게 보낼 수 있다는 거에요. 만약에 a, b, c가 필요하다면 
`run(a, b, c)`이렇게 보내야 하는데 b를 안넘긴다면 `run(a, null, c)`이렇게 써야겠죠. 근데 객체로 보내게 되면 그냥 b를 안보내면 돼요. `run({a: 'some', c: 'value'})` 이렇게요.

또 객체로 만들어야 할 때는 각 파라미터들이 데이터들과 서로 연관이 있을 경우에요. 예를들어 `run(name, address)`를 `run(restaurant)`으로 바꾸는 것 처럼요.

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.8-introduce-parameter-object

2020-07-10 11:42 UTC, hannut91 commented on src/App.jsx
> +        <HeaderPage />
지금 Page는 어떤 페이지를 나타내는데 사용되고 있어요. `/`경로에는 HomePage가 사용되고 있고 /restaurants에는 RestauarntPage가 사용되고 있어요. 그래서 HeaderPage를 보면 어떤 페이지를 나타내는 것 처럼 보여요.

2020-07-10 11:47 UTC, hannut91 requested changes
이제 레스트랑 상세페이지도 구현해주세요!

2020-07-10 11:47 UTC, hannut91 commented on src/App.test.jsx
> +    });
여기도 `renderComponent`를 이용해서 테스트를 표현해줘도 좋을 것 같아요.

2020-07-10 11:48 UTC, hannut91 commented on src/HomePage.test.jsx
> +});
네 잘하셨습니다 ㅎㅎ

2020-07-11 02:30 UTC, hannut91 reviewed
아직 구현중인 것 같네요! 어려운 것 있으면 질문 남겨주세요

2020-07-11 02:30 UTC, hannut91 commented on src/reducer.test.js
> +  context('setRegions', () => {
`context`에는 `when, with, without`만 올 수 있어요. 여기는 describe가 맞을 것 같아요

See also
  - http://www.betterspecs.org/#contexts

2020-09-12 06:45 UTC, closed without merging