Restaurant list web site with router
CodeSoom/week6-assignment-1 pull request #14
Opened 2020-07-10 18:54 UTC by newoo

안녕하세요. 리뷰 신청합니다.

*현재 레스토랑 상세 페이지로 라우팅이 잘 안되는데, 무엇이 잘못되었는지 파악이 잘 안되는 상황입니다

2020-07-11 02:38 UTC, hannut91 requested changes

2020-07-11 02:38 UTC, hannut91 commented on src/HomePage.test.jsx
> +});
`HomePage`가 렌더링 되는지 테스트를 작성하신 것 같아요. HomePage에 링크들이 있다는 것을 테스트로 작성해서 의도를 더 드러내는 것은 어떨까요?

2020-07-11 02:38 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +});
Given에 따라 테스트가 달라질 때는 `beforeEach`로 표현해주면 더 명확하게 보여줄 수 있습니다. 그리고 wtih restaurant id가 아니라 with restaurat이 맞을 것 같아요

```js
describe('RestaurantsContainer', () => {
  const renderRestaurantContainer = () => render(
    <MemoryRouter>
      <RestaurantContainer />
    </MemoryRouter>
  );

  context('without restaurant', () => {
    beforeEach(() => {
      useSelector.mockImplementation((selector) => selector({}));
    });

    it('renders loading page', () => {
      const { container } = renderRestaurantContainer();

      expect(container).toHaveTextContent('Loading');
    });
  });

  context('with restaurant', () => {
    beforeEach(() => {
      useSelector.mockImplementation((selector) => selector({
        restaurant: {
          id: 1,
          categoryId: 1,
          name: '양천주가',
          address: '서울 강남구',
          menuItems: [
            { id: 16, restaurantId: 1, name: '탕수육' },
            { id: 17, restaurantId: 1, name: '팔보채' },
          ],
          information: '양천주가 in 서울 강남구',
        },
      }));
    });

    it('renders restaurant', () => {
      const { container } = renderRestaurantContainer();

      expect(container).toHaveTextContent('양천주가');
      expect(container).toHaveTextContent('서울 강남구');
    });
  });
});
```

2020-07-11 10:15 UTC, newoo commented
피드백 사항 반영했습니다.
리뷰 재요청합니다

2020-07-11 11:03 UTC, hannut91 approved these changes
고생하셨습니다! 더 자세한 내용은 아샬님의 과제풀이 영상을 통해 복습해주시면 좋을 것 같습니다! 자바스크립트가 메인 언어가 아니셔서 어려울 수 있는데 잘 따라오시네요 ㅎㅎ

2020-07-11 11:03 UTC, hannut91 commented on src/RestaurantContainer.jsx
> +  if (restaurant === null || restaurant === undefined) {
이럴경우 자바스크립트에서는 falsy를 이용해서 

```js
if (!restaurant) {
  return ...
}
```

이렇게 표현해줄 수 있습니다.

See also
  - https://developer.mozilla.org/en-US/docs/Glossary/Falsy

2020-07-11 11:03 UTC, hannut91 commented on src/services/__mocks__/api.js
> +  return undefined;
JavaScript에서 undefined는 2가지 의미를 가지고 있습니다. 정말 정의가 되어있지 않아서 자바스크립트 엔진에서 undefined값으로 돌려주는 경우, 이렇게 사용자가 undefined를 사용한 경우입니다. 그래서 개발자가 undefined를 사용하게 되면 자바스크립트 엔진에서 undefined값으로 해석한 것인지 개발자가 의도적으로 undefined값을 사용한 것인지 구분할 수 가 없습니다. 따라서 정말 아무 값도 없다는 것을 드러낼때는 null을 사용하시던지 아니면 빈 object를 반환하던지 더 명시적으로 해주시는게 좋습니다.

2020-07-11 11:03 UTC, hannut91 commented
과제를 통해 무엇을 배우셨나요? 더 배우고 싶은게 있으신가요?

2020-07-16 04:32 UTC, newoo commented
> 과제를 통해 무엇을 배우셨나요? 더 배우고 싶은게 있으신가요?

라우터를 활용한 페이지 이동, ~page를 통해 관심사의 분리 등을 배울 수 있었습니다.
헤더에 base href를 추가하여 path 설정하는 부분에 있어서는 이해가 부족한 부분이 있는 것 같아 추가 학습이 필요합니다

2020-07-16 04:33 UTC, merged