과제6-1: 레스토랑 상세페이지 구현하기
CodeSoom/week6-assignment-1 pull request #18
Opened 2020-10-26 10:36 UTC by bbhye1

앞부분 강의를 TDD로 연습해보고 싶어서 작성한거라 다시 처음 부터  react-router로 작성할 예정입니다. 
다시 새로 작성하고 풀리퀘스트를 올릴까 하다가 질문이 있어서 먼저 올립니다. 

 초중반에 Add TODO in App test.  ee7983b 커밋에 제가 url 경로를 변경해서 테스트하는 법을  모르겠어서 주석만 달아놓고 지나쳤는데 이 부분을 테스트 할 수 있는 방법이 있을까요??

2020-10-27 15:18 UTC, bbhye1 commented
과제를 잘못보고 있는 정보내에서 조회하는것으로 완성했다가 다시 상세페이지 url이 있는것을 확인하고 추가하면서 보수작업을 하고 있습니다. 생각지도한 보수작업이지만 원래 있던 코드에 영향이 가지 않게 추가하고 테스트가 모두 통과하면 이전 코드를 제거하는 방식으로 진행해 나가려고 합니다. :joy:

2020-10-28 00:08 UTC, hannut91 requested changes

2020-10-28 00:08 UTC, hannut91 commented on src/AboutPage.test.jsx
> +    <MemoryRouter>
About page에는 Memory Router를 안써도 될 것 같아요

2020-10-28 00:08 UTC, hannut91 commented on src/App.test.jsx
> +      </MemoryRouter>
여기도 위의 renderApp을 사용해서 테스트할 수 있을까요?

2020-10-28 00:08 UTC, hannut91 commented on src/App.test.jsx
> +      const path = '/';
테스트에 사용되는 Given을 context와 it사이에 쓰면 좋을 것 같아요

2020-10-28 00:08 UTC, hannut91 commented on src/NotFoundPage.test.jsx
> +    </MemoryRouter>
여기도 MemoryRouter는 없어도 될 것 같아요

2020-10-28 00:08 UTC, hannut91 commented on src/Restaurant.jsx
> +  ));
여기서는 괄호를 하나만 쓰는게 좋을 것 같아요

2020-10-28 00:08 UTC, hannut91 commented on src/RestaurantsPage.jsx
> +  });
useEffect에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 돼요

2020-10-28 10:40 UTC, bbhye1 commented
전에 작성했던 코드에서  부분을 새로운 페이지로 대체하는것을 완료했습니다. Restaurants는 Page-Container-Component 이 구조로  작성이 되어 처음 Restaurant를 작성할때도 그 구조를 따랐는데 새로 작성하다가 보니 Container 컴포넌트의 과정을 생략해도 되겠다고 생각하여 생략해서 두단계의 컴포넌트로 만들었습니다.  

다 완성하고 보니 RestaurantDetail이 url로 바로 접근하면 에러가 나길래 index.html의 script주소를 'main.js' 에서 '/main.js' 로 변경해주니 손쉽게 고칠수 있었지만 완성하고 웹팩을 좀 공부하고 활용해야겠다는 생각이 들어 이 코멘트 아래쪽으로는 html-webpack-plugin을 사용해서 변경해주었고 웹팩 연습하는 김에 css-loader, style-loader도 추가했습니다.

2020-10-28 15:49 UTC, hannut91 commented
`index.html`에서 webpack에서 번들링된 `main.js`를 상대경로로 기술되어 있을 때, 특정 url에서 `main.js`를 불러오게 되면 `/restaurants/main.js`처럼 리소스를 요청하게 됩니다. 그러면 파일이 존재하지 않아 에러가 발생합니다. 이 문제를 해결하기 위해서는 두 가지 방법을 이용해서 해결할 수 있습니다.

1. `<base>` 태그를 사용해서 상대경로를 지정하는 방법
html의 `<base>`태그는 상대경로를 지정할 수 있습니다. 우리는 `index.html` 에 상대경로를 다음과 같이 지정하여 항상 root에서 `main.js`를 가져오도록 설정할 수 있습니다.

```html
<base href="/">
```

2. 절대경로로 지정하는 방법

`main.js`를 절대 경로로 수정하는 방법이 있습니다. 그러면 내가 현재 어떤 위치에 있던 일정한 방법으로 리소스를 가져올 수 있습니다.

```html
<script src="/main.js"></script>
```

See also
  - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  - https://webpack.js.org/guides/public-path/

2020-10-28 16:02 UTC, hannut91 commented
자바스크립트는 css 파일이나 image 파일들을 import할 수 없습니다. 그래서 webpack은 css-loader나 file-loader등을 사용해서 자바스크립트가 해당 리소스를 불러올 수 있도록 해줘야 합니다. 하지만 테스트 코드에서는 webpack으로 빌드한게 아니기 때문에 올바르게 동작하지 않습니다. 따라서 실제 코드에서는 동작하지만 테스트 코드에서는 필요없는 리소스들은 mocking해야 합니다.

jest.config.js에 다음과 같이 코드를 추가해서 리소스 파일을 불러올 때 마다 내가 지정한 가짜 코드를 불러오도록 할 수 있습니다.

```js
module.exports = {
  moduleNameMapper: {
    '\\.(css|less)$': '<rootDir>/__mocks__/fileMock.js'
  },
};
```

`<rootDir>/__mocks__/fileMock.js`

```js
module.exports = {};
```

See also
  - https://jestjs.io/docs/en/configuration#modulenamemapper-objectstring-string--arraystring

2020-10-28 16:09 UTC, bbhye1 commented
> 자바스크립트는 css 파일이나 image 파일들을 import할 수 없습니다. 그래서 webpack은 `css-loader`나 `file-loader`등을 사용해서 자바스크립트가 해당 리소스를 불러올 수 있도록 해줘야 합니다. 하지만 테스트 코드에서는 webpack으로 빌드한게 아니기 때문에 올바르게 동작하지 않습니다. 따라서 실제 코드에서는 동작하지만 테스트 코드에서는 필요없는 리소스들은 mocking해야 합니다.
> 
> jest.config.js에 다음과 같이 코드를 추가해서 리소스 파일을 불러올 때 마다 내가 지정한 가짜 코드를 불러오도록 할 수 있습니다.
> 
> ```js
> module.exports = {
>   moduleNameMapper: {
>     '\\.css$': '<rootDir>/__mocks__/fileMock.js'
>   },
> };
> ```
> 
> `<rootDir>/__mocks__/fileMock.js`
> 
> ```js
> module.exports = {};
> ```
> 
> See also
> 
> * https://jestjs.io/docs/en/configuration#modulenamemapper-objectstring-string--arraystring

아...  이게 맞는 방법이군요! 이 페이지대로 적용을 해보다가 실패해서 이게 아닌가했거든요 ㅎㅎ;;  내일 다시 천천히 보면서 시도해봐야겠네요! 😂

2020-10-28 16:23 UTC, hannut91 requested changes

2020-10-28 16:23 UTC, hannut91 commented on src/App.test.jsx
> +  }
조건문이 들어가다보니 코드가 길어지고 복잡해진 것 같아요. `path`를 기본 값으로 `/`로 주는건 어떨까요?

2020-10-28 16:23 UTC, hannut91 commented on src/Loading.css
> +}
```suggestion
}
// Some new code
```

코드 마지막 줄에는 빈 줄이 하나가 추가되어야 합니다. 그렇지 않으면 위와 같이 GitHub에서 표시가 됩니다.

빈 줄을 추가해야하는 이유는 GitHub의 컨벤션 때문에 그렇습니다. GitHub은 변경사항을 표시할 때 변경전 부분과 변경 후 를 모두 보여줍니다. 

```js
console.log('Hello');
```

만약 위와 같이 빈 줄이 없는 코드에서 아래에 코드를 추가하게 되면 Git은 다음과 같이 표시합니다.

```js
- console.log('Hello');
+ console.log('Hello');
+ console.log('world!');
```

저는 단순히 아래 한 줄만 추가했는데 왜 세줄이 변경되었다고 나오는 걸까요? 그 이유는 줄바꿈 문자 \n가 들어갔기 때문입니다. 


```js
- console.log('Hello');
+ console.log('Hello');\n
+ console.log('world');
```

만약 미리 빈 줄을 하나 추가한 상태에서 아래에 새로운 코드를 작성할 경우에는 다음과 같이 보여집니다.

```js
+ console.log('world');
```

이미 \n이 추가되어 있기 때문이죠. 따라서 코드 마지막 줄에 빈 줄 하나를 항상 추가해주는게 좋습니다.

2020-10-28 16:23 UTC, hannut91 commented on src/RestaurantDetail.jsx
> +        ))}
변수의 수명이 긴 이름일수록 더 구체적인 이름을 가져야 합니다. 왜냐하면 변수를 선언한 곳과 거리가 멀기 때문에 이름만 봐도 바로 알 수 있어야 하기 때문입니다. 반대로 변수의 수명이 짧을수록 더 간단한 이름을 사용해야 합니다. 변수의 수명이 짧은 이름은 아주 잠깐만 사용할 것이기 때문에 오래 기억할 필요가 없고 변수를 선언한 곳과 가깝기 때문에 쉽게 알 수 있기 때문입니다.

그래서 `menuItem`대신 `it`같은 간단한 이름을 사용할 수 있고 혹은 `menuItems`를 별도의 컴포넌트로 분리하면 `name`이 중복되는 문제도 같이 해결되겠죠?

2020-10-28 16:23 UTC, hannut91 commented on src/RestaurantDetail.test.jsx
> +  });
```suggestion
  RESTAURANT.menuItems.forEach(({ name }) => {
    expect(container).toHaveTextContent(name);
  });
```

이렇게 쓰는건 어떨까요?

2020-10-28 16:23 UTC, hannut91 commented
`Page` 컴포넌트가 상태를 관리하도록 해주셨군요. `Page` 컴포넌트는 그 자체로 다른 일을 한다고 생각해서 저는 `Page` 컴포넌트와 `Container`컴포넌트를 나눕니다.

2020-10-29 02:30 UTC, bbhye1 commented
> 
> 1. 절대경로로 지정하는 방법
> 
> `main.js`를 절대 경로로 수정하는 방법이 있습니다. 그러면 내가 현재 어떤 위치에 있던 일정한 방법으로 리소스를 가져올 수 있습니다.
> 
> ```
> <script src="/main.js"></script>
> ```
> 

PublicPath를 '/' 로 설정해서 빌드업하는 것도 이렇게 절대경로를 지정해주는것과 같은 것일까요??

2020-10-29 03:49 UTC, hannut91 commented
네 ㅎㅎ 실제로 들어간 결과도 눈으로 직접 확인해보면 좋을 것 같네요.

2020-10-29 04:05 UTC, bbhye1 commented
> `Page` 컴포넌트가 상태를 관리하도록 해주셨군요. `Page` 컴포넌트는 그 자체로 다른 일을 한다고 생각해서 저는 `Page` 컴포넌트와 `Container`컴포넌트를 나눕니다.

다시 나뉘보니 Page컴포넌트는 params를 받아와 dispatch 하는 부분이고 Restaurant에서는 dispatch와는 상관없이 상태를 불러와 하위 컴포넌트들을 보여주는 일을 하는 것으로 다른 역할이라고 해석할 수 있겠네요!

2020-10-29 15:09 UTC, hannut91 requested changes

2020-10-29 15:09 UTC, hannut91 commented on src/App.test.jsx
> +      regions: [{ id: 1, name: '서울' }],
regions도 fixture로 추출할 수 있을까요?

2020-10-29 15:09 UTC, hannut91 commented on src/App.test.jsx
> +  context('with invalid path ', () => {
`invalid`라기 보다는 정의되어 있지 않은 path라고 하면 어떨까요? 유효하지 않다는 것은 조금 오해의 소지가 있는 것 같아요. 예를들어서 `http://example.com\www` 같은게 `invalid`한 URL 인 것 같아요

2020-10-29 15:09 UTC, hannut91 commented on src/Loading.test.jsx
> +  const { container } = render((<Loading />));
여기선 소괄호를 한 개만 써주는게 좋을 것 같아요. 여러 줄일 때만 소괄호를 사용하는게 좋을 것 같아요

2020-10-29 15:09 UTC, hannut91 commented on src/RestaurantContainer.jsx
> +  ));
여기서는 소괄호가 두 개 들어간 것 같아요. 하나를 지워도 괜찮을 것 같아요

2020-10-29 15:09 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +    const restaurant = [];
`restaurant`이 왜 빈 배열로 초기화되는지 이해하기 어려운 것 같아요.

2020-10-29 15:09 UTC, hannut91 commented on src/RestaurantMenu.test.jsx
> +  const { container } = render((<RestaurantMenu menu={menu} />));
여기도 소괄호를 하나만 사용하는게 좋을 것 같아요

2020-10-29 15:09 UTC, hannut91 commented on src/RestaurantPage.jsx
> +  ));
여기도 소괄호를 하나만 사용하는게 좋을 것 같아요

2020-10-29 15:09 UTC, hannut91 commented on src/RestaurantsContainer.jsx
> +          </Link>
여기도 구조분해 할당으로 반복되는 `restaurant`사용을 줄이는건 어떨까요?

2020-10-30 02:52 UTC, bbhye1 commented
코드 한차례 리팩토링 마치고 추가로 레스토랑 상세페이지로 여러번 들어갈 때 이전에 남아있는 restaurant 때문에 로딩페이지 대신 이전  상세페이지 내용이 나와서 이부분 수정하기 위해  loadRestaurant action에서 초기화해주는 disptach를 추가했습니다.

2020-10-30 17:09 UTC, hannut91 commented on src/actions.test.js
> +      expect(actions[0]).toEqual(setRestaurant({}));
`loadRestaurant`가 하는 일이 무엇인지 테스트를 더 작성하면 좋을 것 같아요. 액션이 2번 실행되는줄 알았는데 한 번만 테스트하고 있는 것 같아서요

2020-10-31 16:05 UTC, hannut91 requested changes

2020-10-31 16:05 UTC, hannut91 commented on src/actions.test.js
> +    });
단순히 2번 호출하는 것보다 의도를 더 드러내면 좋을 것 같아요. 이렇게 하면 어떨까요?

```js
it('run setRestaurant', async () => {
  await store.dispatch(loadRestaurant());

  const actions = store.getActions();

  expect(actions).toEqual([
    setRestaurant({}),
    setRestaurant(RESTAURANT),
  ]);
});
```

2020-10-31 16:36 UTC, bbhye1 commented on src/actions.test.js
> +    });
음... 근데 여기서 보면 `expect(actions).toEqual([
    setRestaurant({}),
    setRestaurant(RESTAURANT),
  ]);` 를 확인하는 부분에서 RESTAURANT가 fetchRestaurant에 의해 나온 값인데 fetchRestaurant가 어떤 값을 반환하는지 여기서는 알 수 없어서  RESTAURANT로 확인을 해야 하는지 의문이 듭니다.  실제로 console.log를 찍어보면 actions가
`      [
        { type: 'setRestaurant', payload: { restaurant: {} } },  
        { type: 'setRestaurant', payload: { restaurant: {} } }   
      ]` 
 이렇게 나왔거든요.

2020-11-01 16:18 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 채널에 회고를 남겨주셔서 머지합니다. 

웹팩까지 심화학습을 하시고 그 과정에서 mocking에 대해서 배우신 것 같아서 좋네요 ㅎㅎ

2020-11-01 16:18 UTC, merged