Route pages through path name
CodeSoom/week6-assignment-1 pull request #19
Opened 2020-10-26 13:21 UTC by gringrape

2020-10-26 13:30 UTC, gringrape commented
## 작업 내용 
### 주제
location 객체의 pathname 을 이용해서 서로 다른 컴포넌트 보여주기
### 세부내용
- 경로가 '/restaurants' 일때, RestaurantsPage 표시
- 경로가 '/' 일때, HomePage 표시
- 경로가 존재하지 않을때, ErrorPage 표시
### 테스트
- location 객체의 mocking
https://stackoverflow.com/a/60697570
- URL 생성자
https://developer.mozilla.org/en-US/docs/Web/API/URL

2020-10-26 14:30 UTC, gringrape commented
- historyApiFallback
![image](https://user-images.githubusercontent.com/53764714/97185277-350d2100-17e3-11eb-958d-5ca39d14f343.png)

2020-10-27 14:13 UTC, hannut91 commented
글로벌 객체에 직접 접근해서 테스트가 어려워진 것 같아요. `LocationService`를 만들고 mocking하기 쉬워지지만, `MemoryRouter`를 사용해서 테스트하면 되니 할 필요는 없을 것 같습니다

2020-10-28 11:43 UTC, gringrape commented
## 작업 내용 
### 주제
react-router 를 이용해서 여러개의 페이지를 보여주기
### 세부내용
- About 페이지 구현
- NotFound 페이지 구현
- Home 페이지에서 링크로 About, Restaurants 페이지 연결

2020-10-28 16:27 UTC, hannut91 requested changes

2020-10-28 16:27 UTC, hannut91 commented on src/NotFoundPage.test.jsx
> +  expect(queryByText('존재하지 않는 페이지 입니다')).not.toBeNull();
```suggestion
  const { container } = render((
    <NotFoundPage />
  ));

  expect(container).toHaveTextContent('존재하지 않는 페이지 입니다');
```

다른 곳과 마찬가지로 텍스트만 검사한다면 이렇게 하는게 어떨까요?

2020-10-30 14:11 UTC, gringrape commented
## 작업내용
- 레스토랑 상세 페이지 구현
- 파라메터를 이용해서 상세 페이지 연결
- 리듀서, 액션 구현
## 작업후기
갑자기 일이 많이 생겨서 제대로 진행을 못했네요. ㅜ
일단 끝내자는 생각으로 급하게 했는데, 리뷰해 주시면 열심히 반영해보겠습니다!

2020-10-30 17:10 UTC, hannut91 commented on src/actions.js
> +}
저는 Loading을 직접 수정한다는 이름 보다는 `loading()` `done()`같은 이름을 쓰고 싶은데 너무 귀찮기만 할까요?

2020-10-31 12:27 UTC, gringrape commented on src/actions.js
> +}
그러네요. setLoading(true), setLoading(false) 는 확실히 무슨일을 하는지 말해주는 이름은 아닌것 같습니다. 세부적인 느낌이 들어서 사용되는 맥락을 보아야겠다는 느낌이 드는것 같습니다. 반면에 loading() done() 으로하면 그냥 명확하네요.

2020-10-31 12:29 UTC, gringrape commented on src/actions.js
> +}
현재는 해당 부분에서 restaurant === null 인 경우에 로딩중으로 바꿔서 상태 부분을 아예 삭제 했는데, 다음에는 이렇게 해야 겠습니다 ㅎ

2020-10-31 12:42 UTC, gringrape commented
## 작업내용
- 삭제되지 않은 불필요한 로직 삭제
- 헤더 컴포넌트 분리
- 메뉴 리스트 키 추가
- 기타 리팩토링

## 작업후기
부족해보이는 부분들을 리팩토링 하였습니다. 
진행하는데 급급해서 제공된 코드는 거의 건드리지 않았는데, 
작업하기로 한 이상 다 책임지는 코드라고 생각하고 적극 수정했어야 했다는 생각이 듭니다.

2020-10-31 16:42 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 로딩이라는 추가 기능까지 구현하시고 좋네요 ㅎㅎㅎ

이번 과제를 통해서 무엇을 배우셨나요?

2020-11-01 16:19 UTC, hannut91 commented
채널에 회고를 남겨주셔서 머지합니다 ㅎㅎ 고생하셨습니다

2020-11-01 16:19 UTC, merged