[week6-assignment] 레스토랑 상세 페이지 구현하기 - 진행중
CodeSoom/week6-assignment-1 pull request #22
Opened 2020-10-26 23:16 UTC by comejtome508

**요구사항**

- [ ] TDD로 기능 구현

- [ ] 커버리지 100% 달성

- [ ] About 페이지 구현

- [ ] Not found 페이지 구현

- [ ] 레스토랑 상세페이지 구현

**진행현황**

- HomePage 작성 중

2020-10-27 14:35 UTC, Kihyun92 requested changes
좋습니다! `red-green-refactoring` 사이클을 빠르게 가져가보시면 좋을 것 같아요~

2020-10-27 14:35 UTC, Kihyun92 commented on src/HomePage.jsx
> +    <div>
앞으로 수정 될 수 있지만, 지금 상황에서는 div 태그가 필요 없을 것 같네요~

2020-10-27 23:35 UTC, comejtome508 commented
<고민점>
- 현재 RestaurantsPage로의 route를 추가 한 후
 [TypeError: dispatch is not a function]에러가 나고 있는데 해당 에러에 대해서는 dispatch는 redux-store에 직접 접근을 해야만 하기 때문에 this.props를 추가하는 식으로 접근을 해야한다는내용이 많이 있습니다. 아직 정확하게 파악이 되지 않아서 고민점이 이게 맞는지 모르겠지만 검색해보는 중입니다.

2020-10-28 15:07 UTC, Kihyun92 requested changes
App.test.jsx에 RestaurantsPage로의 이동하는 테스트를 추가하니까 에러가 발생한다는 말씀이신가요?

혹시 dispatch를 mocking 해주지 않아 발생하는건 아닐까요?

```
  const dispatch = jest.fn();

  useDispatch.mockImplementation(() => dispatch);
```
한번 해보시고 말씀해주세용~

2020-10-28 15:07 UTC, Kihyun92 commented on src/App.jsx
> +      <Route path="/RestaurantsPage" component={RestaurantsPage} />
path는 소문자로 하시는 것을 추천합니다. 또한 단어의 연결이 필요할땐 하이픈(-)을 사용하는게 좋을 것 같습니다~:)

2020-10-28 15:07 UTC, Kihyun92 commented on src/App.test.jsx
> +      ));
중복되는 로직은 상위로 추상화하는게 좋을 것 같아요~

2020-10-29 02:38 UTC, comejtome508 commented
> **요구사항**
> 
> * [ ]  TDD로 기능 구현
> * [ ]  커버리지 100% 달성
> * [x]  About 페이지 구현
> * [ ]  Not found 페이지 구현
> * [ ]  레스토랑 상세페이지 구현
> 
> **진행현황**
> 
> * HomePage와 App의 test code 및 original code 작성
> * AboutPage, RestaurantsPage 작성 및 route 추가
> * RestaurantsPage에서 dispatch와 관련한 에러 해결 중



> App.test.jsx에 RestaurantsPage로의 이동하는 테스트를 추가하니까 에러가 발생한다는 말씀이신가요?
> 
> 혹시 dispatch를 mocking 해주지 않아 발생하는건 아닐까요?
> 
> ```
>   const dispatch = jest.fn();
> 
>   useDispatch.mockImplementation(() => dispatch);
> ```
> 
> 한번 해보시고 말씀해주세용~

감사합니다~! dispatch = jest.fn(); 이 없었습니다 ㅎㅎㅎ 현재는 detail 페이지로 링크 누를 경우 api 호출을 하도록 하기 위해 저번주 과제의 구조를 좀 파악해봐야 할 듯합니다~!

2020-10-29 17:49 UTC, Kihyun92 requested changes
좋습니다! TDD도 잘 적용하며 진행해주고 계신 것 같아요~ `red-green-refactoring`사이클을 작게 가져가는 방법도 좋을 것 같아요~ 차근차근 해보시면 금방 하실 수 있을 것 같습니다☺️

도움이 필요하면 언제든 말씀주세요~

2020-10-29 17:49 UTC, Kihyun92 commented on src/App.jsx
> +      <Route path="/detail" component={RestaurantsPage} />
상세 페이지로 이동하는 path를 추가해주셨네요~! 주로 path는 `RESTful API` 방식을 사용합니다.

```
GET /restaurants -> collection(복수형)
GET /restaurants/1 -> 1이라는 id에 대한 element, member
```
위와 같은 방식으로 주로 사용됩니다 ㅎㅎ
따라서 지금 코드에도 특정 id에 대한 상세페이지 라는걸 알 수 있는 경로면 좋을 것 같습니다~

`REST API`에 대해서는 많은 자료들이 있으니 공부해보시면 좋을 것 같아요!

2020-10-29 17:49 UTC, Kihyun92 commented on src/App.test.jsx
> +    </MemoryRouter>
앞쪽에 공백 추가해서 들여쓰기 해주세요~

2020-10-29 17:49 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +          <Link to="/restaurant.name">{restaurant.name}</Link>
구조 분해 할당을 적용하면 어떨까요?

2020-10-31 17:31 UTC, Kihyun92 commented
@comejtome508 님~ 과제는 잘 진행하고 계신가요? 혹시 막히거나 의논이 필요한 부분이 있다면 말씀주세요 :)

2021-01-17 12:58 UTC, closed without merging