[6주차] Routing-Apply
CodeSoom/week6-assignment-1 pull request #23
Opened 2020-10-27 10:09 UTC by onys-programmer

2020-10-27 11:38 UTC, onys-programmer commented
나름 테스트를 만들어보았으나 작동하지 않습니다..ㅎㅎ 2강을 보고 다시 시도해야겠습니다.

2020-10-28 00:10 UTC, hannut91 reviewed
강의를 따라하면서 진행하고 계신 것 같아요. 리액트 라우터가 무슨 일을 하는지 주의해서 보시면 좋을 것 같습니다

2020-10-29 10:08 UTC, onys-programmer commented
강의를 보고 진행하다보니 Red Green Refactoring 사이클이 꼬여 그 사이클을 복구하려고 노력했습니다.

2020-10-29 10:10 UTC, onys-programmer commented
> 강의를 보고 진행하다보니 Red Green Refactoring 사이클이 꼬여 그 사이클을 복구하려고 노력했습니다.

HomePage에서 Link를 구현하기 위해 어떻게 테스트를 작성해야할 지 고민중입니다.

2020-10-29 15:12 UTC, hannut91 requested changes

2020-10-29 15:12 UTC, hannut91 commented on src/AboutPage.Test.jsx
> +});
`AboutPage`가 올바르게 렌더링이 되는지 확인하는 간단한 테스트로 시작해서 좋은 것 같아요 ㅎㅎ 이 페이지가 어떤 일을 하는지 추가적인 테스트를 작성하여 의도를 더 드러내면 좋을 것 같아요

2020-10-29 15:12 UTC, hannut91 commented on src/App.test.jsx
> +      ));
렌더하는 부분이 반본적으로 사용되고 있는 것 같아요. 함수로 추출해서 재사용하는건 어떨까요?

2020-10-29 15:12 UTC, hannut91 commented on src/App.test.jsx
> +  context('without valid path', () => {
path가 invalid하다는 것은 정말 유효하지 않다는 거에요. 예를들어서 경로에 `http://example.com\restaurants`라고 되어있으면 안되겠죠. 이 테스트의 경우는 invalid한 경우보다는 path가 존재하지 않는 경우인 것 같아요

2020-10-30 12:54 UTC, onys-programmer commented
오늘은 부담감에 지레 겁먹고 공부를 시작 못하고 있다가, 그래 한시간만 딱 하고 오자, 라는 마음으로 카페에 나왔는데요.. 
시작하자마자 너무 재미있어서 몇시간은 더 코딩하고 싶은 마음이었습니다. 
부담감은 막상 시작하면 별거 아니라는 경험을 계속해도 인간은 같은 실수를 반복하네요 ㅎㅎ
그래도 코딩이 재미있어 다행입니다. 
깃허브에서 과제를 테스트하는 과정도 오늘 처음으로 유심히 볼 수 있게 되었는데요, 앞으로 제가 할 일이 무엇인지 알게 되어 신기했습니다.
내일은 레스토랑 상세페이지를 구현해보겠습니다.

2020-10-30 16:43 UTC, hannut91 reviewed
열심히 했고 그 과정이 재밌었고 많이 배우신 것 같아요 ㅎㅎ 이 때 감정을 잊지 않으셨으면 좋겠습니다. 앞으로 계속 나아가는데 많은 도움이 될거에요

2020-10-30 16:43 UTC, hannut91 commented on src/AboutPage.Test.jsx
> +    </MemoryRouter>
`AboutPage`를 테스트할 때는 `MemoryRouter`가 필요 없을 것 같아요

2020-10-30 16:43 UTC, hannut91 commented on src/HomePage.test.jsx
> +    ));
컴포넌트를 렌더하는 부분이 중복되는 것 같아요. 함수로 추출하는건 어떨까요?

2020-10-30 16:43 UTC, hannut91 commented on src/NotFound.test.jsx
> +  ));
`AboutPage`에서는 `MemoryRouter`를 사용하지 않아도 될 것 같아요

2020-10-31 00:05 UTC, onys-programmer commented
> 열심히 했고 그 과정이 재밌었고 많이 배우신 것 같아요 ㅎㅎ 이 때 감정을 잊지 않으셨으면 좋겠습니다. 앞으로 계속 나아가는데 많은 도움이 될거에요

열심히 했다고 인정해주셔서 감사합니다. 선생님들이 더욱 보람찰 수 있도록 더욱 재밌게 열심히 해보겠습니다 ^^

2020-10-31 12:11 UTC, onys-programmer commented
오늘은 새벽부터 부산으로 결혼식을 가는 바람에 짬짬이 코딩하였습니다~! actions.test와 actions에 레스토랑 상세페이지를 구현하는 것을 만들어볼 예정입니다.

2020-10-31 16:38 UTC, hannut91 requested changes
레스토랑 상세페이지를 아직 구현중이신 것 같아요 ㅎㅎ

2020-10-31 16:38 UTC, hannut91 commented on src/NotFound.test.jsx
> +});
`AboutPage`를 `NotFoundPage`로 import하고 있고,
파일 이름은 `NotFound`인데 테스트 이름은 `AboutPage`이고
실제 테스트의 이름은 `NotFoundPage`네요

2020-10-31 16:38 UTC, hannut91 commented on src/services/api.test.js
> +      mockFetch(RESTAURANTDETAILS);
`RESTAURANT_DETAILS`이렇게 구분해주면 더 읽기 좋을 것 같아요

2020-11-01 11:46 UTC, onys-programmer commented on src/NotFound.test.jsx
> +});
앗.. 감사합니다!

2020-11-01 11:48 UTC, onys-programmer commented on src/services/api.test.js
> +      mockFetch(RESTAURANTDETAILS);
감사합니다!

2020-11-01 16:24 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 어려운 내용들을 잘 소화해주신 것 같아요.

과제를 너무 따라하는 것 보다는 강의를 모두 학습한 후에 배웠던 내용들을 보지 않고 상기하면서 과제를 진행해보시면 좋을 것 같아요.

2021-01-17 12:58 UTC, merged