Week6 restaurant detail TDD [작성중]
CodeSoom/week6-assignment-1 pull request #26
Opened 2020-10-27 14:42 UTC by saseungmin

## 🚀 레스토랑 상세 페이지 구현하기
- 레스토랑 상세페이지 만들기

### 📌 과제 목표
- [ ] TDD로 기능 구현
- [ ] 커버리지 100% 달성
- [ ] About 페이지 구현
- [ ] Not found 페이지 구현
- [ ] 레스토랑 상세페이지 구현

2020-10-27 16:09 UTC, saseungmin commented
![1](https://user-images.githubusercontent.com/60910665/97328886-d23a8900-18b9-11eb-9882-fc819f7cd57a.PNG)

- 전체적으로 다 구현하였고, 한가지 문제가 발생하였습니다ㅠㅠ
- `http://localhost:8080/restaurants/1` 이런식으로 직접 URL을 입력하였을 때, 위 사진과 같이  `http://localhost:8080/restaurants/main.js`이런식으로 넘어갑니다.. 무슨이유인지 모르겠습니다.
- 직접 link를 클릭하면 아무 이상없습니다.
- 답변 부탁드립니다!! 🙏

2020-10-28 10:50 UTC, saseungmin commented on index.html
> +  <script src="/main.js"></script>
- 오류나는 원인을 찾았습니다..
이러한 문제가 일어나는 이유가 무엇일까요? 🤔

2020-10-28 16:01 UTC, Kihyun92 requested changes
피드백이 조금 늦었네요😅 전반적으로 `red-green-refactoring`사이클을 잘 가져가고 계신것 같아요 👍 

공통 디렉토리에 서로 역할이 비슷한 파일들이 너무 많이 있는 것 같아요. 관심사에 맞게 폴더 구조를 분리해보면 어떨까요?ㅎㅎ

한번 확인해보시고 말씀해주세요~ :)

2020-10-28 16:01 UTC, Kihyun92 commented on src/RestaurantDetailContainer.jsx
> +      ))}
Container를 잘 작성해주셨네요! 다음 단계는 presentational component들과 분리해보실 예정이겠죠? 😁

아하 아래 코드들을 더 보고 구조를 알았습니다.

개인적으로 각 컴포넌트의 역할과 네이밍이 맞지 않게 느껴져요. 왜 이렇게 됐을까요? 하나의 폴더에서 모든 파일들을 관리해서 일수도 있을 것 같습니다. 관심사 별로 폴더를 쪼개보는건 어떨까요? ㅎㅎ

2020-10-28 16:01 UTC, Kihyun92 commented on src/RestaurantDetailContainer.test.jsx
> +      ));
테스트 코드도 리펙토링 대상입니다~ `Refactoring` 단계에서 잊지마시고 중복되는 코드는 없애주시면 더 좋을 것 같습니다 :)

2020-10-28 16:01 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +export default withRouter(RestaurantDetailPage);
`withRouter`로 래핑해준 이유가 있나요? :)

2020-10-28 16:01 UTC, Kihyun92 commented on src/RestaurantDetailPage.test.jsx
> +      </Router>
`createMemoryHistory`를 사용해서 라우터를 테스트해보셨네요~ 좋습니다 :)
이미 아시겠지만, MemoryRouter를 사용하고 `RestaurantDetailPage` 컴포넌트에 props로 match 값을 넘겨주는 방식도 심플할 것 같네요~

2020-10-28 16:01 UTC, Kihyun92 commented on index.html
> +  <script src="/main.js"></script>
음,, 이렇게 수정했더니 해결된건가요?.. 이상하군요,,

에러를 보니 제 생각에는 App.js에서 레스토랑 페이지로 이동시키는 Route에 `exact`가 빠져서 발생하는 것 같아요. 잘못된 요청에 따른 응답인거죠.

2020-10-28 16:01 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/restaurants" component={RestaurantsPage} />
exact 추가해주세요~

2020-10-29 12:57 UTC, saseungmin commented on index.html
> +  <script src="/main.js"></script>
- 알려주신대로 `exact`를 추가하였지만 같은 현상이 발생하였습니다 ㅠㅠ 😢
- 그래서 다시 원래대로 변경해주었습니다..

2020-10-29 13:00 UTC, saseungmin commented on src/RestaurantDetailContainer.jsx
> +      ))}
`component`로 분리해주었습니다! 🙏

2020-10-29 13:20 UTC, saseungmin commented on src/RestaurantDetailPage.jsx
> +export default withRouter(RestaurantDetailPage);
`withRouter` 없이 `match`나 `history`를 못가져오는 줄 알았습니다.. 제거해도 가져올수 있군요..

2020-10-29 13:29 UTC, saseungmin commented on src/RestaurantDetailPage.test.jsx
> +      </Router>
- `RestaurantDetailPage`에서 언마운트될 때 뒷정리해주는 `dispatch`을 테스팅 해주는 방식은 `createMemoryHistory` 없이 어떻게 해주어야 할까요??
- 아니면 이 부분은 `RestaurantDetailPage`에서의 관심사가 아닐까요?
```jsx
  useEffect(() => {
    dispatch(loadRestaurantDetail(id));
    return () => {
      dispatch(resetRestaurantDetail());
    };
  }, []);
```
- 현재 테스트 이런식으로 되어있습니다.
- 언마운트될 때 `dispatch` 액션을 called 했는지 확인할 방법? 이 또 있을까요??

```jsx
  it('renders initial restaurant', () => {
    const history = createMemoryHistory();
    history.push('/');

    render((
      <Router history={history}>
        <RestaurantDetailPage match={{ params: { id: null } }} />
      </Router>
    ));

    expect(dispatch).toBeCalledWith({
      type: 'resetRestaurantDetail',
    });
  });
```

- 굳이 안해도 커버리지 100%를 만족하긴 했습니다..

2020-10-29 13:30 UTC, saseungmin commented on src/App.jsx
> +        <Route path="/restaurants" component={RestaurantsPage} />
- 알려주신대로 `exact`를 추가하였지만 같은 현상이 발생하였습니다 ㅠㅠ 😢
- 그래서 다시 원래대로 변경해주었습니다..

2020-10-29 17:22 UTC, Kihyun92 requested changes
디렉토리 구조를 잘 나눠보신것 같아요~ 👍

2020-10-29 17:22 UTC, Kihyun92 commented on index.html
> +  <script src="/main.js"></script>
아이고 ㅠㅠ  제가 어제는 차이점을 못봤는데 다시보니 script 태그 안에 main.js 앞에 `/`가 추가됐군요!

이 차이와 에러가 뭘 말하는 지를 보면 원인을 파악하는데 도움이 될 것 같네요~
우선 서버에 우리가 해당 url로 요청을 했는데 `404 not found` 라는 응답이 내려왔죠. 자세히 보면 `request url` 경로가 잘못 됐다는 걸 알 수 있어요. 어떤 이유로 인해 저렇게 요청이 바뀐건지 고민해보시면 좋을 것 같습니다~ ☺️

각각 요청 성공과 실패에 대한 네트워크 정보입니다.
![image](https://user-images.githubusercontent.com/35797540/97607891-f2eb1600-1a54-11eb-9c36-4c2f76a9c513.png)
![image](https://user-images.githubusercontent.com/35797540/97607924-fd0d1480-1a54-11eb-9241-09e5fc8565fa.png)

2020-10-29 17:22 UTC, Kihyun92 commented on index.html
> +</html>
파일의 끝엔 항상 공백을 추가해주세요~

PR 요청하시고, 소스를 한번 쭉 봐보시면 표시된 부분으로 파악할 수도 있습니다~
![image](https://user-images.githubusercontent.com/35797540/97609001-6e999280-1a56-11eb-913e-5ba32703bf41.png)

그리고 기존 코드 포멧과 같이 코드 앞쪽에 공백 추가해주세요~

2020-10-29 17:32 UTC, Kihyun92 commented on src/RestaurantDetailPage.test.jsx
> +      </Router>
시도해보신 방식도 좋지만, 제 생각에는 `restaurantDetail`에 대한 초기화를 컴포넌트 단에서 해주지 않아도 될 것 같아요. 
해당 컴포넌트에서는 단순히 `loadRestaurantDetail`만 `dispatch` 하고, 초기화는 `action.js`에서 `loadRestaurantDetail`을 `dispatch` 해주는 부분에서 `최초 호출 시점`에 항상 초기화 해준다면 어떨까요? 🤔

2020-10-30 10:39 UTC, saseungmin commented on src/RestaurantDetailPage.test.jsx
> +      </Router>
- 변경해주었습니다!
- 이 방법이 더 간단한 방법인거 같네요. 이 방법은 생각하지 못했었네요🙏

2020-10-30 10:54 UTC, saseungmin commented
- 로컬에서 `npm test`후 모두 성공 후 `push`를 하고 github에서 테스트가 진행될 때 가끔씩 `fail` 되는 경우가 있습니다.
- 그리고 그 후 불필요한 커밋을 다시 또 하여 테스트가 통과되는 경우가 있는거 같습니다.
그래서 불필요한 커밋 (Fixed Temp Test, Fixed Test)을 다시 해서 성공하게 했는데 이유가 무엇일까요?

2020-10-30 10:55 UTC, saseungmin commented on index.html
> +</html>
자세한 설명 감사합니다!! 🙏🙏

2020-10-30 16:18 UTC, Kihyun92 requested changes
폴더 구조가 분리되니까 훨씬 보기 좋은 것 같아요! 👍 

말씀주신 github test fail 이슈는 확인해보고 말씀드릴게요~

2020-10-30 16:18 UTC, Kihyun92 commented on src/actions.js
> +    dispatch(resetRestaurantDetail());
`resetRestaurantDetail`이 꼭 필요할까요? `setRestaurantDetail`에 빈 배열을 넣어주는건 어떤가요?

2020-10-30 16:18 UTC, Kihyun92 commented on src/components/category/CategoryList.jsx
> +const CategoryList = ({ categories, onSelectCategoryClick, selectedCategory }) => {
`onSelectCategoryClick` select와 click의 의미가 중복되는 것 같아요~ 둘 중 하나만 포함되어도 좋을 것 같습니다 :)

2020-10-30 16:18 UTC, Kihyun92 commented on src/components/detail/RestaurantDetail.jsx
> +        </li>
구조 분해 할당으로 처리해도 좋겠네요~

2020-10-30 16:18 UTC, Kihyun92 commented on src/components/detail/RestaurantDetail.test.jsx
> +    it('see renders restaurant', () => {
`see`와 `render` 둘다 보여진다는 중복된 의미를 가지는 것 같아요~ 둘 중에 하나만 포함해줘도 의미가 전달될 것 같습니다~

2020-10-30 16:18 UTC, Kihyun92 commented on src/components/restaurant/RestaurantList.jsx
> +          restaurant={restaurant}
레스토랑 컴포넌트에서도 `const Restaurant = ({ restaurant: { id, name } }) => (`와 같이 받아서 처리하고 있는데, `id`와 `name`을 내려주는건 어떨까요?

2020-10-31 06:33 UTC, saseungmin commented on src/components/detail/RestaurantDetail.jsx
> +        </li>
- 이 부분은 위에서 `const { name, address, menuItems } = restaurant;` 이미 `name`이 선언되어 있어서 구조 분해 할당으로 `menuItems`을 처리할 때 eslint error가 생겨서 구조 분해 할당으로 처리하지 않았습니다.

2020-10-31 16:45 UTC, Kihyun92 approved these changes
고생하셨습니다! 이번 과제도 쉽지 않았는데, 잘 해주신것 같아요 👍  특히 TDD 사이클을 잘 가져가시는 것 같고, 이전 과제들의 의도들을 잘 흡수하신 것 같습니다 ㅎㅎ

이번 과제를 하면서 느꼈던 부분이나 더 알고 싶은 부분, 아쉬웠던 부분들이 있을까요? 한번 고민해보시면 좋을 것 같습니다~😁

2020-11-01 09:15 UTC, saseungmin commented
- 이번주 코드리뷰도 감사합니다! 🙏

2020-11-02 14:03 UTC, merged