week6 - Create restaurant detail page
CodeSoom/week6-assignment-1 pull request #28
Opened 2020-10-28 11:28 UTC by hyejineee

## 과제 목표

- [ ] TDD로 기능 구현
- [ ] 커버리지 100% 달성
- [ ] About 페이지 구현
- [ ] Not found 페이지 구현
- [ ] 레스토랑 상세페이지 구현

## 요구사항

- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

2020-10-28 16:43 UTC, Kihyun92 requested changes
좋습니다! red-green-refactoring 사이클을 잘 가져가고 계신 것 같네요~
복잡하게 느껴질 수록 이전에 배웠던 관심사에 맞게 처리하고 있는지 고민해보시면 좋을 것 같습니다~

도움이 필요하면 언제든 말씀해주세요~ ☺️

2020-10-28 16:43 UTC, Kihyun92 commented on src/App.jsx
> +
공백을 추가하신 의도가 있나요? 없다면 제거해주면 좋을 것 같아요~ :)

2020-10-28 16:43 UTC, Kihyun92 commented on src/App.test.jsx
> +  describe('/about', () => {
`context`를 사용해서 표현하면 어떨까요?

2020-10-29 01:11 UTC, hyejineee commented on src/App.jsx
> +
네넵! 수정하겠습니다!!

2020-10-29 01:22 UTC, hyejineee commented on src/App.test.jsx
> +  describe('/about', () => {
그럼 단정문을 'when url is /about'으로 하면 될까요???

2020-10-29 04:15 UTC, hyejineee commented
App.test.jsx를 보니 인수테스트랑 많이 비슷한 것 같습니다. App컴포넌트의 역할이 url에 따라 다른 컴포넌트를 그려주는 역할을 한다고 생각하여 App 컴포넌트 테스트에 각 url일때 해당하는 컴포넌트를 그린다. 라는 식의 테스트들을 만들었는데 기현님 생각은 어떠신지 궁금합니다.ㅎㅅㅎ

2020-10-29 15:59 UTC, Kihyun92 commented on src/App.test.jsx
> +  describe('/about', () => {
`path가 ~~ 일때` 라는 의미가 들어가기만 하면 될 것 같아요~ :)

2020-10-29 16:52 UTC, Kihyun92 requested changes
> App.test.jsx를 보니 인수테스트랑 많이 비슷한 것 같습니다. App컴포넌트의 역할이 url에 따라 다른 컴포넌트를 그려주는 역할을 한다고 생각하여 App 컴포넌트 테스트에 각 url일때 해당하는 컴포넌트를 그린다. 라는 식의 테스트들을 만들었는데 기현님 생각은 어떠신지 궁금합니다.ㅎㅅㅎ

공감합니다👍  App 테스트를 잘 구현하신 것 같아요~ 말씀하신대로 App 컴포넌트의 위치 상 테스트가 인수테스트와 비슷한 방향이 될 수 밖에 없다고 생각합니다 ㅎㅎ 본인이 어떤 기준을 잡고 구현하느냐에 따라 방향이 달라질 수 있을 것 같네요 :)

2020-10-29 16:52 UTC, Kihyun92 commented on src/App.jsx
> +
여기도 공백이 있는듯 하네요 ㅎㅎ 제거 부탁드립니다~

2020-10-29 16:52 UTC, Kihyun92 commented on src/App.test.jsx
> +    },
레스토랑 객체에 많은 정보가 들어있네요~ 초기화 객체를 따로 추상화 해두고 사용하는건 어떨까요?

2020-10-29 16:52 UTC, Kihyun92 commented on src/NotFoundPage.jsx
> +    <div>
지금 같은 경우에는 div태그로 감싸줄 필요는 없을 것 같아요~

2020-10-29 16:52 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +            <li key={menu.id}>{menu.name}</li>
구조 분해할당을 적용하면 어떨까요?

2020-10-29 16:52 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +  return (
레스토랑 상세 페이지를 잘 구현해주신 것 같아요!
다만, 관심사의 관점에서 봤을때, 현재 이 컴포넌트는 다양한 역할을 하고 있는 것 같아요~ 아마 수정하실 예정이셨겠지만 고민해보시면 좋을 것 같습니다 ㅎㅎ
`Container / Presentation component`, 그리고 라우팅 관점에서 볼 수 있을 것 같네요 :)

2020-10-29 16:52 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +            {restaurant.name}
구조 분해 할당으로 표현해도 좋을 것 같습니다~

2020-10-29 16:52 UTC, Kihyun92 commented on src/reducer.js
> +  },
`initialRestaurant`처럼 추상화해서 선언해주면 어떨까요? :)

2020-10-30 04:53 UTC, hyejineee commented on src/App.jsx
> +
넵! 수정하겠습니다~~

2020-10-30 04:56 UTC, hyejineee commented on src/App.test.jsx
> +    },
음 따로 추상화한다는게 
```js
const initialRestaurant =  {
      id: null,
      categoryId: null,
      name: '',
      address: '',
      menuItems: [],
      reviews: [],
      information: ',',
}

const initialState = {
...state,
restaurant : initialRestaurant,
}
```
이렇게 리팩토링 하면 좋겠다는 말씀이신가요???

2020-10-30 04:57 UTC, hyejineee commented on src/NotFoundPage.jsx
> +    <div>
네넵~ 수정하겠습니다.~~

2020-10-30 04:59 UTC, hyejineee commented on src/RestaurantDetailPage.jsx
> +            <li key={menu.id}>{menu.name}</li>
해당하는 부분은 위에 
```js
const { id } = useParams();
```
와 겹쳐서 구조분해할당 대신에 객체에서 꺼내쓰는거(?)로 구현했어요!!

2020-10-30 05:01 UTC, hyejineee commented on src/RestaurantDetailPage.jsx
> +  return (
네넵! 수정하겠습니다ㅎㅎㅅㅎ

2020-10-30 05:01 UTC, hyejineee commented on src/RestaurantsContainer.jsx
> +            {restaurant.name}
네넵!!

2020-10-30 05:02 UTC, hyejineee commented on src/reducer.js
> +  },
위에 내용 처럼 말이죠??ㅎㅅㅎ
https://github.com/CodeSoom/week6-assignment-1/pull/28#discussion_r514860812

2020-10-30 13:46 UTC, Kihyun92 commented on src/App.test.jsx
> +    },
넵 맞습니다~~ 개인적으로는 이렇게 처리하는게 여러 측면에서 더 깔끔할 것 같습니다 ㅎㅎ

2020-10-31 17:30 UTC, Kihyun92 approved these changes
`RestaurantContainer`를 분리해보셨네요! 좋은 것 같아요 👍 

이번 주 과제도 쉽지 않았는데 잘해주신것 같습니다 :) TDD도 잘 가져가신 것 같고, 이전 과제에서 배웠던 것들도 잘 적용해주신것 같아요 ㅎㅎ

이번 과제를 하면서 느낀점이나 아쉬웠던 부분, 더 해보고 싶은 부분이 있나요? 한번 고민해보시면 좋겠습니다~

2020-10-31 17:30 UTC, Kihyun92 commented on src/App.test.jsx
> +  describe('/any_not_exist_url', () => {
개인적으로 `any_not_exist_url`이라는 문장은 이 테스트를 이해하는데 어려운 것 같아요. 

`올바르지 않은 경로`임을 알 수 있는 문장은 어떨까요? 🤔

2020-11-02 14:03 UTC, merged