[week6] 과제 수행중
CodeSoom/week6-assignment-1 pull request #29
Opened 2020-10-28 13:43 UTC by ParkDongJo

- Top - Down 방식으로 TDD 진행

2020-10-29 15:16 UTC, hannut91 requested changes

2020-10-29 15:16 UTC, hannut91 commented on src/AboutPage.test.jsx
> +  render((<AboutPage />));
여러줄일 때 소괄호를 사용하는데 이 경우에는 사용하지 않아도 될 것 같아요

2020-10-29 15:16 UTC, hannut91 commented on src/App.test.jsx
> +  context('with invalid path ', () => {
`path`가 `invalid`하다는 것은 정말 유효하지 않은 path를 말하는 것 같아요. 예를들면 `http://localhost:3000\restaurants` 처럼요. 
이 테스트의 경우에는 정의되어 있지 않은 path를 테스트하고 있는 것 같아요

2020-10-29 15:16 UTC, hannut91 commented on src/NotFoundPage.jsx
> +}
```suggestion
}

// Some other code
```

코드 마지막 줄에는 빈 줄이 하나가 추가되어야 합니다. 그렇지 않으면 위와 같이 GitHub에서 표시가 되고 또한 eslint에서 통과하지 못합니다. 

빈 줄을 추가해야하는 이유는 GitHub의 컨벤션 때문에 그렇습니다. GitHub은 변경사항을 표시할 때 변경전 부분과 변경 후 를 모두 보여줍니다. 


```js
console.log('Hello');
```

만약 위와 같이 빈 줄이 없는 코드에서 아래에 코드를 추가하게 되면 Git은 다음과 같이 표시합니다.

```js
- console.log('Hello');
+ console.log('Hello');
+ console.log('world!');
```

저는 단순히 아래 한 줄만 추가했는데 왜 세줄이 변경되었다고 나오는 걸까요? 그 이유는 줄바꿈 문자 \n가 들어갔기 때문입니다. 


```js
- console.log('Hello');
+ console.log('Hello');\n
+ console.log('world');
```

만약 미리 빈 줄을 하나 추가한 상태에서 아래에 새로운 코드를 작성할 경우에는 다음과 같이 보여집니다.

```js
+ console.log('world');
```

이미 \n이 추가되어 있기 때문이죠. 따라서 코드 마지막 줄에 빈 줄 하나를 항상 추가해주는게 좋습니다.

2020-10-29 15:16 UTC, hannut91 commented on src/NotFoundPage.test.jsx
> +  render((<NotFoundPage />));
여기도 소괄호가 하나만 들어가도 될 것 같아요

2020-10-30 16:40 UTC, hannut91 commented
과제 진행사항을 알려주세요 ㅎㅎ

2020-10-31 03:01 UTC, ParkDongJo commented on src/NotFoundPage.jsx
> +}
@hannut91 린트에서 빈 한줄을 계속 체크하는게 이런 이유였군요. 감사합니다. 반영하였습니다.

2020-10-31 16:17 UTC, hannut91 requested changes

2020-10-31 16:17 UTC, hannut91 commented on src/App.jsx
> +  // }[pathname] || NotFoundPage;
사용되지 않는 주석은 삭제하거나 왜 주석처리를 했는지 설명이 있으면 좋을 것 같아요

2020-10-31 16:17 UTC, hannut91 commented on src/actions.js
> +    dispatch(setRestaurant(selectedRestaurant));
selected라는 의미는 이 액션에서는 필요없는 말 같아요. `restaurant`라는 이름을 사용하는건어떨까요?

2020-10-31 16:21 UTC, hannut91 commented on src/reducer.test.js
> +  });
레스토랑을 선택할 때 이 액션이 실행되고 그래서 `selected`라는 이름이 사용된 것 같아요. 이 reducer함수만 보면 레스토랑이 선택되어진 것인지는 중요한 문맥이 아닐 것 같아요

2020-11-01 11:06 UTC, ParkDongJo commented on src/actions.js
> +    dispatch(setRestaurant(selectedRestaurant));
@hannut91 아 넵 듣고보니 selected 라는 의미는.. 해당 엑션으로 봤을때, 없는게 나은거 같습니다. 수정하겠습니다.

2020-11-01 16:27 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ history가 변화는 것 까지 테스트하면서 꼼꼼하게 과제를 진행해주신 것 같아요.

테스트에 대해서 많이 고민하신 흔적이 보입니다. 반복 학습하면서 여러가지 시도를 하면서 점점 정립이 될 것 같아요

2021-01-17 12:58 UTC, merged