[과제] Restaurant Details Page
CodeSoom/week6-assignment-1 pull request #30
Opened 2020-10-28 15:58 UTC by TaeWoongKim2

2020-10-28 16:02 UTC, TaeWoongKim2 commented
## 한 일

- 코드숨 6강 라우팅(Routing) 강의를 듣고 라우터에 대한 기본 사용법 익히기!
- 원복 후 처음부터 다시 진행해보기!

## 할 일

- [ ] 레스토랑 상세 페이지 구현하기
- [ ] TDD로 기능 구현
- [ ] 커버리지 100% 달성

2020-10-29 18:00 UTC, Kihyun92 reviewed
열심히 하려는 의지가 느껴지는 것 같아요 좋습니다~ 👍

`Red-Green-Refactoring`을 잘 적용해보고 계신 것 같네요~ 남겨주신 커밋을 보니 `Refactoring`과정이 빠져있거나, 순서가 맞지 않는 경우도 보여요 ㅎㅎ 테스트의 사이클을 조금 작게 가져가는 것도 좋을 것 같습니다. 원인은 `Green`단계에서 완성도를 높이는데 집중하기 때문일 수도 있을 것 같네요. 당장은 테스트를 성공시키는데 목적을 두고, 그 이후의 완성도는 refactoring 단계에서 챙기는걸 의식하면서 해보셔도 좋을 것 같습니다~ 이래저래 말이 길어졌네요 ㅎㅎ 잘못됐다는 말은 아니니 오해는 말아주세요 😁

2020-10-30 17:18 UTC, TaeWoongKim2 commented
## 📦 한 일

- 레스토랑 상세정보 조회 API 적용.
- 레스토랑 상세정보 페이지 구현 및 라우터 등록.
- 레스토랑 redux에 상태관리 등록 및 action creator 생성.
- 레스토랑 상세정보 조회 기능 구현.

## ⌨️ 할 일

- [x] 코드 리팩토링
- [x] TDD 방식 구현
- [x] 커버리지 100% 달성


> 테스트를 성공시키는데 목적을 두고, refactoring 단계에서 완성도를 높이려고 해봤지만, JEST에서 내뿜어 내는 오류를 보면 혼미합니다..ㅠ
그런 오류를 고치면서 중간중간 TDD cycle이 파괴되는 듯 합니다. 너무 이리저리 왔다갔다 하면서 구현해서 보기 어려우실까 걱정이 됩니다.
추가로, RestaurantContainer 에서 자식 컴포넌트를 굳이 안 나눈 이유는 아직 아무것도 기능이 없는 상세정보이기 때문에 나누지 않았습니다.
제 눈에는 나눈게 오히려 굳이(?) 라는 느낌이 들어서 원복시켰습니다. 혹시 나누는게 더 좋다면 바로 나누겠습니다 :)

2020-10-31 16:34 UTC, Kihyun92 requested changes
TDD 사이클을 잘 지키면서 구현하신 것 같아요 ㅎㅎ
jest에서 내뿜는 에러들이 많다면 한번에 너무 많은 기능을 테스트 하려한게 아닐까요? 테스트를 조금 더 적게 가져가는 방법이 있을 것 같아요 ㅎㅎ 물론 에러 자체가 굉장히 길다보니 힘들기도 하죠😂 그럴때일 수록 차근차근 해결해보시면 좋을 것 같습니다! 
그리고 TDD 사이클이 헝클어지는건 문제가 아닌것 같아요. 다만 `Red-Green-Refactoring`사이클을 가져가지 못하는 원인에 대해서 고민해보시고, 다음 테스트는 더 잘 구현하면 될 것 같아요 :)

추가로 `RestaurantContainer`를 작업하면서 많은 고민을 해보신 것 같아 좋습니다 👍 
지금도 좋지만, 제 생각에는 이전에 배웠던 `Container/Prensentation component` 측면에서 봤을때, 부모 컴포넌트와 함께 봤을때 `RestaurantContainer` 컴포넌트를 분리 할 수 있을 것 같은데 어떤가요?☺️

2020-10-31 16:34 UTC, Kihyun92 commented on src/services/api.js
> +    + `/${id}`;
전체 url에 template literal을 적용하는건 어떨까요?
```suggestion
  const url = `https://eatgo-customer-api.ahastudio.com/restaurants/${id}`;
```

2020-11-01 00:40 UTC, TaeWoongKim2 commented
## 📦 한 일

- 레스토랑 상세정보 페이지,  Container 및 Prensentation 컴포넌트로 분리
- 레스토랑 상세정보 로드 시, 로딩 메시지 출력.
- TDD 방식 구현
- 커버리지 100% 달성

## ⌨️ 할 일

- [ ] 레스토랑 상세정보 URL 직접 접근 및 refresh 시, 출력 안되는 현상 파악


> 모든 테스트 및 기능을 완료 후, ConceptJS 테스트에서 버그를 발견했습니다.
해당 문제는 레스토랑 상세정보 URL(/restaurants/:id)로 직접 접근하거나 해당 페이지에서 새로고침 시, 페이지가 먹통이 되는 현상이 발생했습니다. 해당 문제가 왜 발생하는지 잘 모르겠네요...ㅠㅠ

2020-11-01 01:34 UTC, TaeWoongKim2 commented
## 📦 한 일

- 레스토랑 상세정보 URL 직접 접근 및 refresh 시, 출력 안되는 현상 해결

URL(예:/about/test or /restaurants/1)  직접 입력 혹은 새로고침 시, main.js 에 대한 위치를 제대로 불러오지 못하는 것이 원인!

이를 해결하기 위해 '`html-webpack-plugin`' 플러그인을 설치 및 적용.
[참고] https://webpack.js.org/guides/output-management/

이후, 문제가 해결됐습니다.

2020-11-01 05:46 UTC, Kihyun92 approved these changes
이번 주 과제도 쉽지 않았는데 잘해주신것 같습니다 :) TDD도 잘 가져가신 것 같고, 이전 과제에서 배웠던 것들도 잘 적용해주신것 같아요 👍  그리고 커밋 메세지를 잘 작성해주셔서 저도 수월하게 리뷰 드릴 수 있었던 것 같습니다 ㅎㅎ

이번 과제를 하면서 느낀점이나 아쉬웠던 부분, 더 해보고 싶은 부분이 있나요? 한번 고민해보시면 좋겠습니다~

2020-11-01 12:55 UTC, TaeWoongKim2 commented
1. **한 일(Facts)**
    - **라우팅 처리 방식 및 History API 에 대한 이해**
    리액트 라우터(react-router-dom)를 사용하는 법과 공식 문서를 리딩했다.
    History API 가 어떻게 사용되는지 정리했다!
    - **과제 6. 레스토랑 상세 페이지 구현**
    라우팅을 통해 레스토랑의 상세정보를 출력하도록 구현했다!
    TDD 방식으로 구현했다!
    - **TDD Cycle 반복 연습 (반복숙달중)**

2. **배운 점 (Findings)**
    - **리액트 라우터 처리**
SPA 서비스를 만듬에 있어서 라우터의 역할이 중요하다. 페이지 이동시, 비동기실으로 변경이 필요한 컴포넌트만 재조립하는 방식을 취한다. 동기식에 비해 불필요한 리소스를 다시 로드할 필요가 없기 때문에 불필요한 자원 낭비를 막고, 사용자 경험(UX)도 긍정적으로 높일 수 있는 방식이다.
    기존 vue-router를 이미 사용해봤고 거의 비슷했기 때문에 비교적 수월하게 공식 문서를 읽을 수 있었다.
    - **Script, Style 등 리소스 파일에 대한 경로 이슈**
라우터 처리 시 주의할 점. Depth가 2 이상인 경로 또는 그러한 경로에서 새로고침 시, 스크립트 리소스에 대해 404 에러가 떨어짐을 확인했다. 이는 리소스 파일에 대한 경로가 잡혀있지 않아서 발생했다. 이를 'html-webpack-plugin' 를 통해 해결했다.


> 지금은 페이지가 별로 없고 페이지에서 페이지로 들어가는 깊이가 상당히 얕다고 생각합니다.
페이지가 많을수록 그리고 깊이가 깊을수록 더 가독성 좋고 효율적인 라우터를 구현할 수 있을지 고민하게 되네요!

2020-11-02 14:03 UTC, merged