[week6-assignment-1] 레스토랑 상세 페이지 구현하기
CodeSoom/week6-assignment-1 pull request #32
Opened 2020-10-29 15:12 UTC by goodzzong

## 과제 목표
- TDD로 기능 구현
- 커버리지 100% 달성
- About 페이지 구현
- Not found 페이지 구현
- 레스토랑 상세페이지 구현

2020-10-30 16:45 UTC, hannut91 requested changes

2020-10-30 16:45 UTC, hannut91 commented on src/App.test.jsx
> +    ));
반복적으로 사용되는 코드를 함수로 추출해서 재사용할 수 있을까요?

2020-10-30 16:45 UTC, hannut91 commented on src/App.test.jsx
> +  context('without path', () => {
`path`없이라기 보다 정의되어 있지 않은 path라고 하는건 어떨까요?

2020-10-30 16:45 UTC, hannut91 commented
현재 과제 진행사항을 알려주세요 ㅎㅎ 코드가 아니어도 괜찮습니다

2020-11-02 02:09 UTC, goodzzong commented
저번주는 개인적인 스트레스 때문에 집중을 못했네요 ㅠㅠ  아직 번아웃이긴 하지만....
저번주 과제지만 오늘까지 도전해보겠습니다 .

현재 상세 페이지에 대한 테스트 코드를 작성해야 하고 구현 해야 해요.
그리고 리팩토링 작업을 하려 합니다

2020-11-02 02:52 UTC, hannut91 commented
지난 과제를 계속 누적해서 하다보면 너무 많아져서 힘들 것 같아요 ㅎㅎ 다음 과제에도 어차피 이번 주 과제에 대한 내용이 포함되어 있으니 이번 주 과제에 집중하시는게 좋을 것 같아요. 과제풀이 영상은 꼭 보시구요 ㅎㅎ

2021-01-17 12:58 UTC, merged