즐거운 라우팅 🕸🕸🕸
CodeSoom/week6-assignment-1 pull request #34
Opened 2021-03-01 01:54 UTC by dodoongtak

2021-03-01 07:23 UTC, dodoongtak commented
## User Story

---

# 유저는...

---

### 모든 페이지에서...

- [ ]  Header를 볼 수 있다.
- [ ]  Header를 클릭하면 Home으로 이동한다.

### 초기 화면 Home 에서...

- [ ]  Home Title을 볼 수 있다.
- [ ]  About & Restaurants 링크를 볼 수 있다.

### About 링크를 클릭하면...

- [ ]  About 링크로 이동된다.
- [ ]  About 타이틀을 볼 수 있다.

### Restaurants 링크를 클릭하면...

- [ ]  Restaurants 링크로 이동된다.
- [이전 5주 차 유저 스토리 포함](https://github.com/CodeSoom/react-week5-assignment-1/pull/39#issuecomment-783061836)

### 식당 링크를 클릭하면

- [ ]  데이터 로딩 되기 전 까지 로딩 문구를 볼 수 있다.
- [ ]  클릭 한 식당 제목을 볼 수 있다.
- [ ]  해당 주소를 볼 수 있다.
- [ ]  해당 식당의 메뉴를 리스트로 볼 수 있다.

2021-03-01 11:55 UTC, dodoongtak commented
### 21.03.01 진행 상황:
- 풀이 과정까지 작업 완료.

### 21.03.02 진행 예정:
- restaurants/1 url 형식으로 식당 상세페이지 구현
- loading 문구 붙이기.

#### optional
- 상세페이지에서 식당 선택 페이지 뒤로가기 구현

2021-03-01 14:24 UTC, Kihyun92 requested changes
빠른 PR 좋습니다 💯

2021-03-01 14:24 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
`useEffect`에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 됩니다~

2021-03-01 14:24 UTC, Kihyun92 commented on src/index.jsx
> +        <p><Link to="/">헤더</Link></p>
누르면 메인페이지로 가는 헤더 영역을 추가 해주셨네요~

App 이 아닌 index에 위치시킨 이유가 있나요~?

2021-03-01 16:54 UTC, dodoongtak commented on src/RestaurantsPage.jsx
> +  });
아.... 기존 작성 되있는 코드여서, 소홀히 보지 않았네요 :) 빠른 수정 가보겠습니다 ㅎㅎ

2021-03-01 16:56 UTC, dodoongtak commented on src/index.jsx
> +        <p><Link to="/">헤더</Link></p>
![image](https://user-images.githubusercontent.com/77006427/109530710-5b78fb00-7afa-11eb-8da9-ccb2b35f292d.png)

워메 띨빵한 짓 하였네요. 헤더를 굳이 저기 상단에? 

허허 테스트와 같이 수정 해보겠습니다.

2021-03-02 11:59 UTC, dodoongtak commented
![image](https://user-images.githubusercontent.com/77006427/109645170-d1806f00-7b99-11eb-88f9-d9d927020017.png)

커버리지 100% 달성!

실제 수동으로 웹 구동 테스트 할 떄 (e2e X)
예상한대로 작동합니다

하지만... e2e는 fail.... 개선해보겠습니다 :) 

현재 이슈s: 
- NotFoundPage 제대로 작동 안함
- e2e 테스트 불통

2021-03-02 15:42 UTC, Kihyun92 requested changes
오오 벌써 동작하도록 해보셨군요 👍🏼  

남은 테스트들은 금방 해결하실 수 있을 것 같네요 :)

2021-03-02 15:42 UTC, Kihyun92 commented on src/App.jsx
> +  // 2. Restaurants Detail <- API (with restaurantId)
해당 부분들 구현이 끝났다면 주석은 제거해주세요~

2021-03-02 15:42 UTC, Kihyun92 commented on src/HomePage.jsx
> +        <li><Link to="/restaurants">Restaurants</Link></li>
간단하지만, 태그 간에 줄바꿈 처리해줘도 좋겠네요~

2021-03-02 15:42 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +  if (!restaurant.name) {
레스토랑 이름이 없는 경우에 로딩 화면을 노출해주셨군요 👍🏼 

```suggestion
  if (!restaurant) {
```

이 경우엔 그냥 레스토랑이 없는 경우로 처리해줘도 좋겠네요 :)

2021-03-02 15:42 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +            >
개인적으로 파라미터가 한개인 경우에는 줄바꿈처리를 해주지않는게 가독성이 더 좋은 것 같습니다 ㅎㅎ

본인만의 기준이 있다면 좋을 것 같아요~

2021-03-02 15:42 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +  const restaurant = useSelector(get('restaurant'));
다른 컴포넌트들 처럼 `container`, `presentation`과 같이 관심사를 분리해주는것도 좋을 것 같아요~

2021-03-02 15:42 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +    dispatch(setRestaurant({ id: restaurantId }));
id 라고만 받아서 넘겨주는 건 어떤가요?
```suggestion
  function handleClick(id) {
    dispatch(setRestaurant({ id }));
```

2021-03-02 15:42 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
>        {restaurants.map((restaurant) => (
구조분해할당으로 처리해줘도 좋겠네요~

2021-03-02 15:42 UTC, Kihyun92 commented on src/RestaurantsContainer.test.jsx
> +    ));
매 테스트마다 중복되는 로직이 있는 것 같습니다. 리팩터링 해보면 좋을 것 같네요 ㅎㅎ

2021-03-02 15:42 UTC, Kihyun92 commented on src/reducer.js
> +  },
```suggestion
  setRestaurant(state, { payload: { restaurant } }) {
    return {
      ...state,
      restaurant
    };
  },
```

이렇게 처리하는 것과 같지 않나요? 🤔

2021-03-02 16:26 UTC, dodoongtak commented on src/RestaurantDetailPage.jsx
> +  if (!restaurant.name) {
inititalState에서 retaurant를 빈 객체로 정의 해놨기 때문에, 
restaurant.name으로 처리해봤습니다 

빈 객체는 falsy가 아니기에 ! 로 처리하면 항상 falsy 가 되어 loading 문구가 나오지 않습니다. :) 

```
//reducer.js
const initialState = {
  regions: [],
  categories: [],
  restaurants: [],
  selectedRegion: null,
  selectedCategory: null,
  restaurant: {}, <- 빈 객체
};
```

2021-03-02 16:27 UTC, dodoongtak commented on src/RestaurantDetailPage.jsx
> +            >
줏대 썌게 잡아보겠습니다.

2021-03-02 16:43 UTC, dodoongtak commented on src/RestaurantsContainer.jsx
> +    dispatch(setRestaurant({ id: restaurantId }));
id로 코드를 간략하게 줄일 수 있겠지만, 
이게 어떤 의미를 가진 id인지 표시하고 싶어서 번거롭지만, restaurantId로 작성했습니다. 

추 후에 handleClick을 다시 들여다 볼 때, 생각을 한 번 더 하지 않아도 되는... 

readability > brevity 라는 기준을 잡고 진행해봤습니다. :) 

줏대가 아직 갈대 같아서, 저만의 기준점을 한번 정리해봐야겠네요 ㅎ

2021-03-02 16:51 UTC, dodoongtak commented on src/reducer.js
> +  },
ㅎㅎㅎ 이전에 initialState의 restaurant를 key 를 일일히 다 정의하고 key 하나하나당 일일히 value 값을 주어봤었습니다, (deep merge 고려 such as menuItems, reviews.... 어차피 새로운 배열로 replace 하는 것인데... 괜한 고려를...) 

다시 원상태로 복구할 때 신경을 못썼네요. 🔨🔨🔨🔨🔨🔨🔨🔨🔨🔨🔨🔨

2021-03-02 17:03 UTC, dodoongtak commented on src/RestaurantDetailPage.jsx
> +  const restaurant = useSelector(get('restaurant'));
넵! Hoxy나 싶었습니다. 

이전 base 코드들은 따로 분리를 안된 상태였어서 ㅎㅎ

진행하는 김에 base 코드였던 regionContainer/CategoryContainer/RestaurantContainer 도 전부 리팩토링 진행해볼께요. :) 

통일성! 통일성! 통일성!

2021-03-03 12:33 UTC, dodoongtak commented
## 현재까지 진행상황:
- e2e 테스트통과
- RestaurantPage 생성 (RestaurantsPage와 같은 관심사, presenter와 container분리)
- 해당 restaurant url로 접속 시 useEffect를 활용 loadRestaurant 호출
- HomePage로 갈 시 현재 state를 initialState로 초기화 해줌

## 멍청했던 짓
- HomePage에서 초기화를 시켜주면 되는 걸, Header에서 헤더를 클릭할 때 초기화를 시켜 주는 작업을 완료하고 깨달았습니다, 아 굳이 이렇게 할 필요가 없는데... ㅎㅎㅎㅎㅎㅎㅎㅎ 머리가 나쁘면 몸이 고생 ㅠㅠㅠ

## 질문: useParams 테스팅 하는 방도를 알려 주실 수 있을까요? 
관련 된 테스팅을 공식문서 및 무한구글링으로 찾아봤지만, 제대로 된 resource를 찾지 못했습니다. 

다행이도 [이 글](https://tomalexhughes.com/blog/testing-components-that-use-react-router-hooks)을 참고하여, useParams 자체를 mocking 해봤지만, 완벽히 믿을 수있는 테스트 작성은 아니라고 생각 돼요. 

글 하단 파트에 spyOn을 활용해 fetch된 data까지 비동기 테스트를 진행하는데, 
저희는 redux thunk를 사용하기에 spyOn을 따로 활용할려면 
액션 구조 자체를 다 변경해야돼서, 
선뜻 건들 일 수가 없었습니다. 

useParams 말고 match를 통해서든지, props를 통해서든지, withRouter를 홀용해서 query string을 받을 수 있지만, 
useParams 테스팅을 제대로 해볼 수 있다면, 
작성 난이도가 높은 테스트에도 도전할수 있는 자신감을 가질 수 있을 거 같아 삽질하면서 시도 해보고 있어요.... ㅎㅎㅎㅎ

2021-03-03 15:15 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +  if (!restaurant.name) {
아하 빈 객체로 초기화 해주셨군요~ 제가 착각했네요 😅

2021-03-03 15:17 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +    dispatch(setRestaurant({ id: restaurantId }));
본인의 의도를 드러내는 이유라면 좋은 것 같습니다 👍🏼 👍🏼

2021-03-03 15:20 UTC, Kihyun92 commented on src/reducer.js
> +  },
저는 타입스크립트를 주로 사용하기 때문에 타입 인터페이스를 정의해주고 항상 초기화를 함께 해줍니다 😊

초기 상태값이 복잡해진다면 객체를 쪼개는 것도 가독성에 좋을 것 같네요 :)

```javascript
//예시
const initialRestaurant = {
    id: null,
    name: '',
    address: '',
    menuItems: [],
    reviews: [],
    information: '',
  };

const initialState = {
  regions: [],
  categories: [],
  restaurants: [],
  selectedRegion: null,
  selectedCategory: null,
  restaurant: initialRestaurant,
};
```

2021-03-03 15:45 UTC, Kihyun92 requested changes
useParams에 대한 테스트를 하기위해 여러 시도를 해보신게 정말 좋네요 👍🏼 👍🏼 

그리고 고민하신 부분에 공감합니다. 라우팅 관련된 테스트는 단위 테스트로는 mocking 해서 확인하는 방법 정도로 한계가 있는 것 같아요. useParams에 대해서 어떤 테스트를 해야 우리가 믿을 수 있을까요? 🤔

라우팅 테스트는 유저 사이드에서 이루어지는 부분이라 개인적으로 E2E 테스트로 대체하는 편이에요. ☺️

2021-03-03 15:45 UTC, Kihyun92 commented on src/App.jsx
> +      <main>
main 태그를 사용해보셨군요~ 이유가 있을까요?

2021-03-03 15:45 UTC, Kihyun92 commented on src/Restaurant.jsx
> +export default function Restaurant({ restaurant }) {
restaurant 객체를 구조분해할당 해줘도 좋을 것 같네요 :)

2021-03-03 15:45 UTC, Kihyun92 commented on src/RestaurantPage.jsx
> +    dispatch(loadRestaurant());
```suggestion
    dispatch(loadRestaurant({ id }));
```

`loadRestaurant`을 할때 id 를 넘겨주면 어떤가요?

2021-03-03 15:46 UTC, Kihyun92 commented
추가적으로 src 폴더 내에 파일들이 많아진 것 같아요~ 관심사와 역할에 맞게 폴더 구조를 나눠서 관리해보는 것도 좋을 것 같네요~

2021-03-03 22:25 UTC, dodoongtak commented on src/RestaurantPage.jsx
> +    dispatch(loadRestaurant());
원래는 loadRestaurant에 id ( restaurantId a.k.a query String ) 를 인자로 넘겨서 처리하는 방식을 고려해봤었는데, 

loadRestaurant에서 getState()를 활용하여, 현재 store의 상태를 참고 할 수 있게 했습니다. 

```
export function loadRestaurant() {
  return async (dispatch, getState) => {
    const {
      restaurant: {
        id: restaurantId,
      },
    } = getState(); <- 활용 부분 

    const restaurant = await fetchRestaurant({ restaurantId });

    dispatch(setRestaurant(restaurant));
  };
}
```


**"둘다 동작은 어차피 같은데, 그냥 넘겨도 되지 않음?"** 이라는 의문이 들 수 있다고 생각 할 수 있다고 합니다. 


앞서 언급 했듯이, loadRestaurant로 넘겨지는 인자에 대한 의존성을 낮추고, 
현재 갱신된 store의 state를 참조해서 활용하자라는게 제 의도였습니다. 

음... 이렇게 작성하게 되면 발생을 할 수 있는 문제가, 
store에 연결 된 component 중에 restaurant 를 주시하고 있다면, 두번 갱신되기 떄문에, 해당 컴포넌트의 특정 로직이 엉킬수도 있겠다고 생각이되네요. 

의존성을 낮춰주는 이점이 있는 반면, 에러를 발생시킬수도 있다는 단점도 있겠네요. 

tradeoff를 따지면... 후자가 영향이 더 크니 변경하는 것을 추천하실까요?

2021-03-04 12:12 UTC, dodoongtak commented
## 현재까지 진행상황: 
1. 지역/카테고리 별 문구 
- 지역과 카테고리를 선택해주세요.
- 지역을 선택해주세요. 
- 카테고리를 선택해주세요. 
- 해당 지역에 카테고리 식당은 없습니다. 

2. 상세페이지에서 선택으로 뒤로가기 링크
3. restaurants/askldjaskldj id 숫자가 아닌 경우 NotFoundPage로 이동

4. 각 파일 components/ redux / pages / utils 로 구분 
5. 각 테스트파일은 폴더 안에 __test__에 위치

## 개선해보고 싶은 것
1. 각 페이지 이동 시 index header meta 변경 

CSR 특정 상 SEO score가 현저히 떨어짐. Page 이동 시 meta data를 변경을 하고싶습니다.
추천 해주 실 수 있는 좋은 resource 있으면 공유 부탁드려요 :) 

2. 서버 요청 에러 핸들링
- api method 안에서 try/catch로 잡는게, fetchData를 연결하는 곳에서 핸들링. 

최근에 [이 영상을 ](https://youtu.be/o9JnT4sneAQ) 을 시청하고, 
에러핸들링은 그럼 어떻게 진행해봐야 될까 좀 더 고민 되는거같습니다. 더욱 더 미러로 ㅠㅠㅠㅠㅠ

2021-03-04 13:50 UTC, Kihyun92 requested changes
과제를 계속 개선해보려고 하시는게 너무 좋네요 💯 

테스트파일의 폴더명은 __tests__ 라고 해도 좋을 것 같네요~
그리고 우리가 `container-presentation` 관점에서 파일을 분리했으니까 container, presentation 폴더를 추가해봐도 좋을 것 같네요 :)

SEO는 저도 잘 알지 못해서 좀 더 찾아보고 공유드리겠습니다! 

개선해보고 싶은 사항들은 슬랙 채널에서 동료들과 의논해봐도 좋겠네요 ㅎㅎ

2021-03-04 13:50 UTC, Kihyun92 commented on src/pages/RestaurantPage/Restaurant.jsx
> +      </Link>
사실 이건 레스토랑스 페이지로 가기가 맞는 것 같기도하네요 ㅎㅎ 

다른 방법으론 useHistory를 사용해서 history 객체를 이용해보는 것도 있을 것 같군요 :)

- https://reactrouter.com/web/api/Hooks/usehistory

2021-03-04 13:50 UTC, Kihyun92 commented on src/pages/RestaurantsPage/RestaurantsContainer.jsx
> +  }
어떤 값을 선택했는지에 따라 화면에 보여주는 처리를 컨테이너에서 해주는게 좋을까요? 

Restaurants 컴포넌트에서 해도 괜찮겠다는 생각이 드네요 ㅎㅎ

그리고 상태에 따라 노출되어야하는 요구사항이 이렇다면 어쩔 수 없지만, 예외처리 로직들을 조금 단순화 할 순 없을까요? 🤔

2021-03-05 14:43 UTC, dodoongtak commented
s 를 붙였다고 ci가 통과가 안되네요.

다 통과가 돼있는 상태인데 ....
coverage 100%
lint 통
e2e 통과


!?!?!??!?!!??!?!!?!?

2021-03-05 14:45 UTC, Kihyun92 approved these changes
리뷰 드릴 부분이 없는 것 같네요! 이번주도 고생하셨습니다~ 😊

과제를 더 개선해보려고 하시는 모습이 너무 좋네요 💯 

오늘 자정~내일 오전 중으로 올라갈 문제 풀이 영상도 꼭 봐보시면 좋을 것 같네요ㅎㅎ

이번 과제를 통해 무엇을 배웠나요? 더 알고 싶은 부분이 있나요?

2021-03-05 14:50 UTC, Kihyun92 commented
> s 를 붙였다고 ci가 통과가 안되네요.
> 
> 다 통과가 돼있는 상태인데 ....
> coverage 100%
> lint 통
> e2e 통과
> 
> !?!?!??!?!!??!?!!?!?

다시 빌드 해보니 잘 되는것 같네요 ㅎㅎ 👍🏼

2021-03-08 12:34 UTC, merged