상세 페이지 구현 🍙 🍖
CodeSoom/week6-assignment-1 pull request #35
Opened 2021-03-01 07:00 UTC by SangHoonly

2021-03-01 12:43 UTC, moonkii requested changes
![TDD](https://user-images.githubusercontent.com/46776329/109498287-9a955500-7ad6-11eb-865c-490b8324ac5e.png)

전체적으로 잘 진행하고 있는 것 같아요!

다만 지금은 `RestaurantDetailPage` 가 테스트 코드는 없는데 너무 많이 구현되어 있는 것 같아요.

테스트 코드가 없으면 구현 코드가 나올수가 없어요. 테스트 코드(RED) 를 확인하기 위해 구현 코드(GREEN) 이 나오기 때문이죠.

그리고 테스트 파일명도 항상 일치시켜주면 좋을 것 같아요 ;)

2021-03-01 12:43 UTC, moonkii commented on src/About.test.jsx
> +test('About', () => {
혹시 `AboutPage` 에 대한 테스트가 아닌가요?

맞다면 파일명과 테스트대상에 대한 이름도 일치시켜줘야 할거에요!

2021-03-01 12:43 UTC, moonkii commented on src/App.jsx
> +        <Route path="/restaurants/:id" component={RestaurantDetailPage} />
페이지의 구현을 생각하면서 순서를 바꿔주면 좋을 것 같아요.

2021-03-01 12:43 UTC, moonkii commented on src/App.test.jsx
> +  it('renders the home page with path /', () => {
`path` 별로 `context` 로 나누어 주는건 어떨까요?

2021-03-01 12:43 UTC, moonkii commented on src/RestaurantDetailPage.jsx
> +  dispatch(loadRestaurant(id));
`loadRestaurant` 는 언제 호출이 필요하나요?

라이프 사이클을 잡아주면 좋을 것 같아요.

2021-03-01 12:43 UTC, moonkii commented on src/RestaurantDetailPage.jsx
> +  );
`RestaurantDetailPage` 도 `container` 컴포넌트를 가지고 있으면 `Page` 가 맡고 있는 역할을 나눌 수 있을 것 같아요.

2021-03-01 12:43 UTC, moonkii commented on src/RestaurantDetailPage.test.jsx
> +// });
TDD 를 제대로 하고 있다면 테스트 코드가 없이 `RestaurantDetailPage` 가 존재할 수가 없어요.

왜 이런 현상이 발생 했을까요?

2021-03-01 12:43 UTC, moonkii commented on src/RestaurantsPage.test.jsx
> +  expect(queryByText('한식')).not.toBeNull();
단순히 `test` 로 잡아서 테스트 코드를 작성하시면 코드를 읽는 입장에서는 이 내용들이 무엇인지 어떻게 구분할 수 있을까요?

2021-03-02 12:24 UTC, SangHoonly commented
두 가지 궁금한 점이 있습니다!
첫번째 궁금한 점은, url에 http://localhost:8080/restaurants/1를 입력하여 들어갈 시 첫번째 그림과 같이 404 not found 에러가 뜨지만, http://localhost:8080/restaurants를 통해 링크를 클릭하여 들어갈 시 두번째 그림처럼 문제없이 들어간다는 것입니다. 왜 첫번째 경우는 되지않고, 두번째 경우는 되는지 도통 모르겠습니다. 어디서 문제가 생긴 것일까요?

두번째 궁금한 점은, 두번째 그림에서 보면 resquest가 지속적으로 쌓이는 모습이 보입니다. 페이지가 계속 렌더링 되면서 loadRestaurant가 계속 불러와져서 생기는 현상인 것 같은데, useEffect로 처리하여도 문제가 해결되지 않습니다. 이는 또 어느 부분의 코드에서 생긴 문제인지 궁금합니다.(두 문제 다 온 종일 잡고있었는데, 어디서 문제가 생겼는지 갈피가 잡히지 않습니다.)

![Uploading 스크린샷 2021-03-02 오후 9.17.16.png…]()
![Uploading 스크린샷 2021-03-02 오후 9.17.56.png…]()

2021-03-02 12:32 UTC, SangHoonly commented on src/RestaurantDetailPage.jsx
> +  );
DetailContainer 컴포넌트로 분리하였습니다!

2021-03-02 12:32 UTC, SangHoonly commented on src/RestaurantDetailPage.jsx
> +  dispatch(loadRestaurant(id));
useEffect로 렌더링 후 실행되도록 처리하였습니다.

2021-03-02 12:33 UTC, SangHoonly commented on src/About.test.jsx
> +test('About', () => {
저의 미스테이크...

2021-03-02 12:38 UTC, SangHoonly commented
그리고 항상 하는 고민이지만, TDD를 할 시 진행 순서는 테스트 코드를 작성하는 red -> 컴포넌트 코드를 작성 green -> 리펙토링 단계가 됩니다. 익숙한 코드를 짤때는 머릿속으로 로직 및 테스트케이스들이 그려져 테스트 코드를 바로 작성할 수 있지만, 생소한 코드를 만나거나 로직의 감이 잡히지 않을때도 많고, 이럴때는 함수의 형태가 머릿속에 그려질 수 조차 없습니다. 이러한 경우는, 어떻게 테스트 케이스를 먼저 작성할 수 있을까요??

2021-03-02 12:39 UTC, SangHoonly commented on src/RestaurantsPage.test.jsx
> +  expect(queryByText('한식')).not.toBeNull();
추후 테스트 케이스들을 더 추가 및 분리하겠습니다!

2021-03-02 15:18 UTC, moonkii reviewed
> index.html에서, main.js를 /main.js로 바꾸니까 변경 => 왜 이렇게 바뀌면 해결 되는건가요?????

base path 가 다르기 때문에 발생하는 에러일거에요.
`index.html` 쪽 `main.js` 에서 `/` 를 추가 함에 따라 개발자도구에서 Network 를 살펴보시면 요청하는 경로가 다르게 잡히시는걸 확인하실 수 있을거에요.
제 기억으로는 `webpack.config.js` 에서도 옵션을 주면 해결이 가능했던 걸로 기억이 나네요.

> 두번째 궁금한 점은, 두번째 그림에서 보면 resquest가 지속적으로 쌓이는 모습이 보입니다.

resquest 가 어떤 상황에서 계속 쌓인다는건가요??
추측이지만 useEffect 사용법을 한 번 찾아보시면 좋을 것 같아요. useEffect 는 두번째 인자를 받을 수 있어요.

> 어떻게 테스트 케이스를 먼저 작성할 수 있을까요??

TDD 할 때 주의해야할 점은 익숙해지면 점점 작업 덩어리가 커진다는거에요.
기존에 container 컴포넌트로 이렇게 저렇게 만들면 됐고, 대충 이렇게 저렇게 컴포넌트로 분리되고 당장 reducer에 추가하고 등등 처음부터 리팩토링 된 상태를 생각하며 시작하는 경우가 많아요.
내가 할 수 있는 한 코드를 작고 간단하게 만드는 것 부터 시작해 보세요. 당장 눈에 보이는 것들만 단순히 render 되도록 만들어 보고, 그다음에 무엇이 필요할까 추가될 기능을 하나씩 생각하면서 테스트 케이스를 추가해 나가면 조금 더 수월할 거에요.

과제를 시작할 때 어떻게 시작하는지 과정을 스스로 설명해볼 수 있을까요?

2021-03-02 15:18 UTC, moonkii commented on index.html
> +    <script src="/main.js"></script>
👍

2021-03-02 15:18 UTC, moonkii commented on src/DetailContainer.jsx
> +export default function DetailContainer({ restaurant }) {
컨테이너 컴포넌트의 역할이 무엇일까요?

지금 상태로만 봐선 페이지 컴포넌트가 과도한 책임을 가지고 있을 확률이 높아 보여요.

2021-03-02 15:18 UTC, moonkii commented on src/DetailPage.test.jsx
> +  expect(dispatch).toBeCalled();
따로 테스트에 대한 설명이 없으면 왜 시작하자 마자 `dispatch` 를 하는지 알 수 없어요.

테스트코드는 설명서와 같아요. 테스트 코드만 보더라도 중요한 부분은 다 이해가 되도록 해야해요.

2021-03-02 15:18 UTC, moonkii commented on src/MenuItems.test.jsx
> +      expect(queryByText(/맥도날드/)).toBeNull();
메뉴가 없을 때는 따로 메뉴가 없다고 직접적으로 알려주는건 어떨까요? 🤔

2021-03-02 15:18 UTC, moonkii commented on src/NotFoundPage.jsx
> +export default function NotFoundPage() {
간단한 페이지지만 테스트 코드가 있으면 좋겠죠?

TDD 의 정의는 테스트 코드를 먼저 작성한다에요!

2021-03-02 15:18 UTC, moonkii commented on src/actions.test.js
> +    it('runs setRestaurant with loaded restaurant data', async () => {
테스트에 대한 설명이 이해하기 어려운 것 같아요.

2021-03-02 19:09 UTC, SangHoonly commented on src/DetailContainer.jsx
> +export default function DetailContainer({ restaurant }) {
말씀해주신 내용 참고하여 페이지 컴포넌트, 컨테이너 컴포넌트, 기능 컴포넌트로 나누고 각자의 기능들을 분리했습니다!

2021-03-02 19:10 UTC, SangHoonly commented on src/DetailPage.test.jsx
> +  expect(dispatch).toBeCalled();
참고하여 describe-it 문으로 바꾸고, 설명을 추가하였습니다!

2021-03-02 19:37 UTC, SangHoonly commented on src/MenuItems.test.jsx
> +      expect(queryByText(/맥도날드/)).toBeNull();
값이 없을 시 "값이 없어요!"가 나오는지를 테스트하도록 코드를 수정하였습니다!

2021-03-02 19:38 UTC, SangHoonly commented on src/NotFoundPage.jsx
> +export default function NotFoundPage() {
저의 미스테이크...ㅠ

2021-03-02 19:49 UTC, SangHoonly commented on src/NotFoundPage.jsx
> +export default function NotFoundPage() {
![my mistake](https://user-images.githubusercontent.com/54464320/109706004-c3534280-7bdb-11eb-9b5b-21f42a6dd206.png)

2021-03-02 19:49 UTC, SangHoonly commented on src/NotFoundPage.jsx
> +export default function NotFoundPage() {
저의 미스테이크...

2021-03-02 20:04 UTC, SangHoonly commented on src/actions.test.js
> +    it('runs setRestaurant with loaded restaurant data', async () => {
이름을 수정하였습니다!

2021-03-03 04:31 UTC, dodoongtak commented on index.html
> +    <script src="/main.js"></script>
![image](https://user-images.githubusercontent.com/77006427/109752890-92e3c680-7c24-11eb-97b4-9b2d02be3c42.png)

webpack.config.js 에서 첨부된 사진의 option들을 추가해서 해결해봤습니다!

2021-03-03 11:11 UTC, SangHoonly commented on index.html
> +    <script src="/main.js"></script>
ㅋㅋㅋㅋㅋㅋ 형탁님 진실의 방으로...

2021-03-03 12:52 UTC, moonkii commented on index.html
> +    <script src="/main.js"></script>
@dodoongtak, @SangHoonly  해당 이슈는 다른 수강생 분들도 많이 겪으시는 것 같고, 아마 모르고 지나가시는 분들도 많을 것 같아서 슬랙에서 한 번 공유하면 좋을 것 같아요!

2021-03-03 12:53 UTC, moonkii commented on src/App.test.jsx
> +  beforeEach(() => {
mock clear 를 해주면 좋겠죠?

2021-03-03 12:56 UTC, moonkii commented on src/MenuItems.jsx
> +    </ul>
`값이 없어요!` 도 p 태그라도 감싸주면 좋을 것 같아요.

그리고 ul 안에 있는게 의미상으로 맞을까요? 🤔

2021-03-03 15:17 UTC, SangHoonly commented on src/MenuItems.jsx
> +    </ul>
'값이 없어요!' 가 ul안에 있는 건 의미상 맞는 코드가 아닌 것 같아서, menuItems가 있을 시에 존재하도록 수정하였습니다!

2021-03-04 14:56 UTC, moonkii commented on src/DetailContainer.test.jsx
> +    const { queryByText } = render((<DetailContainer />));
한 줄 일 때는 괄호를 한번만 감싸줘도 돼요.

2021-03-04 14:58 UTC, moonkii commented on src/MenuItems.jsx
> +      : <p>값이 없어요!</p>
태그는 `()` 로 감싸주는게 좋아요.

2021-03-04 15:23 UTC, SangHoonly commented on src/DetailContainer.test.jsx
> +    const { queryByText } = render((<DetailContainer />));
이번 과제에서 render 메서드의 option에 값을 줄 일도 없고 해서 render메서드의 괄호들을 제거하였습니다!

2021-03-06 05:07 UTC, moonkii commented on src/CategoriesContainer.test.jsx
> +      );
괄호를 2개로 감싸는 이유는 줄바꿈할 때 `,` 를 없애기 위해서에요.

간단한 경우에는 한 줄로 해주셔도 될 것 같아요 ;)

2021-03-06 05:12 UTC, moonkii commented on src/DetailPage.jsx
> +  }, [id]);
`[id]` 에서 `id` 는 빼주셔도 될 것 같아요.

`useEffect` 에서 빈 배열을 넣어주면 어떻게되는지 찾아보시면 좋을 것 같아요!

2021-03-06 05:15 UTC, moonkii commented
라우터도 잘 사용하셨고 테스트도 잘 작성하셨어요 👏 👏 👏 

괄호 부분만 다시  코드 정리해주면 좋을 것 같아요.

회고 작성하시면 merge 하도록  하겠습니다!

2021-03-08 12:56 UTC, moonkii approved these changes

2021-03-08 12:56 UTC, merged