라우터를 활용해서 레스토랑 App 확장하기🤔
CodeSoom/week6-assignment-1 pull request #36
Opened 2021-03-01 10:00 UTC by shinhyogeun

일단은 PR를 보냅니다! 이번주도 잘 부탁드립니다~!😊

2021-03-01 12:00 UTC, shinhyogeun commented
라우터에 대해서 공부하면서 과제를 해 나아가고 있습니다! 질문이 있습니다!!

1. **어떻게 하면 Link 태그를 test할 수 있을까요?**

버튼을 클릭하면 handleClick함수가 실행된다는 것을 test는 자주해왔었습니다.

하지만 Link태그에서 클릭하면 pathName이 바뀐다는 것을 테스트하려면 이것은 

테스트가 파일독립적으로 행해지기 때문에 할 수가 없다고 생각합니다. 이럴 경우에는 어떻게 test하는 것이 좋을까요?

Link를 누르는 행위가 일어났을 때는 test를 해야한다고 생각하기때문에 지금 고민중에 있습니다! 

(일단은 Link가 a태그로 test할 때 변환되는 것 같아서 a 태그의 href속성값으로 검증을 하고 있습니다.)

조언 부탁드립니다😊

2. **App을 render하는 것을 다음과 같은 함수로 만드니 오류가 나는 것같습니다.. render에 key속성이 필요한 것일까요?**
```
function renderAppWithPath({ path }) {
  return render(
    <MemoryRouter initialEntries={[path]}>
      <App />
    </MemoryRouter>,
  );
}
```
<img width="456" alt="스크린샷 2021-03-01 오후 8 58 20" src="https://user-images.githubusercontent.com/52554235/109494161-db8a6b00-7ad0-11eb-92f9-29c4526b1182.png">

2021-03-01 13:04 UTC, moonkii requested changes
![image](https://user-images.githubusercontent.com/46776329/109500306-6d967180-7ad9-11eb-94ba-5574a0afb293.png)

> 어떻게 하면 Link 태그를 test할 수 있을까요?

지금 테스트한 방식도 괜찮은 것 같아요.
`Link` 를 누르는 행위를 테스트 하고 싶은 이유가 있나요?

버튼을 클릭했을 때 handleClick 함수를 테스트한건 버튼을 클릭 하면 실제로 handleClick 함수가 호출되기 때문에 그걸 확인하고 싶어서 테스트한거였을 거에요. 

> 2. App을 render하는 것을 다음과 같은 함수로 만드니 오류가 나는 것같습니다.. render에 key속성이 필요한 것일까요?

이미 Jest 에서 친절하게 어느 테스트에서 어떤 부분이 깨지는지 알려주고 있어요.
만약에 저라면 `HomePage를 그린다` 테스트에 가서 확인해보고 문제가 없으면 내부 render 된 구현을 살펴볼 것 같아요.
참고로 List 에서 list item 에는 key 를 넣어줘야해요. 항상 기억하시길..! ;)

2021-03-01 13:04 UTC, moonkii commented on src/App.test.jsx
> +function renderAppWithPath({ path }) {
매개변수로 `path` 가 들어가기 때문에 함수명을 `renderApp` 만 해주셔도 충분이 이해가 될 것 같아요!

2021-03-01 13:04 UTC, moonkii commented on src/App.test.jsx
> +  it('HomePage를 그린다.', () => {
`path` 에 따라 달라지는 케이스기 때문에 `context` 를 사용하여 명시적으로 드러내주면 어떨까요?

2021-03-01 13:04 UTC, moonkii commented on src/RestaurantsPage.test.jsx
> +test('RestaurantsPage', () => {
`RestaurantsPage` 만 `test` 로 작성해준 이유가 있을까요?

`dispatch` 도 `called` 되고 목록들도 나오는 것 같은데 테스트 내용을 추가해주면 어떨까요?

2021-03-02 08:51 UTC, shinhyogeun commented on src/App.test.jsx
> +function renderAppWithPath({ path }) {
넵 알겠습니다!👍

2021-03-02 08:51 UTC, shinhyogeun commented on src/App.test.jsx
> +  it('HomePage를 그린다.', () => {
넵 수정하겟습니다!

2021-03-02 08:52 UTC, shinhyogeun commented on src/RestaurantsPage.test.jsx
> +test('RestaurantsPage', () => {
수정하도록 하겠습니다!😊

2021-03-02 12:00 UTC, shinhyogeun commented
어제의 2번째 질문

> App을 render하는 것을 다음과 같은 함수로 만드니 오류가 나는 것같습니다.. render에 key속성이 필요한 것일까요?

이부분은 단순 오타때문에 일어났던 오류였습니다..😭 아샬님도 key를 작성하지 않았는데 왜 나만 이것때문에 오류가 날까 생각을 해보

던 와중에 찾았습니다. 그래도 key를 붙이는 조언 감사합니다!


오늘은 정말 어렵네요.. 식당목록의 각각을 Link로 감싸서 받는 쪽에서 useParams을 쓰려고 했습니다..ㅠㅠ 그런데 지금 오류가 나서 

일단은 PR을 보냅니다!! 무엇인가가 잘못된 느낌인데 천천히 파악해보려고합니다!🤔🤔

2021-03-02 14:40 UTC, moonkii reviewed
저도 똑같은 에러로 고민을 많이 했던 기억이나는데, `webpack.config.js` 쪽을 알아보시면 도움이 되실거에요!

2021-03-02 14:40 UTC, moonkii commented on src/App.jsx
> +        <Route path="/Restaurants/:id" component={RestaurantsDetailContainer} />
`path`의 첫글자를 대문자로 해준 이유가 있나요?

2021-03-02 14:40 UTC, moonkii commented on src/App.jsx
> +import RestaurantsDetailContainer from './RestaurantsDetailContainer';
라우터는 페이지를 연결해주는 역할을 해요.

상세페이지만 `Container` 인 이유가 있을까요?

2021-03-02 14:40 UTC, moonkii commented on src/HomePage.test.jsx
> +      <MemoryRouter>
`MemoryRouter` 를 붙여준 이유가 있을까요?

2021-03-02 14:40 UTC, moonkii commented on src/actions.test.js
> +      store = mockStore({});
![image](https://user-images.githubusercontent.com/46776329/109660170-e665fe00-7bab-11eb-91f2-01cc8c94a763.png)

제한 조건을 지켜주세요!

2021-03-02 14:40 UTC, moonkii commented on src/actions.test.js
> +    it('특정 액션을 실행한다.', async () => {
특정 액션이라고 하면 어떤 액션이 알기 어려울 것 같아요.

2021-03-03 06:38 UTC, shinhyogeun commented on src/App.jsx
> +        <Route path="/Restaurants/:id" component={RestaurantsDetailContainer} />
path를 모두 수정했습니다!! e2e테스트에서 걸렸네요 하하😭

2021-03-03 06:40 UTC, shinhyogeun commented on src/HomePage.test.jsx
> +      <MemoryRouter>
흠.. HomePage안에는 Link태그가 있어서 그것을 테스트할 때 Router바깥에서 Link가 존재한다고 해서 추가해주었습니다!

어떤 방향성을 원하시는지 여쭤봐도 괜찮을까요??🤔

2021-03-03 06:50 UTC, shinhyogeun commented on src/App.jsx
> +import RestaurantsDetailContainer from './RestaurantsDetailContainer';
여기 부분을 고민했습니다.
**RestaurantsDetailPage 속에 RestaurantsDetailContainer 속에 RestaurantsDetail** 형태로 할 지
**RestaurantsDetailPage 속에 RestaurantsDetail** 형태로 할지 고민이었습니다.

만약에 첫번째 것 처럼 3단으로 한다면 Page는 그냥 Container를 보여주는 것 뿐이라서 저는 Container를 없에서 2번째 형식으로 했습니다. Page단에서도 RestaurantsPage에서 처럼 리덕스와 소통할 수 있으니 크게 어색하다는 생각은 없었습니다.

이런 경우에는 어떻게 하는 것이 좋을까요? 다른 파일들처럼 3단으로 통일해서 만드는 것이 좋을까요..? 🤔

2021-03-03 08:02 UTC, shinhyogeun commented on src/actions.test.js
> +      store = mockStore({});
넵 수정하겠습니다!!!😊

2021-03-03 08:04 UTC, shinhyogeun commented on src/actions.test.js
> +    it('특정 액션을 실행한다.', async () => {
**loadRestaurantsDetail 액션을 실행한다.**로 수정했습니다!!🤔

2021-03-03 11:35 UTC, shinhyogeun commented
일단은 통과했지만 아직 수정해야할 부분이 있습니다.

**Loading화면 구현이 미숙합니다.**

```
if (!restaurantsDetail.name) {
     return <h2>Loading</h2>;
}
```

초기에 `state.restaurantsDetail`값이 없을 때만 Loading화면이 뜹니다. 
즉 처음에 마녀주방이라는 음식점에 들어가면 `state.restaurantsDetail`값이 {}이므로 Loading화면이 뜹니다. 하지만 그 후에 중식당에 들어가면
`state.restaurantsDetail`이 있으니 이제는 Loading화면이 뜨지 않습니다. 
처음에 마녀주방에 들어간 흔적때문에 마녀주방 정보가 떴다가 로드가 완료되면 바뀝니다.😭

그래서 디테일 페이지에서 나갈때 `state.restaurantsDetai`l을 {}로 만드는 방법도 있지만.. 
**굳이..?**라는 생각도 들고 무엇인가 더 좋은 방법이 있지 않을까 생각중에 있습니다!!🤔

위의 코드가 조금 이상하다는 생각도 드는데 어떤 방법이 괜찮을까요..?

2021-03-03 13:01 UTC, moonkii commented on src/HomePage.test.jsx
> +      <MemoryRouter>
방향성 보다는 어떤 의도에서 붙여줬을까 물어본거에요!

2021-03-03 13:03 UTC, moonkii commented on src/App.jsx
> +import RestaurantsDetailContainer from './RestaurantsDetailContainer';
Page 의 역할은 무엇 일까요?

왜 나누는지 부터 고민을 해보면 좋을 것 같아요.

다른 컴포넌트들의 경우 3단계로 구성한 이유가 있을거에요.
상세페이지도 비슷한 이유를 가질 확률이 높을 것 같아요.

2021-03-03 13:04 UTC, moonkii commented on src/App.jsx
> +        <Route path="/restaurants/:id" component={RestaurantsDetailPage} />
순서를 바꿔서 path 가 비슷한 것들끼리 묶어보여주면 좋을 것 같아요.

2021-03-03 13:17 UTC, moonkii reviewed
`loadRestaurant` 에서 fetch 하기 전에 dispatch 로 `state.restaurantsDetail` 을 `{}` 로 만들어 주면 되지 않을까요?

2021-03-03 13:17 UTC, moonkii commented on src/App.jsx
> +        <Route path="/restaurants/:id" component={RestaurantsDetailPage} />
순서를 바꿔서 path 가 비슷한 것들끼리 묶어보여주면 좋을 것 같아요.

2021-03-03 13:17 UTC, moonkii commented on src/RestaurantsDetail.jsx
> +    return <h2>Loading</h2>;
`return ( ... );` 이 기본형태에요!

2021-03-03 13:17 UTC, moonkii commented on src/RestaurantsDetailPage.test.jsx
> +  it('화면이 로딩될 때 자세한 레스토랑 정보를 불러와 state를 업데이트한다.', () => {
`레스토랑 정보를 불러온다` 정도면 충분할 것 같아요.

`화면이 로딩될 때` 라고 상황을 나눠야한다면 `context` 를 사용하는게 맞을 것 같아요.

`state` 를 업데이트 하는건 UI 컴포넌트의 관심사가 아니에요.

2021-03-04 06:51 UTC, shinhyogeun commented on src/App.jsx
> +        <Route path="/restaurants/:id" component={RestaurantsDetailPage} />
네 알겠습니다!👍

2021-03-04 07:47 UTC, shinhyogeun commented on src/RestaurantsDetail.jsx
> +    return <h2>Loading</h2>;
넵 알겠습니다!!

2021-03-04 07:50 UTC, shinhyogeun commented
말씀해주신 방법대로 Loading을 자연스럽게 처리했습니다!! 감사합니다👍👍

Page와 Container의 관계를 생각해보았고 Page가 Load될때 해야할 일과 그 로드가 끝나면 업데이트된 state와의 소통이 

또 필요한 Container라는 명확한 Page와 Container의 관계를 생각할 수 있었습니다!!

2021-03-05 15:07 UTC, moonkii commented
요구 사항에 맞게 라우터까지 잘 사용하셔서 만드신 것 같아요 👏 👏 👏 
따로 `id` 값에 대한 예외처리도 해주려고 생각한 점이 좋은 것 같아요.
회고 작성해주시면 merge 하도록 하겠습니다!


> 1. 파일을 폴더별로 정리해봤습니다. 

test 폴더나 container 폴더로 따로 정리한 이유가 있나요??
(틀렸다가 아니에요. 폴더를 나누더라도 어떠한 이유에서 했느냐가 중요해서 물어 보는거에요.)

> 오늘 많이 찾아봤지만 궁금한 것이 있습니다..
> 
> https://testing-library.com/docs/example-react-router/#reducing-boilerplate
> 위의 링크는 리액트 라우터를 test하는 법을 알려주는 공식문서입니다.
> 위의 문서를 이해하려고 많은 시간을 보냈는데 `createMemoryHistory()`의 역할이 무엇인지 모르겠습니다..ㅠㅠ
> createMemoryHistory가 말그대로 새로운 MemoryRouter전용 History를 만들어주는 역할을 하는 것인가요??
> 저는 test할 때 `createMemoryHistory`를 사용하지 않고 했는데 저 `createMemoryHistory`이 어떤 역할을 하는지 모르겠습니다😭

React Router 에서 `match` 처럼  `history` object 를 컴포넌트에서 매개변수로 받을 수 있어요.
저 같은 경우 history 를 사용하는 경우 테스트 코드에서 따로 mock 해줘서 처리했었는데, `createtMemoryHistory` 는  테스트용으로 쓸 수 있도록 따로 memory history 를 생성해주는 함수 같네요. 지금은 사용할 일이 없을 것 같아요.

참고:
- https://reactrouter.com/web/api/history

2021-03-06 11:20 UTC, shinhyogeun commented
1주일동안 코드리뷰 감사합니다!👍

> test 폴더나 container 폴더로 따로 정리한 이유가 있나요??

일단은 Page와 Container 그리고 Component가 3단으로 되어 있기 때문에 분리하는 것이 나중에 파일이 많아졌을 경우 관리가 쉽다고 생각했습니다. 또한 각각의 파일은 test파일이 있는데 그것도 따로 관리한다면 관리가 수월한 측면을 고려해서 이렇게 나누었습니다!

2021-03-07 14:35 UTC, moonkii approved these changes

2021-03-07 14:35 UTC, merged