Router
CodeSoom/week6-assignment-1 pull request #38
Opened 2021-03-01 12:22 UTC by jjkim01

연휴 잘 보내셨나요?
고생하십니다. 질문드리겠습니다!

1. MemoryRouter 사용에 대한 설명이 강의에서 좀 부족하다고 느꼈습니다.
    찾아보니 test 환경에서 용이하다고 하는데 추가 설명을 부탁드려도 될까요?

2. BrowserRouter를 App에서 index로 옮긴 이유가 강의에서 부족하다고 생각했습니다.
    어떤 이유인가요 ??

3. RestaurantsDetailPage.test.jsx에 주석을 달았는데, useLocation()를 test 할 수 있는 방법이 어떤게 있나요 ??

4. RestaurantsContainer.jsx 에서,
    1 식당 이름을 클릭
    2 클릭한 식당의 id를 사용해서 fetchRestaurantDetail 요청
    3 fetchRestaurantDetail를 통해 setRestaurantDetail 가 호출되어 식당 Detail 상태를 저장함
    4 Link to 의 state에 3번에서 받아온 restaurantDetail.name 를 넘김

을 하고싶은데.. 초기값이 없어서? 지역, 카테고리 목록 뜰 때 이미 undefined 오류가 나네요.

클릭한 식당의 id를 사용해서 fetchRestaurantDetail 요청하는 부분을 어떻게 해결하면 좋을까요 ??

감사합니다 ~~

2021-03-01 14:14 UTC, Kihyun92 requested changes
오 첫날 PR인데 정말 많은 작업을 해보신 것 같아요 👍🏼

남겨주신 질문들을 보니 강의 영상들을 잘 보시고 많은 고민을 해보신 것 같습니다 ㅎㅎ 

간단하게 답변을 남겨봤습니다. 추가로 의논이 필요한 부분이 있으면 말씀주세요~

> 1. MemoryRouter 사용에 대한 설명이 강의에서 좀 부족하다고 느꼈습니다.
>    찾아보니 test 환경에서 용이하다고 하는데 추가 설명을 부탁드려도 될까요?

실재로 주소가 존재하지 않는 라우터입니다. 우리가 라우터를 테스트할 경우엔, BrowserRouter로 감싸줘야 하는데요. 
유닛 테스트의 경우엔 실제 브라우저 환경에서하는게 아니기때문에, `MemoryRouter`를 사용합니다 ㅎㅎ
- https://reactrouter.com/web/api/MemoryRouter

> 2. BrowserRouter를 App에서 index로 옮긴 이유가 강의에서 부족하다고 생각했습니다.
>    어떤 이유인가요 ??
두번째 강의영상 18분 정도에 설명을 추가로 해주시는 부분이 있어요. App.test.jsx에서 라우터를 직접 조작하는 등 테스트를 쉽게 하기 위해 기존 App에서 index로 옮겼다고 보시면 될 것 같아요~

> 3. RestaurantsDetailPage.test.jsx에 주석을 달았는데, useLocation()를 test 할 수 있는 방법이 어떤게 있나요 ??

useLocation을 왜 테스트 해야하나요? `RestaurantsContainer.jsx`에 커맨트 드린대로 상태 정보를 useLocation으로 넘겨주거나 받지 않는다면 어떨까요? 단순히 id 정보만 넘겨주고, 상세 컴포넌트에선 useParams와 같은 함수를 이용해 id 값만 받아오는거죠.

- https://reactrouter.com/web/api/Hooks/useparams

> 4. RestaurantsContainer.jsx 에서,
>    1 식당 이름을 클릭
>    2 클릭한 식당의 id를 사용해서 fetchRestaurantDetail 요청
>    3 fetchRestaurantDetail를 통해 setRestaurantDetail 가 호출되어 식당 Detail 상태를 저장함
>    4 Link to 의 state에 3번에서 받아온 restaurantDetail.name 를 넘김
> 
> 을 하고싶은데.. 초기값이 없어서? 지역, 카테고리 목록 뜰 때 이미 undefined 오류가 나네요.
> 
> 클릭한 식당의 id를 사용해서 fetchRestaurantDetail 요청하는 부분을 어떻게 해결하면 좋을까요 ??

2021-03-01 14:14 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/restaurant/:id" component={RestaurantsDetailPage} />
`restaurants/${restaurant.id}`와 같이 하는게 맞습니다.

`REST API`에서 `URL`을 표현할 땐 `restaurants`와 같이 `collection(집합)`을 먼저 표현하고 그 집합 중에 특정한 1개는 `id(식별자)`로 구분하죠.

2021-03-01 14:14 UTC, Kihyun92 commented on src/RegionsContainer.jsx
> +    dispatch(loadRestaurantDetail());
레스토랑 정보를 지역 클릭시마다 dispatch 해줘야하나요?

2021-03-01 14:14 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +              menuItems: restaurantDetail.menuItems || null,
레스토랑 정보를 미리 받아와서 이 state 를 통해 레스토랑 정보들을 넘겨주도록 처리해보셨네요~

로직이 복잡해보이고, 이 페이지에서 너무 많은 기능을 하고 있는 것 같습니다.

레스토랑의 정보를 라우터를 통해 관리하는 것도 좋지만, 지금처럼 레스토랑 id만 넘겨주고, 상세페이지로 이동 후에 레스토랑 정보를 받아와서 화면에 그려주는 건 어떨까요?

2021-03-01 14:14 UTC, Kihyun92 commented on src/RestaurantsDetailPage.jsx
> +  const { name, address, menuItems } = useLocation().state;
redux를 사용해서 레스토랑 정보를 가져오는건 어떨까요?

2021-03-02 11:32 UTC, jjkim01 commented on src/App.jsx
> +        <Route path="/restaurant/:id" component={RestaurantsDetailPage} />
감사합니다.
다만 제가 이해하기에 내용이 좀 중의적이라 다시 질문드립니다.

1. 이렇게 변경해야한다.
`<Route path="/restaurants/:id" component={RestaurantsPage} />`
그럼 인자가 들어왔을 때 component={RestaurantsDetailPage}는 어떻게 호출하게 하나요 ??
'react route multi component' 같은 검색어로 해봐도 원하는 내용이 잘 안 나오네요 ..

2. 이거다
`<Route path="/restaurants" component={RestaurantsPage} />`
`<Route path="/restaurants/:id" component={RestaurantsDetailPage} />`
제가 이해하기에 가장 맞는 방법인 것 같습니다. s추가하기..

3. 이거다
`<Route path="/restaurants" component={RestaurantsPage} />`
`<Route path="/restaurants/${restaurant.id}" component={RestaurantsDetailPage} />`
이건 템플릿 문자열 에러가 나오더라구요.. 백틱으로 감싸도 그렇던데 이 방법은 아니겠죠 ?..

2021-03-02 11:32 UTC, jjkim01 commented on src/RestaurantsContainer.jsx
> +              menuItems: restaurantDetail.menuItems || null,
좋은 것 같습니다. 적용해보겠습니다~

2021-03-02 11:34 UTC, jjkim01 commented on src/RestaurantsDetailPage.jsx
> +  const { name, address, menuItems } = useLocation().state;
`useLocation()`을 삭제하고 `useParams();` 를 사용했습니다.

state를 가져오는 부분은 `useSelector(get('restaurantDetail'));`
를 적용하기로 했습니다.

이거 말씀해주신 게 맞지요??
감사합니다.

2021-03-02 11:34 UTC, jjkim01 commented on src/RegionsContainer.jsx
> +    dispatch(loadRestaurantDetail());
이걸 어느 시점에 호출해야할지 사실 가장 고민입니다.
Detail 페이지가 열린 시점에 dispatch를 넣으니까 무한 호출되더라구요.
Detail 페이지에서 load 버튼같은걸 만들 수도 없고 .. 고민중입니다!!

2021-03-02 11:57 UTC, jjkim01 commented on src/RegionsContainer.jsx
> +    dispatch(loadRestaurantDetail());
그리고
`dispatch(loadRestaurantDetail(restaurantId));`
이렇게 인자로 id 주려는데 이 생각은 맞지요 ??

2021-03-02 12:06 UTC, jjkim01 commented on src/RegionsContainer.jsx
> +    dispatch(loadRestaurantDetail());
아! 자답입니다.

식당 목록을 클릭했을 때 li에 onClick을 줘서 호출하도록 했습니다.
감사합니다.

2021-03-02 12:19 UTC, jjkim01 commented on src/RestaurantsDetailPage.jsx
> +  const { name, address, menuItems } = useLocation().state;
추가 질문있습니다~

RestaurantsDetailPage.jsx 에서

`const restaurantDetail = useSelector(get('restaurantDetail'));`
`console.log(restaurantDetail);
로 값을 받아오고,

```js
return (
    <div>
      <h2>{id}</h2>
      <h4>
        주소:
        {restaurantDetail.address}
      </h4>
...
```
이런식으로 화면에 뿌려줍니다.

근데 한번 undefined 뜨고나서 console.log 에는 값이 잘 표시되는데,
화면에는 
`Cannot read property 'address' of undefined`
가 나옵니다.

그래서 Detail페이지가 뜨기 전
`await dispatch(loadRestaurantDetail(restaurantId));`
위 처럼 await, async로  줘도 똑같더라구요..


뭔가 initData를 줘야하는걸까요 ??
도움 주시면 감사하겠습니다..

2021-03-02 14:22 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/restaurant/:id" component={RestaurantsDetailPage} />
제가 설명이 조금 부족했네요 😅 2번을 의도해서 말씀드렸습니다!

2021-03-02 14:26 UTC, jjkim01 commented on src/RestaurantsDetailPage.jsx
> +  const { name, address, menuItems } = useLocation().state;
보다보니 `loadInitialData()`에 주면 오류가 안나네요 ..
근데 여기서는 restaurantId를 어떻게 줘야될지 몰라서 일단 0 주니까
다른 동작도 잘 돌아가서 이부분을 더 알아보는 중입니다~~

2021-03-02 14:27 UTC, Kihyun92 commented on src/RestaurantsDetailPage.jsx
> +  const { name, address, menuItems } = useLocation().state;
넵 데이터가 넘어오기 전에 레스토랑 정보를 가져와 처리하기 때문에 발생하는 에러죠.

말씀하신대로 초기값을 줘야할 것 같습니다.

그리고 일반적으로 상세페이지에서 데이터를 가져오지 못했을 경우엔, 우리는 로딩 화면을 볼 수 있죠~ 간단한 문구로 처리해보는 건 어떨까요?

2021-03-02 14:28 UTC, jjkim01 commented on src/RestaurantsDetailPage.jsx
> +  const { name, address, menuItems } = useLocation().state;
로딩이라는 개념 좋은 것 같아요.
바로 코드가 떠오르진 않는데 .. 한번 적용해보겠습니다 ~

2021-03-02 14:29 UTC, jjkim01 commented on src/App.jsx
> +        <Route path="/restaurant/:id" component={RestaurantsDetailPage} />
옙 수정했습니다. 감사합니다~~

2021-03-02 14:41 UTC, Kihyun92 requested changes
리뷰 드린 것보다 더 잘 반영해주시고 고민을 해주시는 것 같아 좋습니다!

질문에 대한 답변이 늦다고 생각이 되면 슬랙 채널을 통해 다른 동료들과 아이디어를 공유해봐도 좋겠네요~

같은 고민을 하는 동료가 있을 수 있고, 의논을 통해 더 개선할 수 있을 것 같아요 :)

2021-03-02 14:41 UTC, Kihyun92 commented on src/HomePage.jsx
> +        <li><Link to="/restaurants">Restaurants</Link></li>
간단하지만, 태그 간에 줄바꿈 처리해주는게 좋을 것 같아요

2021-03-02 14:41 UTC, Kihyun92 commented on src/RestaurantsContainer.test.jsx
> +    <BrowserRouter>
`MemoryRouter` 로 대체해줘도 좋겠네요~

2021-03-02 14:41 UTC, Kihyun92 commented on src/RestaurantsDetailPage.jsx
> +export default function RestaurantsDetailPage() {
`RestaurantDetailPage`는 어떨까요?

그리고 다른 컴포넌트들 처럼 container-presentation 을 구분해줘도 좋겠네요~

2021-03-02 14:41 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
`useEffect`에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 됩니다~

2021-03-02 14:41 UTC, Kihyun92 commented on src/reducer.js
> +      restaurantDetail,
전반적으로 레스토랑 정보에 관한 네이밍이 `restaurantDetail`인 것 같아요. `detail`이라는 정보가 필요할까요? 🤔

레스토랑에 대한 객체라면 `restaurant` 라고만 해도 될 것 같아요.

사용하는 곳에서 보면 `restaurantDetail.address`에서 `restaurant.address`로 될 것 같네요. 어떤가요?

2021-03-02 17:52 UTC, jjkim01 commented on src/RestaurantsDetailPage.jsx
> +export default function RestaurantsDetailPage() {
파일 이름 변경하고,page, container 분리해봤습니다 ~~

2021-03-02 17:58 UTC, jjkim01 commented on src/RestaurantsPage.jsx
> +  });
음.. 어떤 값들이 변할 때 호출될건지 써준다는게 정확히 감이 잘 안오네요..

`console.log`로 확인해보면 빈 배열을 주면 렌더링을 다시 해도 호출을 안하긴 하네요.

App에서 호출하는 `useEffect`는 빈 배열을 주면 통합 테스트 과정에서 에러나는 것 같구요..

일단 빈 배열을 줬습니다. 천천히 이해해보겠습니다 ~

2021-03-02 18:05 UTC, jjkim01 commented on src/reducer.js
> +      restaurantDetail,
적용했습니다.

restaurant 쪽이 더 직관적으로 이해하기 편한 것 같아요.
결국 name, address가 식당 하나에 대한 정보니까..

감사합니다 ~~

2021-03-03 14:43 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
이미 보셨을 수 있지만, `useEffect`의 두번째 인자에 어떤 값을 넣었을때 어떤 처리를 하는지 리액트 공식 문서를 한번 봐보시면 좋을 것 같습니다 :)
- https://ko.reactjs.org/docs/hooks-reference.html#useeffect

2021-03-03 15:12 UTC, Kihyun92 requested changes
리뷰를 드리는 것보다 더 잘 반영해주시는 것 같아요 👍🏼  리뷰드릴 부분을 찾기 쉽지 않네요 😅

2021-03-03 15:12 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +    <div>
div 태그로 감싸준 이유가 있나요? 필요하지 않다면 제거해줘도 좋겠네요 :)

2021-03-03 15:12 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
>        {restaurants.map((restaurant) => (
구조분해할당을 적용해도 좋겠네요 ~

2021-03-03 15:12 UTC, Kihyun92 commented on src/RestaurantsDetailContainer.test.jsx
> +    });
selector에 넘겨주는 값만 다르게 테스트마다 반복 되는 로직이 있네요. 함수로 추출해서 사용하는 건 어떤가요?

2021-03-03 15:12 UTC, Kihyun92 commented on src/RestaurantsDetailPage.test.jsx
> +    });
지금같은 경우엔 상위의 beforeEach에서 함께 처리할 수 있을 것 같네요~

2021-03-04 11:00 UTC, jjkim01 commented on src/RestaurantDetailPage.jsx
> +    <div>
아,
jsx 문법 (반드시 하나의 태그로 자식 태그들을 감싸줘야 함) 때문에 헷갈렸던 것 같아요.

무조건 div로 감싸야한다고 생각했네요..
if문도 한줄만 할 때는 brace({})가 필요없지만 웬만하면 감싸주라는 느낌으로 사용한 것 같습니다.

2021-03-04 11:17 UTC, jjkim01 commented on src/RestaurantsContainer.jsx
>        {restaurants.map((restaurant) => (
```js
this.state = {
  id: 1,
  name: 'kim',
}

const { id, name } = this.state;
```

이 경우에 적용하는게 구조분해할당이라고 알고있어요.

handleClick, dispatch에 구조분해할당을 어떻게 하는지 감이 잘 안오네요 ..

힌트를 더 주실 수 있으신가요 ?

2021-03-04 12:08 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +    <div>
넵 ㅎㅎ 있어도 문제는 없지만, 필요없다면 없는게 더 명확하게 전달되는 것 같아요 :)

2021-03-04 12:13 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
>        {restaurants.map((restaurant) => (
> ```js
> this.state = {
>   id: 1,
>   name: 'kim',
> }
> 
> const { id, name } = this.state;
> ```
> 
> 이 경우에 적용하는게 구조분해할당이라고 알고있어요.
> 
> handleClick, dispatch에 구조분해할당을 어떻게 하는지 감이 잘 안오네요 ..
> 
> 힌트를 더 주실 수 있으신가요 ?

넵 제가 설명이 조금 부족했네요😅 알고 계신 부분을 응용한다고 생각하시면 좋을 것 같아요. 

지금은 map 내부에서 id와 name 만 사용하고 있으니 이렇게 구조분해할당해서 바로 쓸 수 있겠네요 ㅎㅎ 

```suggestion
      {restaurants.map(({ id, name }) => (
```

- https://ko.javascript.info/destructuring-assignment#ref-673

2021-03-04 12:28 UTC, jjkim01 commented on src/RestaurantsContainer.jsx
>        {restaurants.map((restaurant) => (
오 .. 처음 state나 다른 객체로부터 받을 때만 적용할 수 있다고 생각이 갇혀있었어요.

통으로 받고나서 반복문 내부에서 호출할 때도 이렇게 활용 할 수 있겠네요.

좋은 팁 감사합니다 ~~

2021-03-04 12:34 UTC, jjkim01 commented on src/RestaurantsDetailPage.test.jsx
> +    });
context마다 다른 beforeEach를 적용할 수 있다는 생각을 해서

context가 하나밖에 없더라도 그 안에 선언해줬어요.

아까 위에 'div로 감싸고 안감싸고' 문제처럼 어짜피 호출하는 곳이 하나밖에 없는게 확실할땐

상위에 해주는게 더 좋겠네요.

이런 마이크로 팁이 많이 도움되는 것 같습니다.
감사합니다.

2021-03-04 12:57 UTC, Kihyun92 commented
src 폴더 내에 많은 파일들이 생겼네요! 각각의 관심사에 맞게 폴더로 분리해서 관리해보는 것도 좋겠군요 ㅎㅎ

2021-03-04 13:40 UTC, jjkim01 commented on src/RestaurantsDetailContainer.test.jsx
> +    });
함수 추출하고 인자 넘기는 방법이 두가지인 것 같아요.

1. 객체로 넘겨서 state 이름에 관계없이 사용하는것
```js
implementationSelector({ restaurant });

function implementationSelector(mockData) {
  useSelector.mockImplementation((selector) => selector(mockData));
}
```
근데 이 방법은 undefined 도 객체로 넘겨야해서 좀 어색한 감이 있네요..
`implementationSelector({ undefined });`



2. 지금 코드처럼 넘겨서 `restaurant: 인자` 로 사용하는것
```js
implementationSelector( restaurant );

function implementationSelector(mockData) {
  useSelector.mockImplementation((selector) => selector({
    restaurant: mockData,
  }));
}
```

어떤 방식으로 하는게 좀 더 바람직한가요 ??

자연스럽기는 2번 방법이 더 나아보이긴 합니다만 ,,

2021-03-04 13:43 UTC, jjkim01 commented
> src 폴더 내에 많은 파일들이 생겼네요! 각각의 관심사에 맞게 폴더로 분리해서 관리해보는 것도 좋겠군요 ㅎㅎ

넵,

제가 실제 이 서비스를 유지보수하게 된다면 어떻게 나누는게 편할까? 를 생각해봤어요.

근데 좀 한눈에 안들어오는 것 같기도 하네요..

특히 tests 부분이 그런데,

pageTests
containerTests
로 한번 더 나눠볼 수도 있을 것 같아요.

1. 지금처럼 tests는 한 곳에 몰아놓기
2. test의 관심사도 다시 분리하기

아.. 적다보니까 2번이 더 맞는 것 같네요.

test
- page
- container 

이렇게 할 수 있을 것 같아요. 어떻게 생각하시나요 ??

2021-03-05 13:43 UTC, Kihyun92 commented on src/RestaurantsDetailContainer.test.jsx
> +    });
말씀하신대로 2번이 좋을 것 같네요 :)

2021-03-05 13:53 UTC, Kihyun92 commented
주로 폴더 구조는 정답이 있지는 않은 것 같고, 팀 동료들 간에 약속된 구조로 하게 되는 것 같아요 ㅎㅎ 

이번 과제들을 해보면서 재진님께서 느끼신대로 구조를 짜보시면 좋을 것 같아요 :) 직접 써보고 느껴보는게 장단점을 아는데 좋으니까요.

말씀하신대로 지금 저희는 컴포넌트들을 `page, container, presentation`관점으로 쪼갰다보니 폴더 구조도 비슷하게 가져가는게 편할 것 같긴합니다.

저희 팀에선 주로 src 내에 components, utils, commons, pages, stores, locales 등으로 나누고 각 관심사에 맞게 그 안에 배치하는 스타일입니다 ㅎㅎ

실제 컴포넌트 테스트 파일의 위치는 아래와 같구요.
![image](https://user-images.githubusercontent.com/35797540/110124467-75ba1e00-7e05-11eb-9da9-da9ea44894cd.png)

참고만 해보시고, 본인의 주관대로 일단 쪼개보고 동료들과 많이 의논해보면서 맞춰가는게 베스트인 것 같네요 :)

2021-03-05 14:10 UTC, Kihyun92 commented
test 폴더 명은 `__tests__`가 좋을 것 같네요!

- https://create-react-app.dev/docs/running-tests/#filename-conventions

2021-03-05 14:11 UTC, Kihyun92 requested changes
이번주도 고생하셨습니다! 많은 질문을 해주셔서 저도 많이 고민해본 것 같아서 좋았습니다 😊

오늘 저녁~내일 오전 중에 올라갈 과제 풀이 영상을 꼭 보시면 좋겠습니다 ㅎㅎ

이번 과제를 하면서 무엇을 배우셨나요? 더 배우고 싶은 부분이 있나요?

2021-03-05 14:12 UTC, Kihyun92 approved these changes

2021-03-06 11:54 UTC, jjkim01 commented
> 이번주도 고생하셨습니다! 많은 질문을 해주셔서 저도 많이 고민해본 것 같아서 좋았습니다 😊
> 
> 오늘 저녁~내일 오전 중에 올라갈 과제 풀이 영상을 꼭 보시면 좋겠습니다 ㅎㅎ
> 
> 이번 과제를 하면서 무엇을 배우셨나요? 더 배우고 싶은 부분이 있나요?


'피드백을 받아가며 개발하는 것'에 대한 장점들을 많이 느꼈습니다.
이런 기회가 더 자주 있으면 좋겠다고도 생각했습니다.
빠르게 성장할 수 있을 것 같아요.

정답이 있는 것과 없는 것을 잘 구분해가며 힘조절하는 것도 중요할 것 같아요.

개인적인 사정으로 완주는 못할 것 같습니다만 
가르쳐주신 내용, 접근방식들을 앞으로도 참고해서 많이 배워보겠습니다.

감사합니다 ~~

2021-03-06 15:06 UTC, Kihyun92 commented
> '피드백을 받아가며 개발하는 것'에 대한 장점들을 많이 느꼈습니다.
> 이런 기회가 더 자주 있으면 좋겠다고도 생각했습니다.
> 빠르게 성장할 수 있을 것 같아요.
> 
> 정답이 있는 것과 없는 것을 잘 구분해가며 힘조절하는 것도 중요할 것 같아요.
> 
> 개인적인 사정으로 완주는 못할 것 같습니다만
> 가르쳐주신 내용, 접근방식들을 앞으로도 참고해서 많이 배워보겠습니다.
> 
> 감사합니다 ~~

@jjkim01 고생하셨습니다. 잘 진행해주셨어서 아쉽네요 ㅠㅠ

매 과제마다 많이 고민하시고 질문해주신게 너무 좋았습니다.

건승하시고 기회가 된다면 또 뵈면 좋겠네요 😊

2021-05-16 10:06 UTC, merged