Make restaurant detail page
CodeSoom/week6-assignment-1 pull request #39
Opened 2021-03-01 12:49 UTC by canary4651

Add base code

2021-03-02 12:13 UTC, canary4651 commented on src/App.test.jsx
> +  function renderApp({ path }) {
생각해보니까 각 페이지들을 먼저 만들고 난 후에 router를 붙이는 게 좋을 거 같아서 각 페이지들부터 먼저 테스트하고 만들겠습니다.

2021-03-02 15:29 UTC, moonkii requested changes
![image](https://user-images.githubusercontent.com/46776329/109671348-55951f80-7bb7-11eb-9eee-c958cf20c5ef.png)

커밋 메시지는 TDD 사이클에 맞게 잘 쌓아 가고 있는 것 같아요.

작업을 하기 전에 어떻게 진행하면 좋을지 순서를 먼저 고민해봐도 좋을 것 같아요!

2021-03-02 15:29 UTC, moonkii commented on src/App.jsx
>    const dispatch = useDispatch();
`dispatch` 는 필요한가요?

2021-03-02 15:29 UTC, moonkii commented on src/App.jsx
>  } from './actions';
Lint 를 돌리신건가요?

2021-03-02 15:29 UTC, moonkii commented on src/App.test.jsx
> +  function renderApp({ path }) {
👍

2021-03-02 15:29 UTC, moonkii commented on src/App.test.jsx
> +  context('with default path', () => {
`with` 이라는 표현 보다는 `when` 으로 표현해보면 좋을 것 같아요.

2021-03-02 15:29 UTC, moonkii commented on src/App.jsx
> +        <Route path="/about" component={AboutPage} />
`Home` 은 왜 왕따시키나요

2021-03-02 15:29 UTC, moonkii commented on src/pages/RestaurantsPage.jsx
> +  });
`useEffect` 의 실행 타이밍은 언제일까요?

2021-03-02 15:29 UTC, moonkii commented on src/pages/RestaurnatsPage.test.jsx
> +    expect(dispatch).toBeCalled();
왜 처음에 `dispatch` 가 call 되는지 어떻게 알 수 있나요?

2021-03-03 00:59 UTC, canary4651 commented on src/App.jsx
>  } from './actions';
앗,,,, 올리기 전에 lint 돌리겠습니다.

2021-03-03 00:59 UTC, canary4651 commented on src/App.jsx
>    const dispatch = useDispatch();
없어져도 되서 지웠습니다.

2021-03-03 01:00 UTC, canary4651 commented on src/App.test.jsx
> +  context('with default path', () => {
"/" 이렇게 구체적으로 명시해주는 게 좋은 건가요?

2021-03-03 01:02 UTC, canary4651 commented on src/App.jsx
> +        <Route path="/about" component={AboutPage} />
`Home`은 왜 왕따시키나요가 무슨 말인지 이해를 못했어요...

2021-03-03 12:21 UTC, moonkii commented on src/App.test.jsx
> +  context('with default path', () => {
`/about` 처럼 구체적으로 명시해주는게 이해하기 더 쉽겠죠?

2021-03-04 12:36 UTC, canary4651 commented on src/pages/RestaurantsPage.jsx
> +  });
restaurantsPage에 들어오자마자 실행되지 않을까요..?

2021-03-04 12:36 UTC, canary4651 commented on src/pages/RestaurnatsPage.test.jsx
> +    expect(dispatch).toBeCalled();
저는 restauratnsPage에 들어오자마자 dispatch가 바로 실행된다고 생각했어요.

2021-03-04 16:01 UTC, moonkii commented on src/App.jsx
> +        <Route path="/restaurants" component={RestaurantsPage} />
`exact` 가 필요할거에요!

2021-03-04 16:04 UTC, moonkii commented on src/App.jsx
> +        <Route path="/restaurants:id" component={RestaurantPage} />
`/restaurants/:id`

2021-03-04 16:10 UTC, moonkii commented on src/Header.test.jsx
> +  it('renders header', () => {
header 가 무엇인가요?

2021-03-04 16:10 UTC, moonkii commented on src/MenuItems.jsx
> +
👍

2021-03-04 16:22 UTC, moonkii commented on src/MenuItems.test.jsx
> +    it('renders MenuItems', () => {
서술해줄 때는 컴포넌트 이름 보다는 대상을 그냥 풀어서 써주면 좋을  것 같아요.

`renders menu items`

2021-03-04 16:43 UTC, moonkii commented on src/pages/RestaurantPage.jsx
> +  }, [id]);
`id` 값을 넣어준 이유가 있나요?

2021-03-04 16:45 UTC, moonkii commented on src/pages/RestaurantsPage.jsx
> +  });
두 번째 인자는 왜 빼먹으셨나요 ;)

2021-03-04 16:46 UTC, moonkii commented on src/pages/RestaurnatsPage.test.jsx
> +    expect(dispatch).toBeCalled();
그러면  테스트를 추가해주면 좋겠죠?

2021-03-04 16:57 UTC, moonkii commented
`container` 폴더를 빼준 이유가있나요?

2021-03-05 00:47 UTC, canary4651 commented on src/App.jsx
> +        <Route path="/restaurants" component={RestaurantsPage} />
감사합니다 🤦‍♀️ 이거 때매 겁나 헤맸어요

2021-03-05 00:47 UTC, canary4651 commented on src/App.jsx
> +        <Route path="/restaurants:id" component={RestaurantPage} />
감사합니다 🤦‍♀️ 이거 때매 겁나 헤맸어요 22

2021-03-05 00:48 UTC, canary4651 commented on src/Header.test.jsx
> +  it('renders header', () => {
흠,,, header text로 수정하겠습니다.

2021-03-05 07:56 UTC, canary4651 commented on src/pages/RestaurantPage.jsx
> +  }, [id]);
앗! 뺴줘야 하는데 깜빡했어요.

2021-03-05 08:14 UTC, canary4651 commented
> `container` 폴더를 빼준 이유가있나요?

컨테이너랑 페이지가 너무 많아져서 각 기능과 관심사에 맞게 분리해주고 싶어서 container와 page를 뺐어요.
그 외에도 RestaurantDetail이나 MenuItems 컴포넌트들도 따로 분리해주고 싶은데, 폴더 이름을 어떻게 정해야할 지 몰라서 고민 중입니다. 어떤 이름으로 하는 게 좋을까요?

2021-03-05 13:53 UTC, moonkii commented
> > `container` 폴더를 빼준 이유가있나요?
> 
> 컨테이너랑 페이지가 너무 많아져서 각 기능과 관심사에 맞게 분리해주고 싶어서 container와 page를 뺐어요.
> 그 외에도 RestaurantDetail이나 MenuItems 컴포넌트들도 따로 분리해주고 싶은데, 폴더 이름을 어떻게 정해야할 지 몰라서 고민 중입니다. 어떤 이름으로 하는 게 좋을까요?

많이 복잡한가요?
그러면 컴포넌트 폴더 내부에 페이지명에 따라 폴더 나눠주고 거기에 넣어줘도 될  것 같네요.

2021-03-05 13:53 UTC, moonkii commented on src/MenuItems.test.jsx
> +    it('renders Menu items', () => {
`menu items` 대문자일 필요가 없겠죠?

2021-03-05 13:54 UTC, moonkii commented on src/pages/RestaurnatsPage.test.jsx
> +  it('loads restaurant initial data', () => {
`data` 라는 표현을 빼고 다르게 표현할 순 없을까요? 🤔

2021-03-05 15:04 UTC, canary4651 commented on src/MenuItems.test.jsx
> +    it('renders Menu items', () => {
앗..! 수정하겠습니다.

2021-03-05 15:10 UTC, canary4651 commented on src/pages/RestaurnatsPage.test.jsx
> +  it('loads restaurant initial data', () => {
`state` 는 어떤가요..?

2021-03-06 13:21 UTC, canary4651 commented on src/pages/RestaurnatsPage.test.jsx
> +  it('loads restaurant initial data', () => {
수정했습니다!

2021-03-06 15:17 UTC, moonkii commented
참고로 말씀 드리자면 폴더를 나누는 이유는 개발자가 더 인식을 잘하기 위해서에요.
컴퓨터 입장에서는 폴더를 나눌 필요도 없죠.
그래서 미리 폴더 구조를 나누기 보다 정말 헷갈릴 정도로 복잡할 때, 필요할 때 해야한다는 점 항상 생각해주면 좋을 것 같아요.

회고 작성하시면 merge 하도록 하겠습니다!

2021-03-06 15:45 UTC, moonkii approved these changes
참고로 말씀 드리자면 폴더를 나누는 이유는 개발자가 더 인식을 잘하기 위해서에요.
컴퓨터 입장에서는 폴더를 나눌 필요도 없죠.
그래서 미리 폴더 구조를 나누기 보다 정말 헷갈릴 정도로 복잡할 때, 필요할 때 해야한다는 점만 항상 생각해주면 좋을 것 같아요.

회고 작성하시면 merge 하도록 하겠습니다!

2021-03-07 15:19 UTC, merged