week 6 router
CodeSoom/week6-assignment-1 pull request #40
Opened 2021-03-01 13:22 UTC by gyeongwon1275

## 0301 

- [ ] react-router 기본설정
- [ ] header 
- [ ] HomePage
- [ ] About
- [ ] NotFound

### 고민

- 식당 정보는 restaurantId 를 params 를 받은 후 mount 할 때 api 요청을 통해 받은 데이터를 출력하고자 함 
params 는 숫자만 받아야 할 것 같은데 문자등을 받았을 때 예외처리는 어떻게 할지 고민중 

- 링크로 url 이동하는 것과 사용자가 직접 url 입력해서 이동하는 것의 차이를 추후 확인하고자 함

2021-03-01 14:40 UTC, Kihyun92 requested changes
올바르지 않은 id 값인 경우 어떻게 처리할지에 대한 고민을 해보시는게 좋네요! 👍🏼 

여러 방법들이 있을 것 같아요. 음 일단은 올바르지 않은 요청시 해당 API에서 어떤 값을 내려주는지를 보고 처리할 수도 있고, 또는 프론트에서 API 호출 전에 확인해서 처리를 할지 등이죠 ㅎㅎ

한번 고민해보시면 좋을 부분 같습니다~

2021-03-01 14:40 UTC, Kihyun92 commented on src/App.test.jsx
> +  beforeEach(() => {
사이에 공백 추가해주세요~

2021-03-01 14:40 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('with path /', () => {
사이에 공백 추가해주세요~

2021-03-01 14:40 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('with path /about', () => {
사이에 공백 추가해주세요~

2021-03-02 13:32 UTC, gyeongwon1275 commented
# 질문

## 1> 

**path="/restaurants/:restaurantId" 일 때 params 를 받지 못하고 앱이 멈추는 현상 발생**

react-router link 를 클릭해서 /restaurant/:restaurantId 형식으로 접근하면 
restaurantId 받은 후 화면에 출력하는데 

직접 주소창에 /restaurant/:restaurantId 을 입력하면 아래와 같이 나오며 앱이 멈춰버립니다.. 
GET http://localhost:8080/restaurants/main.js net::ERR_ABORTED 404 (Not Found)

일단 확인해 본 것은 /:restaurantId 형식으로 직접 url 에 입력하면 restaurantId 을 받을 수 있다는 것을 확인하였습니다.

공식문서 (https://reactrouter.com/web/example/url-params) 에서 실험한 결과 제대로 동작하는 것을 보면  
예상되는 문제는 webpack 설정 문제인 것 같은데 제가 뭘 잘못하고 있는 걸까요?? 

## 2> 

**현재 url 에서 params 을 받아오는지를 테스트 해야하는지** 

아래처럼 history 객체를 넘겨주어 테스트해야하는지 아니면 useParams 를 mock 처리할지 궁금합니다. 

```javascript
 function renderRestaurantDetail(path) {
    const history = createMemoryHistory();
    return render((
      <MemoryRouter initialEntries={[path]}>
        <Route
          exact
          history={history}
          path="/restaurants/:restaurantId"
          component={RestaurantDetailContainer}
        />
      </MemoryRouter>
    ));
  }
```

2021-03-02 13:48 UTC, gyeongwon1275 commented on src/App.test.jsx
> +  beforeEach(() => {
수정했습니다~!

2021-03-02 13:48 UTC, gyeongwon1275 commented on src/App.test.jsx
> +  context('with path /', () => {
수정했습니다~!

2021-03-02 13:48 UTC, gyeongwon1275 commented on src/App.test.jsx
> +  context('with path /about', () => {
수정했습니다~!

2021-03-02 16:11 UTC, Kihyun92 requested changes
> 현재 url 에서 params 을 받아오는지를 테스트 해야하는지 
아래처럼 history 객체를 넘겨주어 테스트해야하는지 아니면 useParams 를 mock 처리할지 궁금합니다.

공식 문서를 잘 확인해보신 것 같아요 👍🏼  

말씀하신 것과 같은 몇가지 방법이 있을 것 같은데, 정답은 없는 부분인 것 같아요. 

일단 공식 문서대로 한번 해보시고 잘 해결 된다면 슬랙 채널에 공유해도 좋겠네요 :)

2021-03-02 16:11 UTC, Kihyun92 commented on src/App.jsx
> +        <Route exact path="/restaurants" component={RestaurantPage} />
`RestaurantsPage` 가 맞을 것 같아요~

2021-03-02 16:11 UTC, Kihyun92 commented on src/App.jsx
> +        <Route exact path="/restaurants/:restaurantId" component={RestaurantDetailContainer} />
`path="/restaurants/:id"` 이렇게만 처리해주는건 어떨까요?

2021-03-02 16:11 UTC, Kihyun92 commented on src/RestaurantDetailContainer.jsx
> +export default function RestaurantDetailContainer() {
`container-presentation`을 잘 나눠주신 것 같아요~

라우팅에 대한 부분도 따로 관리해주는 건 어떤가요?

이런 순서일 것 같아요. `App -> Page -> Container -> Presentation`

2021-03-02 16:11 UTC, Kihyun92 commented on src/RestaurantDetail.jsx
> +  const {
라인 사이에 공백을 추가해주는게 좋을 것 같아요~

2021-03-02 16:11 UTC, Kihyun92 commented on src/RestaurantDetail.jsx
> +  return (
라인 사이에 공백을 추가해주는게 좋을 것 같아요~

2021-03-02 16:11 UTC, Kihyun92 commented on src/RestaurantDetail.jsx
> +      </div>
```suggestion
      <div>
        {`주소 : ${address}`}
      </div>
```

`template literal`로 처리해주는건 어떤가요? 의도와 다를까요?
- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals

2021-03-02 16:11 UTC, Kihyun92 commented on src/RestaurantDetail.jsx
> +        {menuItems.map((menu) => (
구조 분해 할당으로 처리해줘도 좋겠네요~

2021-03-02 16:11 UTC, Kihyun92 commented on src/RestaurantPage.jsx
> +  });
`useEffect`에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 됩니다~

2021-03-02 16:11 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
>        {restaurants.map((restaurant) => (
구조 분해 할당으로 처리해줘도 좋겠군요~

2021-03-02 16:11 UTC, Kihyun92 commented on src/reducer.js
> +  restaurantDetail: null,
레스토랑 정보에 해당하는 상태인 것 같아요~ `restaurant`라고만 하는건 어떤가요?

사용하는 곳에서 보면 `restaurantDetail.address`에서 `restaurant.address`로 될 것 같네요.

2021-03-03 04:30 UTC, gyeongwon1275 commented on src/App.jsx
> +        <Route exact path="/restaurants" component={RestaurantPage} />
RestaurantsPage 로 수정했습니다~!

2021-03-03 04:31 UTC, gyeongwon1275 commented on src/App.jsx
> +        <Route exact path="/restaurants/:restaurantId" component={RestaurantDetailContainer} />
앞에 /restaurants 가 있기 때문에 굳이 restaurantId 가 필요 없겠네요 id 로 수정했습니다 ~!

2021-03-03 04:32 UTC, gyeongwon1275 commented on src/RestaurantDetailContainer.jsx
> +export default function RestaurantDetailContainer() {
Page -> 라우터 담당 , Container-> api 등 데이터 담당, Presentation -> view 담당으로 지정해서 수정했습니다~!

2021-03-03 04:41 UTC, gyeongwon1275 commented on src/RestaurantDetail.jsx
> +  const {
공백추가 하는 걸로 수정했습니다!

2021-03-03 04:41 UTC, gyeongwon1275 commented on src/RestaurantDetail.jsx
> +  return (
공백추가 하는 걸로 수정했습니다!

2021-03-03 04:43 UTC, gyeongwon1275 commented on src/RestaurantDetail.jsx
> +      </div>
address 만 test 하려고 하다 보니 구조분해 할당하면 getByText 안걸려서 따로 태그를 분리했었는데 
getByText(`주소 : ${address}`) 로 test 수정하고 template literal 적용했습니다!

2021-03-03 04:45 UTC, gyeongwon1275 commented on src/RestaurantDetail.jsx
> +        {menuItems.map((menu) => (
```javascript
 const {
    name, address, menuItems, reviews, information,
  } = restaurant;
```
구조분해 할당하려면 위에 name 과 변수가 겹처서 메뉴, 리뷰 리스트 부분을 따로 컴포넌트로 분리했습니다.

2021-03-03 04:46 UTC, gyeongwon1275 commented on src/RestaurantPage.jsx
> +  });
처음 mount 될 때 한번만 하면 될 것같아 빈배열로 수정했습니다.

2021-03-03 04:49 UTC, gyeongwon1275 commented on src/reducer.js
> +  restaurantDetail: null,
restaurants 와 헷갈릴 것 같아 restaurantDetail 로 설정했었는데 restaurant 으로 수정했습니다!

2021-03-03 04:56 UTC, gyeongwon1275 commented on src/RestaurantsContainer.jsx
>        {restaurants.map((restaurant) => (
destructuring assign 안되있는 다른 부분까지 수정했습니다!

2021-03-03 14:40 UTC, Kihyun92 requested changes
src 폴더 내에 파일들이 꽤 많아진 것 같아요~ 의도와 역할에 따라 폴더로 구분해보는건 어떨까요?

2021-03-03 14:40 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +export default function RestaurantDetailPage() {
이 페이지 컴포넌트의 역할이 무엇인가요? 단순히 컴포넌트만 연결해주고 있는 것 같군요.

`RestaurantDetailContainer` 의 역할을 나눌 수 있을까요?

2021-03-04 01:44 UTC, gyeongwon1275 commented on src/RestaurantDetailPage.jsx
> +export default function RestaurantDetailPage() {
>이 페이지 컴포넌트의 역할이 무엇인가요? 단순히 컴포넌트만 연결해주고 있는 것 같군요.

지적하신 것 처럼 RestaurantDetailPage 가 아무역할도 하지 않는 반면 RestaurantDetailContainer 에 과도한 역할이 몰려있다고 생각했습니다. 

이에 RestaurantDetailContainer 는 store state 에서 데이터를 받아서 전달하는 역할 

RestaurantDetailPage 는 useParams 를 받아서 처리하는 역할로 구분했습니다.

2021-03-04 01:45 UTC, gyeongwon1275 commented
>이 페이지 컴포넌트의 역할이 무엇인가요? 단순히 컴포넌트만 연결해주고 있는 것 같군요.

지적하신 것 처럼 RestaurantDetailPage 가 아무역할도 하지 않는 반면 RestaurantDetailContainer 에 과도한 역할이 몰려있다고 생각했습니다. 

이에 RestaurantDetailContainer 는 store state 에서 데이터를 받아서 전달하는 역할 

RestaurantDetailPage 는 Route 에 컴포넌트로 지정했기 때문에 useParams 를 받아서 처리하는 역할로 구분했습니다. 

올바르게 구분한 걸까요?

2021-03-04 14:08 UTC, Kihyun92 requested changes
### 1번 답변
넵, 좋은 것 같습니다! 👍🏼 

### 2번 답변
이 부분은 상황마다 다를 것 같은데, 지금의 구조에서는 __tests__ 폴더로 분리하지 않아도 괜찮을 것 같네요(지금 구조도 괜찮습니다 ㅎㅎ)

그 이유는 컴포넌트가 다른 폴더로 옮겨지는 경우, 테스트 파일에서 경로 수정해주는 걸 놓칠 수 있을것 같아요.

만약 컴포넌트 별로 폴더가 따로 관리된다면 (Restaurant 폴더 안에 Restaurant.jsx, css 파일 등이 있는 구조) 그 안에서 테스트 폴더를 만들고 테스트를 관리해도 상관없겠죠. 이 경우엔 컴포넌트를 옮기면 같이 옮겨질 테니까요 ㅎㅎ

마지막 리뷰가 될 것 같네요. 혹시 리뷰 받고 싶은 부분이 있다면 언제든 편하게 말씀해주세요 :)

2021-03-04 14:08 UTC, Kihyun92 commented on src/containers/RegionsContainer.jsx
> +  const selectedRegion = useSelector(get('selectedRegion'));
사이에 공백은 빼줘도 좋을 것 같네요~

2021-03-04 14:08 UTC, Kihyun92 commented on src/containers/RegionsContainer.jsx
> +
이곳에 공백은 제거해도 될 것 같네요 ㅎㅎ

2021-03-04 14:08 UTC, Kihyun92 commented on src/containers/RestaurantsContainer.jsx
> +import Restaurants from '../components/Restaurants';
사이에 공백을 추가해서 외부 모듈과 컴포넌트 간에 구분을 해주는것도 좋을 것 같네요

2021-03-04 14:08 UTC, Kihyun92 commented on src/pages/RestaurantDetailPage.jsx
> +  const isInValidParam = !Number.isInteger(parseInt(id, 10));
컴포넌트 바깥에 함수로 빼도 좋겠네요 :)

2021-03-05 12:49 UTC, Kihyun92 commented
이번 주도 고생하셨습니다~ 

위에 커맨트 남긴 부분 한번 확인해보시면 좋을 것 같고, 오늘 밤~내일 오전 중에 올라올 과제 풀이 영상 꼭 보셨으면 좋겠네요 :)

2021-03-08 12:37 UTC, merged