레스토랑 상세 페이지 구현하기
CodeSoom/week6-assignment-1 pull request #41
Opened 2021-03-02 08:03 UTC by Najeong-Kim

2021-03-02 12:00 UTC, Najeong-Kim commented
api 연결은 아직 못했습니다 ㅠ

2021-03-02 14:15 UTC, Kihyun92 requested changes
잘 진행하고 계신 것 같군요! 😊

다음 커밋 기다리겠습니다 ㅎㅎ

2021-03-02 14:15 UTC, Kihyun92 commented on src/DetailPage.jsx
> +export default function DetailPage() {
4c7ff264b1ee4a733f95c321ad37a77bc84ec5bf

위 커밋을 보면 아래 내용들을 확인할 수 없는 것 같아요~ 즉 테스트시에 해당 내용을 먼저 화면에 노출되는지 확인하고,(fail) 지금과 같은 해당 정보들을 노출하는 DetailPage 컴포넌트를 구현하는 순서가 맞을 것 같아요~

2021-03-02 14:15 UTC, Kihyun92 commented on src/HomePage.jsx
> +}
![image](https://user-images.githubusercontent.com/35797540/109660705-82900500-7bac-11eb-864b-d4ab317c05c3.png)

파일 마지막에 추가 라인이 필요하다는 에러가 발생하는 부분들이 있는 것 같아요

PR을 올리시고, 항상 커밋한 내용들을 깃헙에서 확인해보는것도 좋습니다~

2021-03-02 14:15 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
`useEffect`에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 됩니다~

2021-03-03 01:55 UTC, Najeong-Kim commented on src/HomePage.jsx
> +}
아이고..고쳤습니다 PR올리고 확인하기 명심하겠습니다!!!

2021-03-03 02:03 UTC, Najeong-Kim commented on src/RestaurantsPage.jsx
> +  });
네!!

2021-03-03 02:04 UTC, Najeong-Kim commented on src/DetailPage.jsx
> +export default function DetailPage() {
아.. 테스트해보겠습니다!

2021-03-03 11:43 UTC, Najeong-Kim commented
이제 reducer를 구현해볼거예요!

2021-03-03 14:09 UTC, Kihyun92 requested changes
detail 이라는 네이밍으로 관리를 하니 명확하지 않은 느낌이 들었습니다.

조금 더 명확하게 처리하면 좋을 것 같네요 :)

2021-03-03 14:09 UTC, Kihyun92 commented on src/DetailContainer.jsx
> +export default function DetailContainer() {
뭐에 대한 `Detail`인지 모를 것 같아요~

레스토랑 상세 페이지를 위한거라면 조금 더 명확하게 `RestaurantPage`, `RestaurantContainer`는 어떤가요?

2021-03-04 06:44 UTC, Najeong-Kim commented on src/DetailContainer.jsx
> +export default function DetailContainer() {
네!! 명명 변경하는거 한 번에 처리해서 커밋하겠습니다 중간에 오류생길까봐ㅠㅠ ㅎㅎ

2021-03-04 11:04 UTC, Najeong-Kim commented
제가 코드를 잘못작성해버려서 Detail은 Page가 아니라 Container에서 불러와야돼요!! Page랑 Container 이름만 바꾸려는데 코드는 잘 작성된건가요? 아니면 컴포넌트를 Page로 새로 만드는게 좋을까요?
![image](https://user-images.githubusercontent.com/73640737/109954479-b9892680-7d24-11eb-837a-978089a6aacc.png)

2021-03-04 11:09 UTC, Najeong-Kim commented
삼항연산자를 사용하면서 테스트 커버리지 100%가 깨졌습니다 ㅠ

2021-03-04 13:15 UTC, Kihyun92 requested changes
반드시 page로 컴포넌트를 설정해줘야하지는 않습니다 ㅎㅎ

Container에서 Page의 역할을 하고 있는 부분이 있어서 서로 관심사를 분리해주기 위해서라면 Page 컴포넌트를 새로 만드는것도 좋겠네요 :)

2021-03-04 13:15 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/restaurant/:id" component={RestaurantDetailContainer} />
`path="/restaurants/:id"`와 같이 복수형으로 하는게 좋을 것 같아요~

`REST API`에서 URL을 표현할 땐 restaurants와 같이 collection(집합)을 먼저 표현하고 그 집합 중에 특정한 1개는 id(식별자)로 구분하죠.

- https://reactrouter.com/web/api/Route/path-string-string
- https://restfulapi.net/resource-naming/

2021-03-04 13:15 UTC, Kihyun92 commented on src/RestaurantDetailContainer.jsx
> +  const { id } = match.params;
match를 넘겨주는 부분이 아직 구현이 안된 것 같군요.

`useParams`를 사용해서 넘겨주는 id 값을 받아오는건 어떨까요?

- https://reactrouter.com/web/api/Hooks/useparams

2021-03-04 13:15 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +          {menuItems.map(({ id, name }) => (<li key={id}>{name}</li>))}
가독성을 위해 줄바꿈처리를 해주는게 좋을 것 같네요 :)

2021-03-05 04:07 UTC, Najeong-Kim commented on src/App.jsx
> +        <Route path="/restaurant/:id" component={RestaurantDetailContainer} />
아항~~~ 넵!!

2021-03-05 04:28 UTC, Najeong-Kim commented on src/RestaurantDetailPage.jsx
> +          {menuItems.map(({ id, name }) => (<li key={id}>{name}</li>))}
넵!

2021-03-05 04:29 UTC, Najeong-Kim commented on src/RestaurantDetailContainer.jsx
> +  const { id } = match.params;
어... App에서 id를 받는 것 맞나요?
![image](https://user-images.githubusercontent.com/73640737/110067286-c22a3d00-7db6-11eb-92c8-f5f955b5c29a.png)

2021-03-05 12:48 UTC, Najeong-Kim commented on src/RestaurantDetailContainer.jsx
> +  const { id } = match.params;
useParams 이용해서구현했습니다!

2021-03-05 13:39 UTC, Kihyun92 requested changes
깨지는 테스트들만 확인해보시면 될 것 같네요 👍🏼

2021-03-05 13:39 UTC, Kihyun92 commented on src/RestaurantDetailContainer.test.jsx
> +    const { container } = renderDetailPage({ path: './restaurants/1' })
라우트 path에 `.`을 포함하는게 맞나요? 🤔

2021-03-05 13:39 UTC, Kihyun92 commented on src/RestaurantDetailPage.test.jsx
> +      ));
중복되는 렌더 관련 로직은 함수로 추출해도 좋겠군요~

2021-03-05 13:39 UTC, Kihyun92 commented on src/RestaurantsContainer.test.jsx
> +    <MemoryRouter>
`MemoryRouter`로 감싸주지 않아도 되지 않나요??

2021-03-06 07:27 UTC, Najeong-Kim commented on src/RestaurantDetailContainer.test.jsx
> +    const { container } = renderDetailPage({ path: './restaurants/1' })
아..아니요!!

2021-03-06 07:29 UTC, Najeong-Kim commented on src/RestaurantsContainer.test.jsx
> +    <MemoryRouter>
RestaurantsContainer에 Link가 있어서 MemoryRouter를 지우니 오류가 나옵니다!

2021-03-06 11:17 UTC, Najeong-Kim commented on src/RestaurantDetailPage.test.jsx
> +      ));
두번째에 나오는 render는 빈 객체를 넣어주는데 이걸 어떻게 표현해야할까요..?

2021-03-06 12:06 UTC, Najeong-Kim commented
> 깨지는 테스트들만 확인해보시면 될 것 같네요 👍🏼

선생님..다했어요ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2021-03-06 15:14 UTC, Kihyun92 commented on src/RestaurantDetailPage.test.jsx
> +      ));
실제로 빈 객체를 넘겨주거나 혹은 [default parameter](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters)로 해결할 수 있을 것 같아요!

2021-03-06 15:18 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~ 💯 

TDD cycle을 잘 지키면서 완성해주신 것 같아요! 

이번 과제를 통해 무엇을 배웠나요? 더 알고 싶은 부분이 있나요?

강의 풀이 영상 꼭 보시면 좋을 것 같습니다~
슬랙 채널에 회고 남겨주시면 머지하도록 하겠습니다 :)
이번주도 고생하셨습니다. 빠르게 잘 완성해주신 것 같아요! 👍🏼

배운 내용들을 잘 정리해보며 진행하시는게 너무 좋네요!

이번 과제를 통해 무엇을 배웠나요? 더 알고 싶은 부분이 있나요?



슬랙 채널에 회고 남겨주시면 머지하도록 하겠습니다 :)

2021-03-07 13:07 UTC, merged