Develop
CodeSoom/week6-assignment-1 pull request #42
Opened 2021-03-02 11:57 UTC by yoonhe

## 한 일
- `about`, `restaraunts`, `restaraunts/:id` 라우팅 작업

2021-03-02 12:01 UTC, yoonhe commented
질문이 있습니다!

`restaurants/:id`를 제외한 나머지 페이지들(about, restaurents)은 새로고침을 해도 페이지가 잘 나오는데 ``restaurants/:id` 페이지만 새로고침시에 아래와 같은 에러가납니다.
![image](https://user-images.githubusercontent.com/53102889/109645482-3f2c9b00-7b9a-11eb-8d9a-1022bc619d20.png)

다른페이지들과 다른부분을 찾아보니
`http://localhost:8080/restaurants/main.js` 이렇게 `main.js`를 다른 경로에서 가져와 에러가 나는것 같습니다.. 원인은 파악했는데 해결방법을 못찾고있습니다..

2021-03-02 15:47 UTC, moonkii requested changes
![image](https://user-images.githubusercontent.com/46776329/109673401-575fe280-7bb9-11eb-9a23-58396da1e758.png)

TDD 를 하실 때 `RED` 에서 확인하고 싶은 내용이 테스트로 들어가야해요.
테스트 없이 먼저 작성되는 코드들이 많은 것 같아요!

> ... main.js를 다른 경로에서 가져와 에러가 나는것 같습니다..

네 원인은 잘 파악하신 것 같아요.
base 가 되는 path 가 다르기 때문에 발생하는 문제에요.
해결 방법으로는 `main.js` 의 경로를 잡아주는 방법도 있고, `webpack.config.js` 에서 옵션을 주는 방법이 있을거에요.

2021-03-02 15:47 UTC, moonkii commented on src/AboutPage.jsx
> +export default AboutPage;
따로 분리하지말고 `export default function AboutPage()...`  로 합쳐주면 좋을 것 같아요.

2021-03-02 15:47 UTC, moonkii commented on src/AboutPage.test.jsx
> +});
간단하지만 제목이라도 나오도록 테스트를 넣어주면 어떨까요? 🤔

2021-03-02 15:47 UTC, moonkii commented on src/RestaurantsContainer.test.jsx
>  import RestaurantsContainer from './RestaurantsContainer';
`import` 도 공백으로 구분지어주면 좋을 것 같아요.

2021-03-02 15:47 UTC, moonkii commented on src/RestaurantsDetailPage.jsx
> +  }, [id]);
load 하는 시점은 id 값이 변할 때가 좋을까요? 🤔

2021-03-02 15:47 UTC, moonkii commented on src/RestaurantsDetailPage.test.jsx
> +});
왜 테스트 코드는 없나요??

2021-03-03 02:16 UTC, yoonhe commented
> 네 원인은 잘 파악하신 것 같아요.
base 가 되는 path 가 다르기 때문에 발생하는 문제에요.
해결 방법으로는 main.js 의 경로를 잡아주는 방법도 있고, webpack.config.js 에서 옵션을 주는 방법이 있을거에요.

슬랙에 효근님께서 올려주신 아래의 질문글에 대한 답변에서 답을 찾을 수 있었는데요
https://codesoom-group.slack.com/archives/C01JEHR319T/p1614692515012800

아래처럼 `/main.js`로 경로가 잡히면 절대경로가 되기때문에 어떤 페이지에서 `main.js `를 가져오던 `루트경로/main.js`에서 가져오게되서 `main.js`가 올바르게 가져와진다고 이해했는데, 

잘못 이해한 부분이 있으면 말씀해주세요!
```js
<script src="/main.js"></script>
```

2021-03-03 07:07 UTC, yoonhe commented on src/RestaurantsDetailPage.test.jsx
> +});
`RestaurantsDetailPage`를 마크업부터 다시 `TDD` 해보았습니다. 관련내용은 푸쉬해두었습니다 !

2021-03-03 10:13 UTC, yoonhe commented on src/RestaurantsDetailPage.jsx
> +  }, [id]);
깃헙에 슬랙 내용을 기록해두려고 가져왔습니다 ㅎㅎㅎㅎ

상세 페이지는 레스토랑 메뉴(마녀주방 등등..)을 클릭했을때 라우팅되거나 주소창에 직접 입력했을때 보여지므로 `id`가 바뀌어 리렌더링될 상황이 생기지않으므로 두번쨰 인자에 `id` 를 넣어줄 필요가 없는거군요?? 두번쨰 인자에 빈배열을 넣어 최초 렌더링시에만 `useEffect` 가 실행되게 하면 된다고 이해했는데, 틀린 부분이 있으면 말씀해주세요!

#### 답변
네 맞아요!

2021-03-03 12:42 UTC, moonkii commented on src/RestaurantDetail.jsx
> +      ) : <div>로딩중..</div>}
컴포넌트를 `( )` 로 감싸주면 좋을 것 같아요.

린트에서는 안잡히나요?

2021-03-03 12:44 UTC, moonkii commented on src/RestaurantDetailContainer.test.jsx
> +  beforeEach(() => {
mock clear 도 추가해주면 좋겠죠?

2021-03-03 12:44 UTC, moonkii commented on src/RestaurantDetailContainer.test.jsx
> +      restaurantDetail: given.restaurantDetail,
잘 사용하셨어요! 👍

2021-03-03 12:46 UTC, moonkii commented on src/RestaurantDetailPage.jsx
> +    </>
컴포넌트가 하나면 Fragment 로 감싸주지 않아도 괜찮아요!

2021-03-04 11:06 UTC, yoonhe commented on src/RestaurantDetail.jsx
> +      ) : <div>로딩중..</div>}
흠.. 넵..

```js
: (
        <div>로딩중..</div>
      )
```

이렇게 변경해주었습니다!

2021-03-04 11:07 UTC, yoonhe commented on src/RestaurantDetailContainer.test.jsx
> +  beforeEach(() => {
넵! `jest.clearAllMocks();` 추가해주었습니다!

2021-03-04 11:08 UTC, yoonhe commented on src/RestaurantDetailPage.jsx
> +    </>
앗.. 제가 왜 그랬을까요 ㅎㅎㅎ 수정했습니다!

2021-03-04 15:08 UTC, moonkii commented on src/RestaurantDetailPage.jsx
> +  return <RestaurantDetailContainer />;
`return ( );` 이 기본형태에요. 괄호를 넣어주면 좋을 것 같아요.

2021-03-04 15:18 UTC, moonkii commented on src/RestaurantDetailContainer.jsx
> +  );
코드 리뷰를 할 때 동일한 부분에 모두 리뷰를 달지는 않아요.

리뷰를 반영하실 때 똑같은 부분도 찾아서 전체적으로 반영해주면 좋을 것 같아요.

2021-03-04 15:20 UTC, moonkii commented on src/HomePage.test.jsx
> +});
`HomePage` 테스트도 추가해주세요 ;)

2021-03-05 07:47 UTC, moonkii commented
PR을 `CodeSoom:main` 으로 보내셨어요!
올바른 branch 로  변경해서 보내주세요 ;)

2021-03-05 08:47 UTC, yoonhe commented on src/RestaurantDetailContainer.jsx
> +  );
넵... 좀더 꼼꼼히 살펴보로독 할게요!

2021-03-05 08:57 UTC, closed without merging