Feature/restaurant detail
CodeSoom/week6-assignment-1 pull request #43
Opened 2021-03-02 12:02 UTC by bluel00

About 페이지 생성까지 작업.

# 할일
- About 페이지 링크 연결

2021-03-02 14:04 UTC, Kihyun92 commented
강의를 보시고 TDD cycle에 맞게 진행해보고 계신 것 같네요! 좋습니다 :)

다음 커밋 기다리겠습니다~

2021-03-03 13:57 UTC, Kihyun92 requested changes

2021-03-03 13:57 UTC, Kihyun92 commented on src/Restaurants.jsx
> +  });
`useEffect`에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 됩니다~

- https://reactjs.org/docs/hooks-reference.html#useeffect

2021-03-03 13:58 UTC, Kihyun92 commented
커밋 내용들을 보니 `TDD cycle`을 잘 지키며 진행해주고 계신 것 같네요 👍🏼 👍🏼

2021-03-05 15:30 UTC, Kihyun92 requested changes
TDD Cycle을 정말 잘 사용하고 계신듯합니다 👍🏼 

다만 아직 리뷰 드릴 작업물들이 많지 않네요. 이번 주말을 잘 활용해보셔도 좋을 것 같습니다 😊

2021-03-05 15:30 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/restaurant/:id" component={RestaurantDetail} />
`path="/restaurants/:id"`와 같이 패스를 정해주는 건 어떨까요?

`REST API`에서 URL을 표현할 땐 `restaurants`와 같이 `collection(집합)`을 먼저 표현하고 그 집합 중에 특정한 1개는 `id(식별자)`로 구분하죠.

- https://restfulapi.net/resource-naming/

2021-03-07 13:27 UTC, Kihyun92 approved these changes
잘 진행해주셨네요!

강의 풀이영상을 보시고 아샬님은 어떻게 접근하는지 보셔도 좋을 것 같습니다 :)

이번 과제를 통해 무엇을 배웠나요? 더 배우고 싶은 부분이 있나요?

슬랙 채널에 회고 올려주시면 머지 하겠습니다~

2021-03-07 13:27 UTC, Kihyun92 commented on src/RestaurantDetail.jsx
> +export default function RestaurantDetail({ params }) {
해당 컴포넌트가 많은 역할을 하고 있는 것 같아요~ `container-presentation`이라는 관심사에 따라 컴포넌트를 쪼개보는 것도 좋을 것 같네요 ㅎㅎ

2021-03-07 23:47 UTC, bluel00 commented on src/RestaurantDetail.jsx
> +export default function RestaurantDetail({ params }) {
네 회고 올렸습니다.

아직 TDD에 대한 감을 잘 못잡은거 같아서 
이번주에는 TDD를 꼼꼼하게 해보고 싶어서 진행해 봤습니다.

컴포넌트 분리를 하고 싶었는데 시간 안에 다 못 끝냈네요; 

근데 TDD로만 작업할 때는 몰랐는데,
지금 저 e2e 에러는 왜 나는지 모르겠습니다.

2021-05-16 10:06 UTC, merged