2 zero1
CodeSoom/week6-assignment-1 pull request #44
Opened 2021-03-02 12:22 UTC by 2Zero1

2021-03-02 13:52 UTC, Kihyun92 commented
강의 영상을 잘 봐주신 것 같군요 ㅎㅎ 

다음 커밋 기다리겠습니다~

2021-03-03 13:50 UTC, Kihyun92 requested changes
가능하면 TDD cycle에 맞춰 작업 의도가 드러나게 커밋을 하는 연습을 해보시면 좋을 것 같아요!

2021-03-03 13:50 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/restaurants/" component={RestaurantPage} />
restaurants/${restaurant.id}와 같이 뒤에 id 정보를 넘겨주는 건 어떤가요?

`REST API`에서 `URL`을 표현할 땐 `restaurants`와 같이 `collection(집합)`을 먼저 표현하고 그 집합 중에 특정한 1개는 `id(식별자)`로 구분하죠.

2021-03-03 13:50 UTC, Kihyun92 commented on src/RestaurantPage.jsx
> +    const id = pathname.split('/')[pathname.split('/').length - 1];
id 정보를 가져오는데 꽤나 복잡한 로직이 필요해진 것 같습니다.

조금 단순화하려면 어떻게 할 수 있을까요? `useParams`를 활용해보셔도 좋을 것 같습니다 ㅎㅎ

- https://reactrouter.com/web/api/Hooks/useparams

2021-03-03 13:50 UTC, Kihyun92 commented on src/RestaurantPage.jsx
> +  });
`useEffect`에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 됩니다~

2021-03-03 13:50 UTC, Kihyun92 commented on src/RestaurantsDetailContainer.jsx
> +export default function RestaurantsDetailContainer() {
네이밍을 `RestaurantContainer` 라고만 해주는건 어떤가요?

2021-03-03 13:50 UTC, Kihyun92 commented on src/RestaurantsMenusContainer.jsx
> +export default function RestaurantsMenusContainer() {
마찬가지로 `RestaurantMenuContainer` 라고만 해주는건 어떨까요?

2021-03-04 01:21 UTC, 2Zero1 commented on src/App.jsx
> +        <Route path="/restaurants/" component={RestaurantPage} />
음 .. 이해가 잘 안되는데 다시 한번 설명 부탁드려요 !

2021-03-04 01:27 UTC, 2Zero1 commented
> 가능하면 TDD cycle에 맞춰 작업 의도가 드러나게 커밋을 하는 연습을 해보시면 좋을 것 같아요!

테스트 코드 작성 한 후에 코드를 작성하긴 했는데, 매번 커밋을 생성한다는걸 잊고 다 해버린 후에 완료했다는 커밋만 만들게 되네요. 배운걸 머릿속에 넣는것도 힘들다 보니 그런것 같습니다. 리뷰 적용한 후에 처음부터 다시 tdd 사이클로 해보겠습니다

2021-03-04 01:28 UTC, 2Zero1 commented on src/RestaurantPage.jsx
> +  });
이부분도 이해가 잘 안되는데 한번만 더 설명 부탁드립니다 !

2021-03-04 12:47 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/restaurants/" component={RestaurantPage} />
제가 설명이 조금 부족했네요😅 아래 두 문서가 참고가 되실 것 같습니다 :)

- https://reactrouter.com/web/api/Route/path-string-string
- https://restfulapi.net/resource-naming/

2021-03-04 12:48 UTC, Kihyun92 commented on src/RestaurantPage.jsx
> +  });
useEffect의 두번째 인자로 어떤 값을 넘기느냐에 따라 다르게 동작합니다 ㅎㅎ 이 부분도 문서를 참조 드리니 한번 확인해보시면 좋을 것 같네요!

- https://ko.reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect

2021-03-04 12:53 UTC, Kihyun92 requested changes
src 폴더 내에 많은 파일들이 생긴 것 같아요~ 각각 관심사에 맞게 폴더로 관리해보는 것도 좋을 것 같네요 :)

2021-03-04 12:53 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
이 부분도 적용해주세요!

https://github.com/CodeSoom/react-week6-assignment-1/pull/44/files#r587442558

2021-03-04 12:53 UTC, Kihyun92 commented on src/reducer.js
> +  },
레스토랑에 대한 초기상태를 마찬가지로 객체로 분리해줘도 좋겠네요~

``` javascript
const initialRestaurant = {
  ...
};

const initialState = {
  ...
  restaurant: initialRestaurant,
}
```

2021-03-05 15:50 UTC, Kihyun92 requested changes
파일 전반적으로 개선해보고 계신 것 같아요~ 어떤 방향으로 진행하는지 알려주셔도 좋을 것 같습니다 :)

![image](https://user-images.githubusercontent.com/35797540/110138998-e9fcbd80-7e15-11eb-89ca-7c2caf977ae2.png)

그리고 파일 전반적으로 마지막에 공백을 추가해주세요!

2021-03-05 15:50 UTC, Kihyun92 commented on src/App.test.jsx
> +  render((
중복되는 테스트로 인해 App의 테스트를 간소화해본건 좋은 것 같지만, 지금의 경우 이 테스트 코드가 아무런 의미가 없는 것 같아요.

assertion을 추가해주는건 어떨까요?

2021-03-05 15:50 UTC, Kihyun92 commented on src/App.jsx
> +  dispatch(loadCategories());
App으로 옮기신 의도가 궁금하네요~

2021-03-05 15:50 UTC, Kihyun92 commented on src/CategoriesContainer.test.jsx
>      });
useSelector를 mocking 해주는 로직이 테스트마다 중복되는 것 같아요~ 

이 부분을 함수로 추출 해서 상위 beforeEach와 함께 관리할 수 있을까요?

2021-03-06 05:11 UTC, 2Zero1 commented on src/App.test.jsx
> +  render((
파일을 전반적으로 개선하는게 아니라 이전에 했던것들 다 날리고 처음부터 다시 TDD 사이클로 진행해보고 있습니다 !

2021-03-06 15:09 UTC, Kihyun92 commented on src/App.test.jsx
> +  render((
아하 다시 진행해보시고 있었군요! 꼭 TDD cycle로 완주 해보시면 좋겠네요 👍🏼 👍🏼

2021-03-07 13:09 UTC, Kihyun92 commented
@2Zero1 님~ 어떻게 잘 진행해보고 계신가요?

과제 풀이 영상을 보시고 해보셔도 좋을 것 같습니다! :)

2021-03-07 16:24 UTC, 2Zero1 commented
> @2Zero1 님~ 어떻게 잘 진행해보고 계신가요?
> 
> 과제 풀이 영상을 보시고 해보셔도 좋을 것 같습니다! :)

주말은 퍼져서 진행을 못했네요 ..ㅠㅠ 
내일까지 모두 다 진행하고 푸쉬하려고 합니다.

2021-05-16 10:06 UTC, merged