라우팅 - 상세페이지 구현
CodeSoom/week6-assignment-1 pull request #45
Opened 2021-03-02 15:30 UTC by ParkYoungHoon

2021-03-03 13:37 UTC, Kihyun92 requested changes
강의영상을 잘 봐보신 것 같네요 👍🏼 

다음 커밋 기다리겠습니다 😊

2021-03-03 13:37 UTC, Kihyun92 commented on src/AboutPage.jsx
> +      <p>이번주 과제는 꼭 잘 끝내보자 화이팅!</p>
화이팅입니다~ 🔥

2021-03-03 13:37 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
`useEffect`에 어떤 값들이 변할 때 호출될건지 써줘야할 것 같아요. 한 번만 실행하고 싶다면 빈 배열을 넣어주면 됩니다~

2021-03-04 12:36 UTC, Kihyun92 requested changes

2021-03-04 12:36 UTC, Kihyun92 commented on src/App.jsx
> +        <Route path="/detail" component={DetailPage} />
`path="/restaurants/:id"`와 같이 패스를 정해주는 건 어떨까요?

`REST API`에서 URL을 표현할 땐 `restaurants`와 같이 `collection(집합)`을 먼저 표현하고 그 집합 중에 특정한 1개는 `id(식별자)`로 구분하죠.

- https://restfulapi.net/resource-naming/

2021-03-04 12:36 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
loadInitialData에 빈배열의 인자를 넘기라는 의미는 아니었습니다 😅

```suggestion
  useEffect(() => {
    dispatch(loadInitialData());
  }, []);
```

위와 같이 useEffect에 두번째 인자로 빈 배열을 넘길 경우, 최초 렌더 이후에 한번만 첫번째 인자로 넘기는 콜백을 실행하라는 의미입니다~ 문서를 한번 보시고 이해가 안되는 부분이 있다면 말씀주세요!

- https://ko.reactjs.org/docs/hooks-reference.html#useeffect

2021-03-04 14:40 UTC, ParkYoungHoon commented on src/RestaurantsPage.jsx
> +  });
ㅎㅎ.. 문서 읽어보겠습니다. 😅

2021-03-05 14:33 UTC, Kihyun92 requested changes
TDD cycle 을 지켜서 작업을 해보시면 좋을것 같아요!

조금 오래 걸릴 수 있지만, 잘못된 로직을 바로바로 알 수 있으니까요

2021-03-05 14:33 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +  }
handleClick을 이제 사용해주는 일만 남았군요 ㅎㅎ

그리고 지금 상황은 loadDetailRestaurant를 dispatch 하기 전에 레스토랑 id 정보를 업데이트하도록 다른 dispatch를 해주고 있는 것 같아요. 레스토랑 정보를 가져오려면 항상 두개의 dispatch를 해야할 것 같군요.

loadDetailRestaurant에 restaurantId 를 넘겨주면 어떤가요?

2021-03-06 15:24 UTC, Kihyun92 requested changes
꾸준히 진행해주시는 모습이 좋습니다! 👍🏼 

올라온 과제 풀이 영상을 보고 진행해보셔도 좋을 것 같네요 :)

2021-03-06 15:24 UTC, Kihyun92 commented on src/actions.js
> +export function setmenus(restaurantId) {
`setMenus`와 같이 [lower camel case](https://wiki.c2.com/?LowerCamelCase)로 작성해보시는게 좋을 것 같아요~

2021-03-06 15:24 UTC, Kihyun92 commented on src/actions.js
> +    }
이 로직들이 지금도 필요한가요? 🤔

2021-03-06 15:24 UTC, Kihyun92 commented on src/actions.js
> +    });
```suggestion
    const restaurantMenus = await fetchDetailRestaurant({
      restaurantId,
    });
```
이렇게 생략할 수 있을 것 같아요 ㅎㅎ

2021-05-16 10:06 UTC, merged