Set Router
CodeSoom/week6-assignment-1 pull request #46
Opened 2021-03-03 14:36 UTC by gimsesu

1. dev server에서 모든 요청이 'index.html'로 가도록 수정
2. RestaurantsPage 컴포넌트 생성

2021-03-04 18:06 UTC, moonkii requested changes
![image](https://user-images.githubusercontent.com/46776329/110008807-82843680-7d5f-11eb-8069-b347a7536845.png)

작게 잘 시작하고 있는 것 같아요.

이번주차 과제의 핵심은 라우터라서 라우터에 대해 테스트 코드와 구현을 신경써서 해주시면 될 것 같아요 ;)

2021-03-04 18:06 UTC, moonkii commented on src/App.test.jsx
> +  context('requests HomePage', () => {
`context` 는 상황을 나눌 때 사용하고 내부에 `it` 이 있어야해요.

2021-03-04 18:06 UTC, moonkii commented on src/RestaurantsPage.jsx
> +  });
`useEffect` 를 찾아보시면 두번 째 인자가 있을거에요 ;)

2021-03-04 18:06 UTC, moonkii commented on src/RestaurantsPage.test.jsx
> +  expect(dispatch).toBeCalled();
`dispatch` 가 call 되는 것도 테스트가 있으면 좋을 것 같아요.

2021-03-05 13:28 UTC, gimsesu commented on src/RestaurantsPage.jsx
> +  });
useEffect의 문서를 봐도 아직 정확히 파악이 잘 되지 않습니다 ^^; 다시 한 번 살펴보겠습니당

2021-03-05 13:29 UTC, gimsesu commented on src/RestaurantsPage.test.jsx
> +  expect(dispatch).toBeCalled();
넵 이것도 추가해보겠습니다!

2021-03-05 13:35 UTC, gimsesu commented on src/index.jsx
> +      <BrowserRouter>
App.test.jsx에서 About 페이지의 테스트가 예상대로 진행되지 않아 애를 먹었습니다. 

```jsx
 expect(element).toHaveTextContent()

    Expected element to have text content:
      어바웃
    Received:
      HomeAboutRestaurants

      26 |       ));
      27 | 
    > 28 |       expect(container).toHaveTextContent('어바웃');
```

이 에러가 발생할 때, `<BrowserRouter>`를 App.jsx 에 위치해 있었습니다.

혹시나 싶어 강의를 다시 보고 index.jsx로 `<BrowserRouter>`를 옮기니 정상적으로 테스트가 통과됐습니다.

어떤 부분을 살펴봐야 할까요? 🤔 

테스트.. 정말 쉽지 않습니다 ㅠ

2021-03-05 15:11 UTC, moonkii commented on src/RestaurantsPage.test.jsx
> +  expect(dispatch).toBeCalled();
테스트 코드만 봤을 때 왜 `dispatch` 가 call 되는지 어떻게 알 수 있을까요?

테스트 코드는  설명서와도 같아요. 테스트 코드만 보더라도 대략적으로 파악이 다 가능해야해요.

지금 상태에서는 뭔가 dispatch 된다는  것만  알 수 있을 뿐 '왜' 는 알수가 없죠.

예를들어 `it('loads something..', () =>  { ... });` 이런식으로만 추가해주더라도 아 처음에 페이지가 렌더링되면 ~~ 를  불러오는  구나 알수  있어요.

2021-03-05 15:15 UTC, moonkii commented on src/index.jsx
> +      <BrowserRouter>
`BrowserRouter`  가 App 전체를 감싸주고 있어야 작동 할거에요.

공부하실  때 강의 뿐만  아니라  공식 문서도 살펴보시면 좋을 것 같아요!

2021-03-05 15:17 UTC, moonkii commented on src/App.test.jsx
> +  context('requests path /', () => {
`context` 는 `when, with, without` 을로 표현하시는게 좋아요.

참고: 
- https://www.betterspecs.org/#contexts

2021-05-16 10:06 UTC, merged