Restaurant router
CodeSoom/week6-assignment-1 pull request #47
Opened 2021-03-04 11:44 UTC by datalater

6주차 과제 제출합니다.

## 진행상황

### 2020.03.04(목)

* 헤더 TDD로 구현
* HomePage TDD로 구현
* AboutPage TDD로 구현
* Restaurants TDD로 구현
* RestaurantInfo TDD로 구현

## TODO

* 레스토랑 상세 페이지 렌더링 오류 해결하기. 라우터로 레스토랑 상세 페이지로 이동했을 때 레스토랑 상세 정보를 불러오지 못한다. 콘솔로 찍어보니 라우터로 이동 후에 컴포넌트가 상태를 받아서 업데이트 되기 전에 먼저 렌더링이 되는 것 같다. 아직 정확한 이유는 모르겠는데 아마 useEffect와 관련이 있지 않을까 싶다.

## 궁금한 점

## 코드 리뷰 모음

## 메타인지

### 내가 모르는 것은 무엇인가

### 내가 알게 된 것은 무엇인가

### 어떻게 하면 더 나을까
 
## 주간회고

2021-03-04 12:24 UTC, Kihyun92 requested changes
오 빠르게 진행해보셨네요! 좋습니다 👍🏼

2021-03-04 12:24 UTC, Kihyun92 commented on src/RestaurantInfoContainer.jsx
> +        {menuItems.map((item) => (
구조분해할당을 해줘도 좋겠네요~

2021-03-04 12:24 UTC, Kihyun92 commented on src/RestaurantInfoPage.jsx
> +export default function RestaurantInfoPage() {
현재 이 컴포넌트는 단순히 `RestaurantInfoContainer`로 연결만 해주고 있는 것 같네요~ 어떤 역할을 할 예정인가요?

2021-03-04 12:24 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +    dispatch(loadRestaurantInfo());
`loadRestaurantInfo`를 dispatch 하기 전에 레스토랑 id 정보를 업데이트하도록 다른 dispatch를 해주고 있는 것 같아요. 레스토랑 정보를 가져오려면 항상 두개의 dispatch를 해야할 것 같군요.

`loadRestaurantInfo`에 `restaurantId` 를 넘겨주면 어떤가요?

2021-03-05 07:55 UTC, datalater commented on src/RestaurantInfoContainer.jsx
> +        {menuItems.map((item) => (
넵~ 👍

2021-03-05 07:56 UTC, datalater commented on src/RestaurantInfoPage.jsx
> +export default function RestaurantInfoPage() {
음 라우팅으로 보여줄 화면 컴포넌트 이름을 일관되게 Page로 하다보니 이렇게 됐네요.

2021-03-05 08:01 UTC, datalater commented on src/RestaurantsContainer.jsx
> +    dispatch(loadRestaurantInfo());
오 처음에 그렇게 하려고 했었는데요.

```jsx
export default function RegionsContainer() {
  const dispatch = useDispatch();

  const regions = useSelector(get('regions'));
  const selectedRegion = useSelector(get('selectedRegion'));

  function handleClick(regionId) {
    dispatch(selectRegion(regionId));
    dispatch(loadRestaurants());
  }
```

기존코드가 위와 같이 되어 있길래 비슷한 구조로 했습니다.

그러나 위 코드는 regionId를 미리 저장해 두어야 하지만, 현재 레스토랑 상세 정보를 불러오는 건 굳이 레스토랑 id를 저장할 필요는 없기 때문에 차이점이 있겠네요.

restaurantId를 넘겨줘도 될 것 같네요. 

흠 이 부분은 지금 오류가 난 다른 부분부터 작업하고 리팩토링하면 될 것 같은데 어떻게 생각하시나요?

2021-03-05 08:50 UTC, datalater commented on src/RestaurantInfoPage.jsx
> +export default function RestaurantInfoPage() {
항상 restaurantId를 파라미터로 받고 받은 레스토랑 아이디로 상세페이지를 불러오도록 useEffect 코드를 추가했습니다.

2021-03-05 08:54 UTC, datalater commented
![image](https://user-images.githubusercontent.com/8105528/110091032-573f2d00-7ddb-11eb-97af-b62dbcc0914b.png)

CI에서도 실패하듯이, 로컬에서도 `/restaurants/1`과 같이 URL로 레스토랑 id를 넣어서 상세 정보를 보려고 하면 오류가 납니다.

그런데 `/restaurants`에서 직접 지역과 분류를 선택해서 나온 식당을 클릭하면 url이 `/restaurants/1`로 바뀌면서 정상적으로 나옵니다.

계속 알아보고 있는데, 왜 직접 url을 타이핑할 때만 오류가 나는지 잘 모르겠네요 🤔

관련해서 개발자도구 network 창 사진을 첨부합니다!

# 직접 `/restaurants/1`로 입력한 경우

![image](https://user-images.githubusercontent.com/8105528/110091337-b0a75c00-7ddb-11eb-89c0-b05a1f1dd957.png)

# 레스토랑 이름을 클릭해서 `/restaurants/1`로 라우팅된 경우

![image](https://user-images.githubusercontent.com/8105528/110091488-d5033880-7ddb-11eb-8aab-94291cf003af.png)

2021-03-05 14:53 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +    dispatch(loadRestaurantInfo());
넵 일단 오류를 잡는게 먼저죠 👍🏼

2021-03-05 15:17 UTC, Kihyun92 commented
경로 문제 같군요! 관련해서 동료들이 슬랙으로 의논한 부분 참고해보시면 좋을 것 같습니다 :)

https://codesoom-group.slack.com/archives/C01JEHR319T/p1614692515012800

2021-03-05 15:23 UTC, Kihyun92 requested changes

2021-03-05 15:23 UTC, Kihyun92 commented on src/NotFoundPage.test.jsx
> +      <MemoryRouter>
이 테스트에서는 MemoryRouter로 감싸주지 않아도 될 것 같군요!

2021-03-05 15:23 UTC, Kihyun92 commented on src/RestaurantInfoPage.jsx
> +  });
`useEffect`에 두번째 인자를 넘겨주면 좋을 것 같네요!

2021-03-05 15:23 UTC, Kihyun92 commented on src/RestaurantsContainer.test.jsx
> +    ));
중복 되는 로직이 있는 것 같네요 개선해보면 좋겠습니다 :)

그리고 이 테스트도 MemoryRouter로 감싸줄 필요가 있을까요?

2021-03-06 01:17 UTC, datalater commented on src/NotFoundPage.test.jsx
> +      <MemoryRouter>
그렇네요 불필요한 부분이므로 삭제하겠습니다!

2021-03-06 01:47 UTC, datalater commented on src/RestaurantsContainer.test.jsx
> +    ));
여기에서는 RestaurantsContainer가 보여주는 화면에서 레스토랑 이름을 클릭하면 react rotuter의 `<Link>` 컴포넌트를 사용하므로 MemoryRouter가 필요한 것 같습니다.

2021-03-06 01:50 UTC, datalater commented on src/RestaurantInfoPage.jsx
> +  });
```jsx
export default function RestaurantInfoPage() {
  const dispatch = useDispatch();

  const { restaurantId } = useParams();

  useEffect(() => {
    dispatch(loadRestaurantInfo(restaurantId));
  }, []);

  return (
    <RestaurantInfoContainer />
  );
}
```

위와 같이 변경했습니다. 저렇게 하면 되겠죠? 디펜더시가 걸려 있는 state가 없어서 빈 배열로 넣었습니다!

2021-03-06 02:06 UTC, datalater commented
> 경로 문제 같군요! 관련해서 동료들이 슬랙으로 의논한 부분 참고해보시면 좋을 것 같습니다 :)
> 
> https://codesoom-group.slack.com/archives/C01JEHR319T/p1614692515012800

정말 감사합니다. 이 챗을 놓쳤었네요 😢 

완전히 이해되었습니다. 속이 다 시원하네요 ㅎㅎ [알게 된 내용을 정리](https://github.com/CodeSoom/react-week6-assignment-1/pull/47#issue-584740956)했습니다.

2021-03-06 15:31 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다. 빠르게 잘 완성해주신 것 같아요! 👍🏼 

이번 과제를 통해 무엇을 배웠나요? 더 알고 싶은 부분이 있나요?

슬랙 채널에 회고 남겨주시면 머지하도록 하겠습니다 :)

2021-03-06 15:31 UTC, Kihyun92 commented on src/actions.js
> +    }
restaurantId 가 없는 경우에 대해 예외처리를 해보셨군요! 좋습니다 ㅎㅎ

RestaurantInfoPage에서 dispatch 하기 전에 restaurantId가 없는 경우 호출하지 않도록 처리하는 것에 대해선 어떻게 생각하시나요? 🤔

2021-03-07 07:27 UTC, datalater commented on src/actions.js
> +    }
그렇네요. dispatch 전에도 예외 처리를 해주는 것이 낫겠습니다 ㅎㅎ

2021-03-07 07:34 UTC, datalater commented on src/actions.js
> +    }
흠 작성해보니 이런 형태가 될 것 같습니다.

```jsx
export default function RestaurantInfoPage() {
  const dispatch = useDispatch();

  const { restaurantId } = useParams();

  if (!restaurantId) {
    return (
    <RestaurantInfoContainer />
  );
  }

  useEffect(() => {
    dispatch(loadRestaurantInfo(restaurantId));
  }, []);

  return (
    <RestaurantInfoContainer />
  );
}
```

return 코드가 결국 중복되네요. 어차피 `RestaruantInfoContainer`가 레스토랑 정보가 없는 경우에 대해서 예외처리를 해주기 때문에 새로운 예외처리 화면을 만들어줄 필요가 없을 것 같아요.

그러면 결국 이전 코드와 동일하게 해도 상관 없을 것 같은데 어떻게 생각하시나요? 🤔

2021-03-07 08:26 UTC, datalater commented
[질문](https://github.com/CodeSoom/react-week6-assignment-1/pull/47#discussion_r588987346) 하나 남겼습니다.

그리고 [6주차 회고](https://www.notion.so/jayday/6-afa67e02ed074de0a7c6df465730add8) 올려요.

2021-03-07 13:14 UTC, Kihyun92 commented on src/actions.js
> +    }
```javascript
export default function RestaurantInfoPage() {
  const dispatch = useDispatch();

  const { restaurantId } = useParams();

  useEffect(() => {
    if (restaurantId) {
      dispatch(loadRestaurantInfo(restaurantId));
    }
  }, []);

  return (
    <RestaurantInfoContainer />
  );
}
```

위와 같은 형태를 의도해서 말씀드리긴 했습니다 ㅎㅎ

2021-03-08 09:42 UTC, datalater commented on src/actions.js
> +    }
아하!! `useEffect` 안에 if문을 넣을 생각을 못했네요 ㅎㅎ 알려주셔서 감사합니다!

2021-03-08 12:40 UTC, merged