6주차_ 과제1 [레스토랑 상세 페이지 구현하기]
CodeSoom/week6-assignment-1 pull request #49
Opened 2021-06-07 05:04 UTC by seong-dodo

안녕하세요. 

6주차 과제 : 레스토랑 상세 페이지 구현하기

- 라우팅의 이해
-  React router 사용하기

이번 과제에서는 `테스트 시나리오 네이밍`과 `커밋 메시지` 작성에 좀 더 신경 써서 작성해보도록 하겠습니다.
그리고 피드백 주시는 부분도 최대한 반영할 수 있도록 과제를 진행 하겠습니다.

> 1차 라우터 작업
- RestaurantsPage로 관심사 분리 
- MyComponent 만들기
- HomePage 만들기
- AboutPage 만들기
- NotFoundPage 만들기

> 2차 React Router 라이브러리 이용해서 고도화 작업
- 레스토랑 상세 페이지 구현하기

이렇게 차근차근 진행 해보도록 하겠습니다

2021-06-07 12:31 UTC, Kihyun92 requested changes
빠른 PR 너무 좋네요 👍🏼 👍🏼 

TDD cycle도 잘 지키며 해주시는 것 같습니다😄

2021-06-07 12:31 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('without path', () => {
잘못된 경로로 접근한 경우를 테스트해주셨군요 👍🏼 

`without path`도 좋지만, `with invalid path`와 같이 적절하지 않다는 의미를 더 드러내줘도 좋을 것 같아요~

2021-06-07 12:31 UTC, Kihyun92 commented on src/RestaurantsPage.jsx
> +  });
useEffect hook 에 두번째 인자를 넘겨주어서 보다 의도하는 경우에 실행해줄 수 있습니다.

초기 데이터는 최초 렌더시 한번만 호출해주기위해 두번째 인자로 빈 배열을 넘겨주는건 어떨까요?

- https://ko.reactjs.org/docs/hooks-reference.html#useeffect

2021-06-07 13:18 UTC, seong-dodo commented on src/App.test.jsx
> +  context('without path', () => {
네 수정하겠습니다!! 코드를 작성하다보니 말씀해주신 `with invalid path`가 더 적절한 것 같아요~~ 👍

2021-06-07 13:53 UTC, seong-dodo commented on src/RestaurantsPage.jsx
> +  });
넵 감사합니다~ 피드백 반영하여 수정하였습니다 😄 😄 😄

2021-06-07 14:14 UTC, seong-dodo commented
안녕하세요.

제가 `RestaurantsContainer`에 대한 테스트 코드 추가하고 기능을 구현해보았습니다.
 `RestaurantsContainer` 컴포넌트에서 레스토랑 목록에 <Link />를 연결해서 `RestaurantDetilPage`로 이동하는 부분에 대한 테스트 코드를 작성을 하였습니다. 제가 생각할 때 path : `/restaurants/Id`를 만들어줄거라고 정의는 했으나 유효하지 않은 경로니깐 `NotFoundPage`로 넘어갈 것 같아서  아래와 같이 `'Not Found'` 텍스트가 보일 것이라고 생각하고 테스트를 만들었습니다.

```javascript
context('with path /restaurants/Id', () => {
    it('renders restaurantDetilPage', () => {
      const { container } = render((
        <MemoryRouter initialEntries={['/restaurants/1']}>
          <RestaurantsContainer />
        </MemoryRouter>
      ));

      expect(container).toHaveTextContent('Not Found');
      // expect(container).toHaveTextContent('마법사주방');
      // expect(container).toHaveTextContent('메뉴');
    });
  });
```

그런데 아래와 같은 에러가 발생하였습니다.
제가 생각했던데로 `NotFoundPage`로 연결이 되지 않았다고 알려주는데 제가 테스트 코드를 잘 못 작성한 거 같습니다.
제가 깨우치지 못한 부분이 무엇인지 조언 부탁드립니다 🙏 
![image](https://user-images.githubusercontent.com/68280407/121031695-8c498a00-c7e5-11eb-9b3a-fda77f320df2.png)

2021-06-08 14:08 UTC, Kihyun92 requested changes

2021-06-08 14:08 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +    const resultInformation = await fetchRestaurantInformation(props.match.params.id);
`useParams` hook 을 사용하면 조금 더 편하게 match.param 정보를 가져올 수 있습니다~

- https://reactrouter.com/web/api/Hooks/useparams

2021-06-08 14:08 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +  });
아직 작업 중이신 것 같지만, 추후 스토어에서 관리해도 좋을 것 같네요~

2021-06-08 14:08 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
>          </li>
구조 분해 할당을 사용해도 좋을 것 같군요~

2021-06-08 14:11 UTC, Kihyun92 commented
> 안녕하세요.
> 
> 제가 `RestaurantsContainer`에 대한 테스트 코드 추가하고 기능을 구현해보았습니다.
> `RestaurantsContainer` 컴포넌트에서 레스토랑 목록에 를 연결해서 `RestaurantDetilPage`로 이동하는 부분에 대한 테스트 코드를 작성을 하였습니다. 제가 생각할 때 path : `/restaurants/Id`를 만들어줄거라고 정의는 했으나 유효하지 않은 경로니깐 `NotFoundPage`로 넘어갈 것 같아서 아래와 같이 `'Not Found'` 텍스트가 보일 것이라고 생각하고 테스트를 만들었습니다.
> 
> ```js
> context('with path /restaurants/Id', () => {
>     it('renders restaurantDetilPage', () => {
>       const { container } = render((
>         <MemoryRouter initialEntries={['/restaurants/1']}>
>           <RestaurantsContainer />
>         </MemoryRouter>
>       ));
> 
>       expect(container).toHaveTextContent('Not Found');
>       // expect(container).toHaveTextContent('마법사주방');
>       // expect(container).toHaveTextContent('메뉴');
>     });
>   });
> ```
> 
> 그런데 아래와 같은 에러가 발생하였습니다.
> 제가 생각했던데로 `NotFoundPage`로 연결이 되지 않았다고 알려주는데 제가 테스트 코드를 잘 못 작성한 거 같습니다.
> 제가 깨우치지 못한 부분이 무엇인지 조언 부탁드립니다 🙏
> ![image](https://user-images.githubusercontent.com/68280407/121031695-8c498a00-c7e5-11eb-9b3a-fda77f320df2.png)

여러 테스트를 고려해보시는 것 같아 좋네요 👍🏼 👍🏼 

`App` 컴포넌트의 경우엔 유효하지 않은 경로로 접근시 라우트 처리가 되지만, `RestaurantsContainer`에서는 path 에 따른 라우팅 처리가 없기 때문에 그렇습니다~ 

단순히 초기 path 값을 통해서는 의도하신대로 처리할 수 없을 것 같아요.

2021-06-09 12:27 UTC, seong-dodo commented on src/RestaurantsContainer.jsx
>          </li>
넵~ 감사합니다! 구조 분해 할당을 사용해보았습니다~~

2021-06-09 12:28 UTC, seong-dodo commented on src/RestaurantDetailPage.jsx
> +  });
넵! 스토어로 관리할 수 있도록 변경해보겠습니다 😆

2021-06-10 03:52 UTC, seong-dodo commented on src/RestaurantDetailPage.jsx
> +    const resultInformation = await fetchRestaurantInformation(props.match.params.id);
감사합니다. 수정해보았습니다 👍 😄

2021-06-10 15:34 UTC, Kihyun92 requested changes
잘 진행하고 계신 것 같군요! 👍🏼👍🏼

2021-06-10 15:34 UTC, Kihyun92 commented on src/App.test.jsx
> +import RESTAURANDETAIL from '../fixtures/restaurantDetail';
대문자로 표현 할거라면 `RESTAURANT_DETAIL`과 같이 구분해주는건 어떨까요? 😄

2021-06-10 15:34 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +  );
삼항연산자로 레스토랑 정보가 없는 경우에 대해서 처리해주신 것 같아요!

```javascript
if (restaurantDetail === null) {
  return <div>404 Not Found</div>
}

return (
   <div>
        <h1>{restaurantDetail.name}</h1>
        <p>
          주소:
          {' '}
          {restaurantDetail.address}
        </p>
        <h2>메뉴</h2>
        <ul>
          {restaurantDetail.menuItems.map((menuItem) => (
            <li key={menuItem.id}>
              {menuItem.name}
            </li>
          ))}
        </ul>
      </div>
    );
```
위 예시와 같이 `Guard Clauses`를 사용해서 처리해주는 것도 좋을 것 같네요~

- https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2021-06-10 15:34 UTC, Kihyun92 commented on src/RestaurantsContainer.test.jsx
> +  context('with path /restaurants/:id', () => {
context는 with path <=> without path와 같이 문맥이 서로 다른 경우에 사용합니다.

그외의 경우에는 describe로 처리해도 좋을 것 같아요~

2021-06-11 03:38 UTC, seong-dodo commented on src/App.test.jsx
> +import RESTAURANDETAIL from '../fixtures/restaurantDetail';
수정해보았습니다. 오타도 있었네요 ㅜㅜ 감사합니다 👍 😄👍 😄👍 😄

2021-06-11 07:12 UTC, seong-dodo commented on src/RestaurantsContainer.test.jsx
> +  context('with path /restaurants/:id', () => {
넵 ~ 감사합니다 😃

2021-06-11 07:48 UTC, seong-dodo commented on src/RestaurantDetailPage.jsx
> +  );
안녕하세요. 
피드백을 받고 삼항연산자로 표현한 부분을 바꾸어 보았습니다.
그런데 말씀해주신 예시처럼 함수를 만들어서 변경하지 않고😅😅😅, 기존에 만들었던 `NotFoundPage`를 활용해보았습니다;;;

생각을 해보니 Page라는 이름이 붙은 컴포넌트들은 각각 프레젠테이션컴포넌트로써 역활을 하고 있는데,  현재 제가 만든`restaurantDetailPage`에는 로직이 포함되어 있어 컨테이너 컴포넌트 역활을 하고있습니다.
컨테이너 컴포넌트로 분리하는게 좋을지.. 아니면 말씀해주신 `Guard Clauses`을 사용해서 `restaurantDetailPage` 컴포넌트에서 모든걸 처리하도록 표현해야할지 고민이 되어 글 남겨봅니다.

```
function getPayAmount() {
  if (isDead) return deadAmount();
  if (isSeparated) return separatedAmount();
  if (isRetired) return retiredAmount();
  return normalPayAmount();
}
```

2021-06-11 15:21 UTC, Kihyun92 commented on src/RestaurantDetailPage.jsx
> +  );
저 조건에 걸리는 경우가 not found 도 있지만, 데이터를 로딩해오는 경우도 있을 것 같아요~ 이 경우엔 NotFound 페이지를 보여주는게 맞을지 고민해봐도 좋을 것 같네요 😊

2021-06-11 15:35 UTC, seong-dodo commented on src/RestaurantDetailPage.jsx
> +  );
아항!! 감사합니다 😀 😀 😀 
그럼 로딩해주는 경우로 생각을 해보겠습니다 👍 👍  👍  👍  👍

2021-06-11 15:36 UTC, Kihyun92 requested changes

2021-06-11 15:36 UTC, Kihyun92 commented on src/App.jsx
> +        <Route component={NotFoundPage} />
전반적으로 `**Page`라는 처리가 필요할까요? 

page 들이라는 의도를 드러내고 싶다면 pages 폴더와 같이 처리해주고 컴포넌트 네이밍은 역할만 드러내 주는 방법도 있을 것 같아요~

2021-06-11 15:36 UTC, Kihyun92 commented on src/RestaurantDetailPage.test.jsx
> +      ));
반복되는 렌더 관련 로직은 함수로 추출해줘도 좋을 것 같아요~

2021-06-12 13:41 UTC, seong-dodo commented on src/RestaurantDetailPage.test.jsx
> +      ));
넵 😀  수정해보겠습니다.

2021-06-12 13:49 UTC, seong-dodo commented on src/App.jsx
> +        <Route component={NotFoundPage} />
아항😀 감사합니다. 그런방법이 있었군요!!!👍 👍 👍 👍 👍

2021-06-12 16:01 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~
TDD에 많이 익숙해지신 것 같아요 ㅎㅎ

과제 풀이 영상 꼭 봐보시고, 이번주에 어떤걸 배웠는지, 어떤걸 더 배우고 싶은지 정리해보셔도 좋을 것 같네요 😊

슬랙 채널에 회고 올려주시면 머지하겠습니다~~

2021-06-13 13:33 UTC, merged