Kcena 6주차 과제1 [레스토랑 상세 페이지 구현하기] 제출
CodeSoom/week6-assignment-1 pull request #5
Opened 2020-07-07 07:53 UTC by Kwakcena

6주차 과제1 [레스토랑 상세 페이지 구현하기] 제출합니다.

2020-07-07 12:07 UTC, hannut91 commented
잘 진행하고 계신 것 같아요 ㅎㅎ 계속 진행해주세요 😀

2020-07-08 09:01 UTC, Kwakcena commented
지역과 분류를 선택하여 나온 레스토랑 이름 목록에 `Link` 태그를 걸었습니다.

이를 클릭하면 해당 레스토랑의 id가 url에 포함된 주소로 이동합니다. 예를 들어 다음과 같습니다. `restaurants/1` 

이에 대한 `Route` 는 App 컴포넌트에서 `<Route path="/restaurants/:id" component={RestaurantPage} />` 와 같이 설정하여 id값을 match 객체로 읽을 수 있도록 했는데,

문제는 레스토랑을 클릭해서 들어가면 제대로 된 레스토랑 정보가 나오지만, 직접 url을 쳐서 들어가면 에러가 나타납니다.

이 문제를 어떻게 해결해야 할까요 ?

2020-07-08 10:56 UTC, Kwakcena commented
다른 분의 코드리뷰를 통해서 `base path` 문제를 해결했습니다.

그런데 이유가 무엇때문인지는 아직 알지 못했습니다... 

왜 index.html에 `/main.js` 라고 하면 `restaurants/1` 을 직접 쳐서 들어갈 수 있고, `main.js` 라 하면 안되는건가요...?

참고할만한 자료가 있다면 부탁드립니다.

2020-07-08 13:22 UTC, hannut91 commented
그 부부는 절대경로 상대경로의 차이인 것 같아요

2020-07-08 14:19 UTC, hannut91 requested changes
`main.js`에 대한 문제는 `index.html`의 `head`에 
`<base href="/">`를 추가해서 해결할 수도 있습니다.

See also
  - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

2020-07-08 14:19 UTC, hannut91 commented on src/App.test.jsx
> +  beforeEach(() => {
`dispatch.mockClear`를 해주셔야 의도치 않게 테스트가 동작하는 것을 방지할 수 있어요

2020-07-09 11:24 UTC, Kwakcena commented
다시 제출하는 방법 말고 이미 제출한 PR에 대해 테스트를 다시 돌리는 방법을 모르겠어서 수정하고 제출합니다... 무슨 키워드로 찾아봐야 할지도 잘 모르겠어서...

이번에 추가한 것은 restaurant 정보를 출력할 때 loading page를 구현해봤습니다. 감사합니다.

2020-07-09 11:47 UTC, hannut91 requested changes

2020-07-09 11:47 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +    it('is false show restaurant page', () => {
`renders restaurant`은 어떨까요?

2020-07-09 11:47 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +    it('is true show loading page', () => {
`renders loading`은 어떨까요?

2020-07-09 11:47 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +      }));
각 컨텍스트마다 달라지는 것은 beforeEach로 표현하면 더 좋을 것 같아요.

```js
describe('RestaurantContainer', () => {
  function renderRestaurantContainer() {
    return render((
      <MemoryRouter>
        <RestaurantContainer />
      </MemoryRouter>
    ));
  }

  context('when loading is done', () => {
    beforeEach(() => {
      useSelector.mockImplementation((selector) => selector({
        restaurant,
        loading: false,
      }));
    });

    it('is false show restaurant page', () => {
      const { container } = renderRestaurantContainer();

      expect(container).toHaveTextContent(restaurant.name);
    });
  });
  
  context('when is loading', () => {
    beforeEach(() => {
      useSelector.mockImplementation((selector) => selector({
        restaurant,
        loading: true,
      }));
    })

    it('renders loading', () => {
      const { container } = renderRestaurantContainer();

      expect(container).toHaveTextContent('Loading...');
    });
  });
});
```

2020-07-09 11:47 UTC, hannut91 commented on src/RestaurantPage.jsx
> +  }, []);
`setLoading()`을 `loadRestaurant`액션에서 dispatch하는건 어떨까요?

`setRestaurantId`할 필요 없이 `loadRestaurant(id)`이렇게 하는건 어떨까요?

2020-07-10 03:03 UTC, Kwakcena commented on src/RestaurantContainer.test.jsx
> +      }));
아하🤔 이부분을 어떻게 리팩토링 해야할까 고민했는데 저렇게 처리하면 좋을것 같군요 !

2020-07-10 03:03 UTC, Kwakcena commented on src/RestaurantPage.jsx
> +  }, []);
음... 다른 `load` 함수처럼 인자를 전달하지 않으려 맞췄는데 굳이 그럴 필요가 없었으려나요 ?

2020-07-10 12:39 UTC, hannut91 approved these changes
변경사항이 있을 때 조금씩 변경해가면서 피해를 최소화하는 부분이 좋네요! 고생하셨습니다. 아샬님의 과제풀이를 보며 복습해주면 좋을 것 같아요!

2020-07-10 12:39 UTC, hannut91 commented on src/RestaurantContainer.test.jsx
> +  context('when is loading', () => {
`when loading`이 맞는 것 같구요 ㅎㅎ..제가 잘못썻네요

2020-07-10 12:39 UTC, hannut91 commented on src/reducer.test.js
> +      const regions = [REGIONS[0]];
이거는 크게 의미가 없을 것 같아요. fixture를 사용하실꺼면 그냥 사용하면 좋을 것 같아요

```js
const state = reducer(initialState, setRegions(REGIONS));

expect(state.categories).toEqual(REGIONS);
```

2020-07-10 12:39 UTC, hannut91 commented
이번 과제를 통해 무엇을 배우셨나요? 더 배우고 싶은게 있으신가요?

2020-07-12 06:03 UTC, Kwakcena commented
# 내가 한 것(Fact)

- 레스토랑 상세 페이지 구현하기.
- `react-router-dom` 을 이용해서 리액트를 이용해 라우팅하기.
- 데이터를 `fetch` 하는 동안 화면에 보여 줄 `loading` 페이지 구현.
- `<base>` 태그를 사용하여 baseURL 문제를 해결.

# 느낀 점(Feelings)

- 과제를 수행하면서 라우팅 뿐만 아니라 저번시간에 배운 비동기를 활용한 과제라는 점에서 복습도 할 수 있었고 , 라우팅도 적용할 수 있었다.
- 수행한 과제 중에서 가장 재미있었다.
- url에 직접 `restaurants/1` 과 같이 검색하여 레스토랑 정보를 가져올 때 절대경로와 상대경로의 차이로 인해 발생하던 에러를 해결함에 있어 `<base>` 태그를 이용해 해결했는데, 다른 분은 웹팩의 설정을 통해 해결했다는 리뷰를 보았다. 웹팩 설정을 잘 할줄 알아야 겠다는 느낌을 받았다.
- 이번에 수행한 TDD는 사이클을 나름 잘 지킨 것 같아 뿌듯하다.
- 영어로 테스트를 작성하고 싶은데 참 어렵다. 😭
- 과제의 첫 코드로 주어진 테스트 코드를 보고 감탄했다.

# 배운 점(Finding)

1. `<base>` 태그를 사용하면 기준 절대경로를 정할 수 있다. 이후로는 웹 페이지와 연결되는 링크 주소를 상대경로로 간소화 할 수 있다.
2. `<a>` 태그를 사용했을 때와 `<Link>` 를 사용할 때의 차이점을 알 수 있었다. 페이지 자체의 리로딩 없이 하려면 `<Link>` 를 써야 한다.
3. `<Route>` 컴포넌트의 `component` prop으로 넣어준 컴포넌트에 `match, location, history` 라는 3개의 prop을 넘겨준다는 것을 배웠다.
4. `<Route path="restaurants/:id" ...>` 에서 경로 부분의 `:id` 는 URL 파라미터를 정의할 때 사용하는 React Router의 문법임을 알 수 있었다. URL 파라미터가 포함된 경우 패턴 매칭에 의해 해당 파라미터는 `component` prop로 전달한 컴포넌트에서 `match.params.id` 와 같이 읽을 수 있다.
5. `<Route>` 에서 정확히 일치하는 URL에 대해서만 라우팅 하고 싶다면 `exact` 를 써야 함을 배웠다.

# 내가 할 것(Affirmation)

- 아샬님 풀이 강의 보면서 복습하기
- 지금은 간략하게 배운점을 썻지만 이걸 자세히 써서 블로그에 써야 하는데... 안쓰는 나.
- `api` 를 테스트 하던 코드에 대해 자세히 알아보자.

2020-07-12 06:22 UTC, hannut91 commented
블로그에 정리한걸 기대해봅니다!

2020-07-12 06:22 UTC, merged