6주차 1번째 과제
CodeSoom/week6-assignment-1 pull request #51
Opened 2021-06-07 12:33 UTC by yujong-lee

이전에 5주차에서 구성해둔 구조와 작성해둔 코드를 그대로 가져가면서 점진적으로 변화를 가하는 것이 더 배우는 것이 많을 것 같아 이전에 작성한 코드를 옮겼습니다. 이후 `RestaurantsPage`를 작성하는 것까지 진행했습니다. 나머지 라우팅작업은 내일부터 진행하려고 합니다. 감사합니다.

2021-06-08 14:42 UTC, Kihyun92 requested changes
리덕스 툴킷까지 벌써 적용해보셨군요 👍🏼 

TDD cycle도 잘 지키려 노력하시는 것 같습니다 😄

2021-06-08 14:42 UTC, Kihyun92 commented on src/components/ButtonList.jsx
> +export default function ButtonList({ names, onClick, selected }) {
`**List`도 좋지만 조금 더 간결하게 `Buttons`는 어떤가요?

`List`는 읽는 사람마다 다르게 해석될 수 있을 것 같아요 😊

2021-06-08 14:42 UTC, Kihyun92 commented on src/components/ButtonList.jsx
> +            {(selected === name) ? `${name}(V)` : name}
`name`은 항상 노출되는 정보 같은데, 뒤쪽에 추가되는 부분만 예외처리해주는건 어떨까요?

2021-06-08 14:42 UTC, Kihyun92 commented on src/components/CategoryListContainer.jsx
> +  const handleClick = (newCategoryName) => {
선택한 카테고리 이름을 인자로 받는건가요? 새롭게 선택됐다는 의도를 드러내신 것 같군요 ㅎㅎ
개인적으로는  new 라는 prefix가 조금 어색한 것 같아요~ selected와 같이 조금 더 의도를 드러내줘도 좋을 것 같네요 😊

그리고 `name`이 아니라 선택한 카테고리의 `id`를 넘겨 받으면 어떨까요? 
name으로만 관리되다보니 name으로 일치하는 카테고리를 가져와서 처리해주는 로직이 추가되는 것 같아요.

2021-06-08 14:42 UTC, Kihyun92 commented on src/components/RestaurantList.jsx
> +  const infos = useSelector((state) => state.restaurant.selectedRestaurants);
infos 도 좋지만, restaurants와 같이 조금 더 명확하게 해주는 것도 좋을 것 같네요~

2021-06-08 17:22 UTC, yujong-lee commented on src/components/CategoryListContainer.jsx
> +  const handleClick = (newCategoryName) => {
변수명은 바꿔줬고, `regions`가 `categories`와 같은 데이터 구조를 사용하게 하도록 수정하고, `Buttons`의 인터페이스를 수정하면서 `find`하는 코드를 제거했습니다.

2021-06-08 17:23 UTC, yujong-lee commented on src/components/RestaurantList.jsx
> +  const infos = useSelector((state) => state.restaurant.selectedRestaurants);
수정했습니다!

2021-06-08 17:27 UTC, yujong-lee commented on src/components/ButtonList.jsx
> +export default function ButtonList({ names, onClick, selected }) {
수정했습니다~

2021-06-08 17:37 UTC, yujong-lee commented on src/components/ButtonList.jsx
> +            {(selected === name) ? `${name}(V)` : name}
기존의 제 코드는 상황에 따라 `name`에 뭔가가 추가되는 의도가 잘 드러나지 않네요.
```js
      {items.map(({ id, name }) => {
        const suffix = (selected === name) ? '(V)' : '';

        return (
          <li key={id}>
            <button
              type="button"
              onClick={() => onClick({ id, name })}
            >
              {name + suffix}
            </button>
          </li>
        );
      })}
```
`name`은 항상 렌더되고, 그 뒤에 어떤 로직에 따라 결정된 `suffix`를 붙인다고 표현하는 코드는 어떤가요?

2021-06-09 07:33 UTC, yujong-lee commented
현재 레스토랑 상세페이지 구현만 남겨놓은 상태인데, 아까 DM으로 여쭤본 것과 같이 라우팅에서 문제가 발생하여 해결하지 못하고 있습니다.

```js
// 기존 코드

  return (
    <>
      <Link to="/">헤더</Link>

      <Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="/about" component={AboutPage} />
        <Route path="/restaurants" component={RestaurantsPage} />
        <Route component={NotFoundPage} />
      </Switch>
    </>
  );
```

위에서 `/restaurants/id` 경로만 추가하여 `restaurants/1` 같은 요청에 제대로 동작하는지 확인한 뒤, 그 요청에 돌려줄 컴포넌트를 작성하려고 했습니다.  아래는 그 내용입니다.


```js
  return (
    <>
      <Link to="/">헤더</Link>

      <Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="/restaurants/:id" component={RestaurantsPage} />
        <Route path="/restaurants" component={RestaurantsPage} />
        <Route path="/about" component={AboutPage} />
        <Route component={NotFoundPage} />
      </Switch>
    </>
  );
```

그런데 이렇게 하면 다른건 다 동작하는데 `/restaurants/1`로 들어가면 빈 화면만 출력됩니다.
콘솔에 찍히는 에러는 아래와 같습니다.

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.js, line 0)
[Error] Refused to execute http://localhost:8080/restaurants/main.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
```
예전에 프런트/백앤드를 함께 개발했을 때 CORS와 관련하여 비슷한 이슈가 있었던 것 같은데, 그때 제대로 이해하지는 못해서 좀 어렵습니다.

```js
  function temp() {
    return <p>1111</p>;
  }

  return (
    <>
      <Link to="/">헤더</Link>

      <Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="/restaurants/:id" component={temp} />
        <Route path="/restaurants" component={RestaurantsPage} />
        <Route path="/about" component={AboutPage} />
        <Route component={NotFoundPage} />
      </Switch>
    </>
  );
```
이런식으로 구성하면 `/restaurants`에서 버튼 하나만  클릭해도 
```
Access to fetch at 'https://eatgo-customer-api.ahastudio.com/restaurants?region=[object%20Object]&category=1' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

main.js:2 Uncaught (in promise) TypeError: Failed to fetch
```

위와 같은 오류가 발생합니다.

무엇이 문제일까요?

2021-06-09 13:48 UTC, Kihyun92 commented on src/components/ButtonList.jsx
> +export default function ButtonList({ names, onClick, selected }) {
ㅎㅎ넵 마찬가지로 수정해주면 좋겠네요! 👍🏼

2021-06-09 14:58 UTC, Kihyun92 requested changes
경로 문제인 것 같아요~ 
우리는 존재하지 않는 페이지로의 접근에 대한 처리를 위해 웹팩 설정에서 `historyApiFallback: true`로 해줬어요. 이로인해 없는 주소로 접근시 `index.html`로 리다이렉트 되는데요, 이때 경로가 잘못되어서 main.js 파일을 가져오지 못해서 발생하는 상황입니다.

`index.html`내에 `<script src="main.js"></script>` 부분을 `<script src="/main.js"></script>`과 같이 절대 경로로 변경해주세요. 이렇게 해주면 localhost:8080/main.js 와 같이 정상적인 경로로 스크립트를 로딩하게 됩니다~

참고:
- https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually
- https://ui.dev/react-router-cannot-get-url-refresh/

2021-06-09 14:58 UTC, Kihyun92 commented on src/components/ButtonList.jsx
> +            {(selected === name) ? `${name}(V)` : name}
```javascript
      {items.map(({ id, name }) => (
          <li key={id}>
            <button
              type="button"
              onClick={() => onClick({ id, name })}
            >
              {name}
              {selected === name ? '(V)' : null}
            </button>
          </li>
        ))}
```
저는 위와 같이 바로 사용하는걸 의도하긴 했지만, suffix를 통해서 조금 더 의도를 드러내고 싶다면 작성해주신 방법도 좋은 것 같습니다~! 😊

2021-06-09 14:58 UTC, Kihyun92 commented on toBeArrayOfObjectWith.js
> +      };
```suggestion
    return {
        pass: failingElement === null,
        message: () => (`expected ${this.utils.printReceived(failingElement)} to ${failingElement === null ? 'not' : ''} has ${this.utils.printExpected(keys.join(', '))} as property`),
      };
```

비슷한 객체인 것 같아 간단하게 수정해봤어요. 몇몇 부분에서만 예외처리가 필요하다면 이런식으로 처리해주는 것도 좋을 것 같네요

2021-06-09 14:58 UTC, Kihyun92 commented on src/components/ButtonList.test.jsx
> +      const { getAllByRole, queryByText } = render(
테스트마다 반복되는 코드들에 대해서 처리해주면 좋을 것 같아요~

2021-06-09 14:58 UTC, Kihyun92 commented on src/pages/HomePage.jsx
> +      </ul>
요소 간에 연관성을 위해 `Link` 태그를 `li`로 감싸주거나, `ul`을 다른 방식으로 처리해주는게 좋을 것 같아요~

2021-06-09 23:52 UTC, yujong-lee commented on toBeArrayOfObjectWith.js
> +      };
```js
    const { printReceived, printExpected } = this.utils;

    return {
      pass: failingElement === null,
      message: () => (
        `expected ${printReceived(failingElement)} to 
        ${failingElement === null ? 'not' : ''} has 
        ${printExpected(keys.join(', '))} as property`
      ),
    };
```

중복을 제거할 수 있었군요. 위와 같이 수정해줬습니다.

2021-06-10 00:17 UTC, yujong-lee commented on src/components/ButtonList.test.jsx
> +      const { getAllByRole, queryByText } = render(
이 부분이 좀 혼란스럽네요. 이미 `ButtonList`는 `Butons`로 바꾸었고, 위 코드도 이전에 수정을 했었는데 안바뀐건가요?
일단 현재 코드는 이렇습니다. https://github.com/CodeSoom/react-week6-assignment-1/blob/855f33a9ea96ff89574542481a1219d4e3f134d3/src/components/Buttons.test.jsx

2021-06-10 00:18 UTC, yujong-lee commented on src/pages/HomePage.jsx
> +      </ul>
수정했습니다~

2021-06-10 07:51 UTC, yujong-lee commented
말씀해신 내용을 이용해서 문제를 해결하였고, E2E테스트가 통과하는 것을 확인하는 것으로 기능개발은 일단 끝났습니다.

그런데 `module`을 `mock`하는 부분에서 제 예상과 다르게 동작하는 경우가 있습니다. 공식문서는 많이 읽어봤는데 혹시 제가 놓친게 있다면 링크만 걸어주셔도 좋습니다.

1. `__mocks`에서 `react-redux`를 삭제하더라도 문제가 없음.
[여기](https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options)를 보면 `Mocks a module with an auto-mocked version when it is being required.`라고 되어있습니다. 이는 `jest.mock('react-redux')`를 하는 것만으로도 `react-redux` 안의 모든 api `useSelector, useDispatch, useStore`를 `jest.fn()`으로 대체한다고 이해할 수 있고, 실제로 실험해보면 맞는 것 같습니다. 따라서 어짜피 `mockImplementation`을 하거나, `jest.mock()`에 두번쨰 인자로 `factory`를 넘길 것이라면 `__mocks__`는 필요없는 것 같습니다.

2.  `__mocks`에 `react-redux`가 있든 말든 상관없는 것과 반대로, `react-router`은 있으면 오류가 발생함
`react-router.js`내부에 `useParams`만 구현했을 때, 오류가 발생합니다. 제 추측으로는 `react-redux는` `useSelector, useDispatch, useStore`밖에 없는데  `react-router`는 `broswerRouter`같은 쓰이는 것들이 또 있어서 그런것까지 같이 mock이 되어서가 아닐까 합니다.

그런데 그렇다면 
```js
jest.mock('react-router', () => {
  const originalModule = jest.requireActual('react-router');

  return {
 // ... originalModule
    useParams: jest.fn().mockReturnValue({ id: 1 }),
  };
});
```
인터넷의 다른 예시 코드들은 저렇게  `originalModule `를 넣어주던데, 저걸 주석처리했을 때 오류가 발생해야할 것 같은데 또 이러면 통과를 합니다.

3. `react-router-dom`이 `react-router`의 일부라고 알고있는데 그러면 `import/mock`할 때는 하나로 통일해서 해주기만 하면 되는건가요? 다른 부분에서 의문이 있다보니까 직접 실험은 못해봤습니다.

2021-06-10 16:52 UTC, Kihyun92 requested changes
리뷰 드린것보다 더 잘 진행해주신 것 같군요 👍🏼 

남겨주신 커맨트에 답변을 남겨보면

1. 정리해주신게 맞습니다. 테스트에서 사용하는 외부 모듈을 mocking 해주거나 외부 라이브러리 함수들을 mocking 해주기 위해 사용하는 거죠ㅎㅎ
2. 어떤 오류가 나는지 남겨주시면 리뷰하기 더 좋을 것 같아요! 일단 originalModule에 대해서 처리해주신 부분에 주석을 했을때 테스트가 통과하는건 해당 테스트에서 useParams 외에 다른 함수들은 사용하지 않기 때문아닐까요?
3. 테스트해주는 컴포넌트에서 어떤 모듈을 import 해서 사용하는지에 따라 다를 것 같아요~

혹시 잘못된 부분이 있거나 의논이 필요하다면 말씀해주세요! 😄

2021-06-10 16:52 UTC, Kihyun92 commented on src/components/CategoriesContainer.jsx
> +    dispatch(loadRestaurants(region.name, selectedCategory.id));
레스토랑들을 로드할 때 상태값들을 받아서 다시 넘겨주고 있는 것 같아요.

`getState`를 사용하면 action 내에서 상태 값을 가져올 수 있습니다. 액션에서 선택한 지역과 카테고리 정보를 가져와서 처리하는건 어떨까요?

- https://redux.js.org/api/store#getstate

2021-06-10 16:52 UTC, Kihyun92 commented on src/pages/RestaurantPage.jsx
> +  return (
레스토랑 정보를 가져오는 동안 로딩을 노출해주는 처리가 있어도 좋을 것 같네요~

2021-06-10 16:52 UTC, Kihyun92 commented on src/redux_module/RestaurantSlice.js
> +      restaurant: {
restaurant 정보를 굳이 selected 객체에 포함할 필요는 없을 것 같아요~

2021-06-11 02:06 UTC, yujong-lee commented on src/components/CategoriesContainer.jsx
> +    dispatch(loadRestaurants(region.name, selectedCategory.id));
`getState`이 있는걸 잊고 있었네요. 수정했습니다. 혹시 `getState`에 대해서는 `mock-store`에 초깃값을 주는 것 외에 다른 좋은 테스트 방법이 있을까요?

2021-06-11 02:06 UTC, yujong-lee commented on src/redux_module/RestaurantSlice.js
> +      restaurant: {
`information`이라는 이름으로 밖으로 빼서 수정했습니다.

2021-06-11 05:21 UTC, yujong-lee commented on src/pages/RestaurantPage.jsx
> +  return (
리덕스에서 `boolean`값을 저장하고, `loadRestaurantInfo`에서 로딩이 완료되었을 때 그 값을 바꿔주고, `RestaurantPage`에서는 그 `boolean`값에 따라 렌더링을 다르게 해주는 방법이 떠오르는데요. 이것 때문에 리덕스에 값을 추가하는 것은 좀 과한 것 같기도 하네요. 혹시 다른 방법이 있나요?

2021-06-11 16:01 UTC, Kihyun92 commented on src/pages/RestaurantPage.jsx
> +  return (
RestaurantPageContainer에서 RestaurantPage에 넘겨줄 정보가 없을때 로딩으로 처리해주는건 어떨까요?

2021-06-11 16:02 UTC, Kihyun92 commented on src/components/CategoriesContainer.jsx
> +    dispatch(loadRestaurants(region.name, selectedCategory.id));
`mock-store` 로 초기 상태값을 초기화해주는 방법 밖에 생각나지 않네요 🤔 조금 더 고민해보겠습니다~

2021-06-11 16:06 UTC, Kihyun92 commented on src/redux_module/RestaurantSlice.js
> +      restaurant: {
개인적으로는 뭐에 대한 정보인지 한번 더 생각하게 만드는 네이밍 같아요. 조금 더 명확하게 해줘도 좋을 것 같습니다~

2021-06-11 16:13 UTC, Kihyun92 requested changes

2021-06-11 16:13 UTC, Kihyun92 commented on jest.config.js
> +      statements: 0,
이건 테스트를 위해 변경해보셨을까요~?

2021-06-11 16:13 UTC, Kihyun92 commented on src/App.jsx
> +        <Route component={NotFoundPage} />
컴포넌트 전반적으로 `**Page` 와 같은 네이밍이 필요할까요?

page 들이라는 의도를 드러내고 싶다면 pages 폴더를 통해 관리해주고, 컴포넌트 네이밍은 역할만 드러내 주는 방법도 있을 것 같아요~

2021-06-12 05:55 UTC, yujong-lee commented on src/App.jsx
> +        <Route component={NotFoundPage} />
무슨 말씀이신지 이해했습니다. 그래도 저는 `page`를 이름에도 붙이는게 덜 헷갈릴 것 같기는 한데 조금더 생각해보겠습니다.

2021-06-12 09:56 UTC, yujong-lee commented on jest.config.js
> +      statements: 0,
네. `api`테스트에서 `coverage`가 채워지지 않아서 그렇게 두었습니다.
이전 과제 리뷰에서 

> api.js 테스트에서 coverage가 100이 안되는데 이걸 어떻게 더 테스트할지 모르겠습니다. fetch자체를 mock하지 않는 이상 어려울 것 같은데요. 그런데 fetch는 브러우저에서 동작하는 함수인데, node-fetch같은걸 설치해서 해야할까요?
> 
> 이미 기본스펙으로 구현된 부분이기 때문에 fetch 부분은 굳이 테스트 코드를 작성하지 않아도 괜찮을 것 같아요.
> 
> 공부를 할 땐 테스트 코드를 다양하게 많이 작성해 보시라고 coverage 를 채우라고 하는데 실제로 coverage 가 테스트와 코드의 퀄리티를 보장해주는 건 아니기 때문에 그렇게까지 안해도 괜찮을 것 같아요.
> 보통은 라이브러리는 믿고 사용하는 편이에요.(믿고 사용하려면 내가 사용하는 라이브러리는 라이브러리 구현 내부에 테스트 코드가 있는게 좋겠죠?)

이렇게 리뷰를 받았는데, 다시 보니까 아예 0으로 하는건 좀 그렇고 `ignore`으로 빼주는게 나을 것 같아서 한번 수정해봤는데 어떠신지요

2021-06-12 09:56 UTC, yujong-lee commented on src/redux_module/RestaurantSlice.js
> +      restaurant: {
저도 작성하면서 살짝 생각하긴했습니다. ㅎㅎ 수정했습니다.

2021-06-12 09:57 UTC, yujong-lee commented on src/pages/RestaurantPage.jsx
> +  return (
좋네요!. 로딩 페이지가 복잡해지면 따로 빼줘도 되겠지만 지금은 일단 간단히 처리해봤습니다~

2021-06-12 16:06 UTC, Kihyun92 commented on jest.config.js
> +      statements: 0,
괜찮은 것 같습니다 😄

2021-06-12 16:09 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~ 👍🏼 

과제 풀이 영상 꼭 봐보시고, 처음 코드와 지금 코드가 어떻게 바뀌었는지 비교해보셔도 좋을 것 같습니다~

슬랙 채널에 회고 올려주시면 머지하겠습니다~~ 😊

2021-06-14 12:23 UTC, merged