Apply routing to restaurants app
CodeSoom/week6-assignment-1 pull request #9
Opened 2020-07-07 16:08 UTC by min-w-park

안녕하세요, 
항상 피드백 감사드립니다.
일단 작업한 부분까지 푸쉬 합니다!

2020-07-08 00:43 UTC, hannut91 reviewed
잘 진행하고 계시네요 ㅎㅎ 계속 진행해주세요 😃

2020-07-08 00:43 UTC, hannut91 commented on src/HomePage.test.jsx
> +import HomePage from './HomePage';
위에 빈 줄을 추가해서 라이브러리 임포트와 컴포넌트 임포트를 구분해주면 좋을 것 같아요

2020-07-10 09:28 UTC, min-w-park commented
이번 과제는 TDD 측면에서는 실패네요..
routing path에 exact으로 인해 발생한 에러를 찾기가 어려워 이것저것 해보다가, 막상 마지막엔 한꺼번에 처리했네요.. 
가설을 세우고, 테스트하고 확인하고 수정하고 하는게 어느순간 이런저런 시도로 인해 다 무너졌습니다..

2020-07-10 12:46 UTC, hannut91 commented
TDD는 꾸준히 연습하시면 되니까 너무 처음부터 잘하려고 할 필요는 없어요 ㅎㅎ 지금처럼 계속 시도해보시면 좋을 것 같아요

2020-07-10 13:22 UTC, hannut91 requested changes

2020-07-10 13:22 UTC, hannut91 commented on index.html
> +    <script src="/main.js"></script>
절대경로로 수정하셔서 문제를 해결해주셨군요! 웹팩의 publicPath를 변경하거나 `<head>`에 `<base href="/" >`를 추가해서 문제를 해결할 수도 있습니다.

See also
  - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  - https://webpack.js.org/guides/public-path/

2020-07-10 13:22 UTC, hannut91 commented on src/HomePage.test.jsx
> +  expect(container).toHaveTextContent('About');
About만 보이니까 어떤 의도인지 파악하기 어려운 것 같아요.

만약 이렇게 하면 어떻게 될까요?

```js
const links = ['About', 'Restaurants'];

links.forEach((link) => {
  expect(container).toHaveTextContent(link);
});
```

2020-07-10 13:22 UTC, hannut91 commented on src/RestaurantDetailPage.jsx
> +  const restaurant = useSelector(get('restaurant'));
순서가 useEffect가 아래로 오는게 더 좋을 것 같아요.

2020-07-10 13:22 UTC, hannut91 commented on src/RestaurantsContainer.test.jsx
> +  function renderApp() {
`renderApp`이 아니라 renderRestaurantsContainer가 더 좋을 것 같아요

2020-07-11 00:05 UTC, min-w-park commented on src/HomePage.test.jsx
> +  expect(container).toHaveTextContent('About');
오, 좋네요

2020-07-11 01:36 UTC, hannut91 approved these changes
고생하셨습니다! 코드의 중복을 제거하는 것과, `describe-context-it`의 사용법, 변수의 의미 더 명확하기 등을 조금만 더 신경써주시면 좋을 것 같아요! 

아샬님의 과제풀이를 통해 꼭 복습해주세요

2020-07-11 01:36 UTC, hannut91 commented on src/RestaurantDetail.test.jsx
> +      ));
여기 중복되는 곳도 함수로 추출하면 좋을 것 같아요

2020-07-11 01:36 UTC, hannut91 commented on src/RestaurantsContainer.test.jsx
> +  context('display restaurant', () => {
`context`에는 `when, with, without`만 사용하시는게 좋습니다. 

See also
  - http://www.betterspecs.org/#contexts

2020-07-11 01:36 UTC, hannut91 commented on src/actions.js
> +    const restaurantDetail = await fetchRestaurant({
레스토랑 상세 정보를 가져오기 때문에 restaurantDetail이라고 하신 것 같아요. 제가 보기에는 `restaurant`이라고만 해도 충분히 의미가 전달될 것 같아요. 그게 아니라면 setRestaurantDetail(restaurantDetail)이 더 낫겠죠

2020-09-12 06:44 UTC, closed without merging