6-1 레스토랑 상세 페이지 구현하기
CodeSoom/week6-assignment-1 pull request #96
Opened 2022-07-12 00:49 UTC by alstjr0183

2022-07-12 12:41 UTC, daadaadaah requested changes
일단 진행된 것까지 PR 만드신거 너무 잘하셨어요!👍
곳곳에 About이 아닌 AboutPage 라고 되어있어야 하는 부분이 있는데, 이부분 수정해주시고~ 계속 진행해주세요🚀

2022-07-12 12:41 UTC, daadaadaah commented on src/RestaurantsPage.test.jsx
> +  const KOREAN_FOOD = CATEGORIES[0];
오! 테스트 데이터를 변수명으로 의도를 드러내니까 테스트에 대해 좀더 명확히 생각할 수 있어서 좋은 것 같아요!👍 저도 나중에 활용해봐야겠어요😊

2022-07-12 12:41 UTC, daadaadaah commented on src/Routes.jsx
> +export default function Routes() {
Routes로 따로 빼서 관리하면 어떤 장점이 있나요?ㅎㅎ
저는 Routes로 빼는 것보다 App에서 관리하는게 이 앱에 어떤 페이지가 있는지 한눈에 알 수 있어서 App에서 관리하는 편이거든요!

2022-07-12 12:41 UTC, daadaadaah commented on src/RestaurantsPage.test.jsx
> +  it('RegionsContainer가 렌더링된다', () => {
좀더 의도를 드러내 보는 건 어떠세요?
예를 들어, 지역 이름이 보인다 또는 지역 버튼이 렌더링 된다 등으로!

2022-07-13 11:06 UTC, alstjr0183 commented on src/Routes.jsx
> +export default function Routes() {
저는 헤더쪽이랑 라우팅되는페이지쪽이랑 분리하고싶어서 그랬었는데 app에서 관리하게끔 다시 수정했습니다!!

2022-07-13 11:07 UTC, alstjr0183 commented on src/RestaurantsPage.test.jsx
> +  const KOREAN_FOOD = CATEGORIES[0];
앗 그부분은 기본과제에 셋팅되어있는거 토대로 사용한거여서 제가 생각한방법은 아닙니다..!!

2022-07-13 11:41 UTC, alstjr0183 commented on src/RestaurantsPage.test.jsx
> +  it('RegionsContainer가 렌더링된다', () => {
### 수정했습니다
지역버튼이 렌더링된다 ~~~ 이런식으로 추가해주었습니다!!

2022-07-13 11:50 UTC, alstjr0183 commented
안녕하세요 오늘은 피드백 주신거밖에 아직 수정을 못했습니다..ㅠ
### 질문이있습니다
api 호출시 cors 에러가 뜨는데 api쪽 문제일까요?!
<img width="758" alt="image" src="https://user-images.githubusercontent.com/57708817/178727032-842d6ca1-e0bc-4669-860f-f85801d19521.png">

2022-07-14 12:06 UTC, alstjr0183 commented
안녕하세요 오늘은 페이지가없을때랑 app의 테스트코드를 보완했습니다!

2022-07-14 12:48 UTC, daadaadaah commented
잘하셨습니다!ㅎㅎ계속 진행해주세요🚀
디스코드 채널에 올려드린 자료 한번 보시고 적용시켜보시구요~!😄

2022-07-17 11:48 UTC, alstjr0183 commented
안녕하세요 여행을 다녀오느라 진행을 못했네요 ㅠㅠ 이번주도 감사했습니다..! 강의보고 복습하겠습니다

2022-07-18 01:57 UTC, daadaadaah commented
좋습니당!! 과제 완성 못하셨지만 회고 하신 점 너무 잘하셨어요👍
강의 꼭 들으시고~ 다음주에 다시 달려봅시당🚀

2022-07-18 01:57 UTC, merged